### ISSUE TITLE
reduce mptcp options space usage

### ISSUE THREAD

**Issue by pabeni** [multipath-tcp/mptcp_net-next#10]
'struct mptcp_options_received' is part of tcp socket and can be zeroed per packet

'struct mptcp_out_options' is part of 'struct tcp_out_options', is allocated on the stack and is cleared once for each xmitted TCP packet.

Both the above mptcp data structer are wider than what is strictly needed, and could be shrinked, saving both memory and performances

**Comment by matttbe** [comment]
Note: can be closed when this series is applied: https://patchwork.ozlabs.org/project/mptcp/list/?series=173810&state=%2A&archive=both

**Comment by matttbe** [comment]
> Note: can be closed when this series is applied: https://patchwork.ozlabs.org/project/mptcp/list/?series=173810&state=%2A&archive=both

This series has been applied, we can close this issue.
