### ISSUE TITLE
[syzkaller] KASAN: null-ptr-deref Write in add_wait_queue

### ISSUE THREAD

**Issue by cpaasch** [multipath-tcp/mptcp_net-next#100]
```
==================================================================
BUG: KASAN: null-ptr-deref in instrument_atomic_write include/linux/instrumented.h:71 [inline]
BUG: KASAN: null-ptr-deref in atomic_try_cmpxchg_acquire include/asm-generic/atomic-instrumented.h:705 [inline]
BUG: KASAN: null-ptr-deref in queued_spin_lock include/asm-generic/qspinlock.h:82 [inline]
BUG: KASAN: null-ptr-deref in do_raw_spin_lock_flags include/linux/spinlock.h:195 [inline]
BUG: KASAN: null-ptr-deref in __raw_spin_lock_irqsave include/linux/spinlock_api_smp.h:119 [inline]
BUG: KASAN: null-ptr-deref in _raw_spin_lock_irqsave+0x73/0xe0 kernel/locking/spinlock.c:159
Write of size 4 at addr 0000000000000000 by task syz-executor.0/27264

CPU: 1 PID: 27264 Comm: syz-executor.0 Not tainted 5.9.0-rc8 #27
Hardware name: QEMU Standard PC (i440FX + PIIX, 1996), BIOS rel-1.13.0-0-gf21b5a4aeb02-prebuilt.qemu.org 04/01/2014
Call Trace:
 __dump_stack lib/dump_stack.c:77 [inline]
 dump_stack+0xbe/0xfe lib/dump_stack.c:118
 __kasan_report mm/kasan/report.c:517 [inline]
 kasan_report.cold+0x5/0x37 mm/kasan/report.c:530
 check_memory_region_inline mm/kasan/generic.c:186 [inline]
 check_memory_region+0x14e/0x1b0 mm/kasan/generic.c:192
 instrument_atomic_write include/linux/instrumented.h:71 [inline]
 atomic_try_cmpxchg_acquire include/asm-generic/atomic-instrumented.h:705 [inline]
 queued_spin_lock include/asm-generic/qspinlock.h:82 [inline]
 do_raw_spin_lock_flags include/linux/spinlock.h:195 [inline]
 __raw_spin_lock_irqsave include/linux/spinlock_api_smp.h:119 [inline]
 _raw_spin_lock_irqsave+0x73/0xe0 kernel/locking/spinlock.c:159
 add_wait_queue+0x46/0x170 kernel/sched/wait.c:23
 sk_stream_wait_close net/core/stream.c:101 [inline]
 sk_stream_wait_close+0x153/0x330 net/core/stream.c:96
 __tcp_close+0x5ca/0x1110 net/ipv4/tcp.c:2493
 __mptcp_close_ssk+0x1ea/0x380 net/mptcp/protocol.c:1750
 __mptcp_destroy_sock+0x49c/0x770 net/mptcp/protocol.c:2110
 mptcp_close+0x5cc/0x890 net/mptcp/protocol.c:2162
 inet_release+0xe9/0x1f0 net/ipv4/af_inet.c:434
 __sock_release+0xd2/0x280 net/socket.c:596
 sock_close+0x15/0x20 net/socket.c:1277
 __fput+0x276/0x960 fs/file_table.c:281
 task_work_run+0x109/0x1d0 kernel/task_work.c:141
 tracehook_notify_resume include/linux/tracehook.h:188 [inline]
 exit_to_user_mode_loop kernel/entry/common.c:165 [inline]
 exit_to_user_mode_prepare+0x136/0x140 kernel/entry/common.c:192
 syscall_exit_to_user_mode+0x26/0x170 kernel/entry/common.c:267
 entry_SYSCALL_64_after_hwframe+0x44/0xa9
RIP: 0033:0x7f34eb06128d
Code: c1 20 00 00 75 10 b8 03 00 00 00 0f 05 48 3d 01 f0 ff ff 73 31 c3 48 83 ec 08 e8 ee fb ff ff 48 89 04 24 b8 03 00 00 00 0f 05 <48> 8b 3c 24 48 89 c2 e8 37 fc ff ff 48 89 d0 48 83 c4 08 48 3d 01
RSP: 002b:00007fff799a9150 EFLAGS: 00000293 ORIG_RAX: 0000000000000003
RAX: 0000000000000000 RBX: 0000000000000004 RCX: 00007f34eb06128d
RDX: 0000001b2bf20000 RSI: 0000000000000b96 RDI: 0000000000000003
RBP: 0000000000000001 R08: 00000000002019a8 R09: 000000000000067e
R10: 000000007b106b96 R11: 0000000000000293 R12: 000000000069c980
R13: 000000000069c980 R14: 00000000000001f4 R15: 0000000000195c71
==================================================================
```

HEAD is at:
2229aa47069b ("DO-NOT-MERGE: mptcp: enabled by default")  (HEAD, tag: export/20201015T052017, mptcp_net-next/export) (13 hours ago) <Matthieu Baerts>
e3a6adb4c880 ("DO-NOT-MERGE: mptcp: use kmalloc on kasan build")  (13 hours ago) <Paolo Abeni>
a70060b9e1aa ("mptcp: send explicit ack on delayed ack_seq incr")  (13 hours ago) <Paolo Abeni>
374eed7700b2 ("mptcp: keep track of advertised windows right edge")  (13 hours ago) <Florian Westphal>
8378c1afaaa9 ("mptcp: rework poll+nospace handling")  (13 hours ago) <Florian Westphal>
d8463fbc00e4 ("mptcp: try to push pending data on snd una updates")  (13 hours ago) <Paolo Abeni>
b731900568d7 ("mptcp: move page frag allocation in mptcp_sendmsg()")  (13 hours ago) <Paolo Abeni>
87c30b978039 ("mptcp: refactor shutdown and close")  (13 hours ago) <Paolo Abeni>
52f36208ca29 ("mptcp: introduce MPTCP snd_nxt")  (13 hours ago) <Paolo Abeni>
6f3da02b398d ("mptcp: add accounting for pending data")  (13 hours ago) <Paolo Abeni>
29341dcc284f ("mptcp: reduce the arguments of mptcp_sendmsg_frag")  (13 hours ago) <Paolo Abeni>
f39e0646adad ("mptcp: introduce mptcp_schedule_work")  (13 hours ago) <Paolo Abeni>
d22ae16552f0 ("tcp: factor out __tcp_close() helper")  (13 hours ago) <Paolo Abeni>
f584bdddf7a3 ("selftests: mptcp: add ADD_ADDR timeout test case")  (13 hours ago) <Geliang Tang>
4e829f2ac041 ("mptcp: add a new sysctl add_addr_timeout")  (13 hours ago) <Geliang Tang>
c8f08dc983f6 ("mptcp: split mptcp_clean_una function")  (13 hours ago) <Florian Westphal>
ab67d804132c ("tcp: propagate MPTCP skb extensions on xmit splits")  (13 hours ago) <Paolo Abeni>
503d07ba7aac ("mptcp: use _fast lock version in __mptcp_move_skbs")  (13 hours ago) <Florian Westphal>
682ae73aa83a ("mptcp: adjust mptcp receive buffer limit if subflow has larger one")  (13 hours ago) <Florian Westphal>
b112bb722fe7 ("bpf:selftests: add bpf_mptcp_sock() verifier tests")  (13 hours ago) <Nicolas Rybowski>
54ad37ce60c2 ("bpf:selftests: add MPTCP test base")  (13 hours ago) <Nicolas Rybowski>
99fa4f0decf2 ("bpf: add 'bpf_mptcp_sock' structure and helper")  (13 hours ago) <Nicolas Rybowski>
ab21791b86e4 ("mptcp: attach subflow socket to parent cgroup")  (13 hours ago) <Nicolas Rybowski>
7d0ec462bd09 ("bpf: expose is_mptcp flag to bpf_tcp_sock")  (13 hours ago) <Nicolas Rybowski>
7708163727ba ("net: mptcp: make DACK4/DACK8 usage consistent among all subflows")  (13 hours ago) <Davide Caratti>
d47745679578 ("mptcp: subflows garbage collection")  (13 hours ago) <Paolo Abeni>
4a9600a3c4cd ("mptcp: fix fallback for MP_JOIN subflows")  (13 hours ago) <Paolo Abeni>
d25e2e9388ed ("netfilter: restore NF_INET_NUMHOOKS")  (mptcp_net-next/net-next) (15 hours ago) <Pablo Neira Ayuso>
50172733d01c ("Merge tag 'mlx5-updates-2020-10-12' of git://git.kernel.org/pub/scm/linux/kernel/git/saeed/linux")  (2 days ago) <Jakub Kicinski>

syzkaller-repro:
```
# {Threaded:true Collide:true Repeat:true RepeatTimes:0 Procs:8 Sandbox:none Fault:false FaultCall:-1 FaultNth:0 Leak:false NetInjection:true NetDevices:true NetReset:true Cgroups:true BinfmtMisc:true CloseFDs:true KCSAN:false DevlinkPCI:false USB:false VhciInjection:false Wifi:false UseTmpDir:true HandleSegv:true Repro:false Trace:false}
r0 = socket$inet_mptcp(0x2, 0x1, 0x106)
r1 = socket$inet_mptcp(0x2, 0x1, 0x106)
setsockopt$sock_linger(r0, 0x1, 0xd, &(0x7f0000000280)={0x1, 0x5}, 0x8)
connect$inet(r0, &(0x7f0000000040)={0x2, 0x4e20, @loopback}, 0x4d)
accept(r1, 0x0, 0x0)
dup3(r0, r0, 0x80000)
```

**Comment by matttbe** [comment]
Closes thanks to Paolo's patch: e3514ae223bd
