### ISSUE TITLE
[syzkaller] WARNING in inet_csk_listen_stop

### ISSUE THREAD

**Issue by cpaasch** [multipath-tcp/mptcp_net-next#103]
```
------------[ cut here ]------------
WARNING: CPU: 0 PID: 4615 at net/ipv4/inet_connection_sock.c:1031 inet_csk_listen_stop+0x8e8/0xad0 net/ipv4/inet_connection_sock.c:1031
Modules linked in:
CPU: 0 PID: 4615 Comm: syz-executor.4 Not tainted 5.9.0 #37
Hardware name: QEMU Standard PC (i440FX + PIIX, 1996), BIOS rel-1.13.0-0-gf21b5a4aeb02-prebuilt.qemu.org 04/01/2014
RIP: 0010:inet_csk_listen_stop+0x8e8/0xad0 net/ipv4/inet_connection_sock.c:1031
Code: 03 00 00 00 e8 79 b2 3d ff e9 ad f9 ff ff e8 1f 76 ba fe be 02 00 00 00 4c 89 f7 e8 62 b2 3d ff e9 14 f9 ff ff e8 08 76 ba fe <0f> 0b e9 97 f8 ff ff e8 fc 75 ba fe be 03 00 00 00 4c 89 f7 e8 3f
RSP: 0018:ffffc900037f7948 EFLAGS: 00010293
RAX: ffff88810a349c80 RBX: ffff888114ee1b00 RCX: ffffffff827b14cd
RDX: 0000000000000000 RSI: ffffffff827b1c38 RDI: 0000000000000005
RBP: ffff88810a2a8000 R08: ffff88810a349c80 R09: fffff520006fef1f
R10: 0000000000000003 R11: fffff520006fef1e R12: ffff888114ee2d00
R13: dffffc0000000000 R14: 0000000000000001 R15: ffff888114ee1d68
FS:  00007f2ac1945700(0000) GS:ffff88811b400000(0000) knlGS:0000000000000000
CS:  0010 DS: 0000 ES: 0000 CR0: 0000000080050033
CR2: 00007ffd44798bc0 CR3: 0000000109810002 CR4: 0000000000170ef0
Call Trace:
 __tcp_close+0xd86/0x1110 net/ipv4/tcp.c:2433
 __mptcp_close_ssk+0x256/0x430 net/mptcp/protocol.c:1761
 __mptcp_destroy_sock+0x49b/0x770 net/mptcp/protocol.c:2127
 mptcp_close+0x62d/0x910 net/mptcp/protocol.c:2184
 inet_release+0xe9/0x1f0 net/ipv4/af_inet.c:434
 __sock_release+0xd2/0x280 net/socket.c:596
 sock_close+0x15/0x20 net/socket.c:1277
 __fput+0x276/0x960 fs/file_table.c:281
 task_work_run+0x109/0x1d0 kernel/task_work.c:151
 get_signal+0xe8f/0x1d40 kernel/signal.c:2561
 arch_do_signal+0x88/0x1b60 arch/x86/kernel/signal.c:811
 exit_to_user_mode_loop kernel/entry/common.c:161 [inline]
 exit_to_user_mode_prepare+0x9b/0xf0 kernel/entry/common.c:191
 syscall_exit_to_user_mode+0x22/0x150 kernel/entry/common.c:266
 entry_SYSCALL_64_after_hwframe+0x44/0xa9
RIP: 0033:0x7f2ac1254469
Code: 00 f3 c3 66 2e 0f 1f 84 00 00 00 00 00 0f 1f 40 00 48 89 f8 48 89 f7 48 89 d6 48 89 ca 4d 89 c2 4d 89 c8 4c 8b 4c 24 08 0f 05 <48> 3d 01 f0 ff ff 73 01 c3 48 8b 0d ff 49 2b 00 f7 d8 64 89 01 48
RSP: 002b:00007f2ac1944dc8 EFLAGS: 00000246 ORIG_RAX: 0000000000000010
RAX: ffffffffffffffbf RBX: 000000000069bf00 RCX: 00007f2ac1254469
RDX: 0000000000000000 RSI: 0000000000008982 RDI: 0000000000000003
RBP: 000000000069bf00 R08: 0000000000000000 R09: 0000000000000000
R10: 0000000000000000 R11: 0000000000000246 R12: 000000000069bf0c
R13: 00007ffeb53f178f R14: 00000000004668b0 R15: 0000000000000003
```

HEAD is at:
0114cba6dbf2 ("DO-NOT-MERGE: mptcp: enabled by default")  (HEAD, tag: export/20201024T195715, mptcp_net-next/export) (4 days ago) <Matthieu Baerts>
f61d98f7a954 ("DO-NOT-MERGE: mptcp: use kmalloc on kasan build")  (4 days ago) <Paolo Abeni>
f2ff7f11f9a7 ("selftests: mptcp: add ADD_ADDR IPv6 test cases")  (4 days ago) <Geliang Tang>
417851835a81 ("mptcp: send out dedicated ADD_ADDR packet")  (4 days ago) <Geliang Tang>
d887378271f1 ("mptcp: change add_addr_signal type")  (4 days ago) <Geliang Tang>
672855c44b26 ("mptcp: keep unaccepted MPC subflow into join list")  (4 days ago) <Paolo Abeni>
d2388ff1e42f ("selftests: mptcp: add link failure test case")  (4 days ago) <Florian Westphal>
44ac18265dad ("mptcp: skip to next candidate if subflow has unacked data")  (4 days ago) <Florian Westphal>
7c71a8e63b4a ("mptcp: send explicit ack on delayed ack_seq incr")  (4 days ago) <Paolo Abeni>
5946644421b0 ("mptcp: keep track of advertised windows right edge")  (4 days ago) <Florian Westphal>
2188d9026158 ("mptcp: rework poll+nospace handling")  (4 days ago) <Florian Westphal>
02822d35f415 ("mptcp: try to push pending data on snd una updates")  (4 days ago) <Paolo Abeni>
4ffa0020bb84 ("mptcp: move page frag allocation in mptcp_sendmsg()")  (4 days ago) <Paolo Abeni>
69e9c8aa6ca1 ("mptcp: refactor shutdown and close")  (4 days ago) <Paolo Abeni>
47a87aef622d ("mptcp: introduce MPTCP snd_nxt")  (4 days ago) <Paolo Abeni>
6f791e40e1b9 ("mptcp: add accounting for pending data")  (4 days ago) <Paolo Abeni>
b0dd9f043538 ("mptcp: reduce the arguments of mptcp_sendmsg_frag")  (4 days ago) <Paolo Abeni>
db2c0dbac7f8 ("mptcp: introduce mptcp_schedule_work")  (4 days ago) <Paolo Abeni>
ec8e220dfac8 ("tcp: factor out __tcp_close() helper")  (4 days ago) <Paolo Abeni>
1e5b794f2cac ("mptcp: use tcp_build_frag()")  (4 days ago) <Paolo Abeni>
0d6e197d8c7e ("tcp: factor out tcp_build_frag()")  (4 days ago) <Paolo Abeni>
31fdec7ae122 ("selftests: mptcp: add ADD_ADDR timeout test case")  (4 days ago) <Geliang Tang>
0c91e211ffed ("mptcp: add a new sysctl add_addr_timeout")  (4 days ago) <Geliang Tang>
93dc437ba3c1 ("mptcp: split mptcp_clean_una function")  (4 days ago) <Florian Westphal>
9025b69074d6 ("tcp: propagate MPTCP skb extensions on xmit splits")  (4 days ago) <Paolo Abeni>
1ed5e4cd069c ("mptcp: use _fast lock version in __mptcp_move_skbs")  (4 days ago) <Florian Westphal>
c5a240ce86de ("mptcp: adjust mptcp receive buffer limit if subflow has larger one")  (4 days ago) <Florian Westphal>
03f061409b51 ("bpf:selftests: add bpf_mptcp_sock() verifier tests")  (4 days ago) <Nicolas Rybowski>
c746d1dddb67 ("bpf:selftests: add MPTCP test base")  (4 days ago) <Nicolas Rybowski>
8e50f33b0694 ("bpf: add 'bpf_mptcp_sock' structure and helper")  (4 days ago) <Nicolas Rybowski>
d6ab3ae2ff4c ("mptcp: attach subflow socket to parent cgroup")  (4 days ago) <Nicolas Rybowski>
9e9fc7dcff52 ("bpf: expose is_mptcp flag to bpf_tcp_sock")  (4 days ago) <Nicolas Rybowski>
80fd952a6edc ("acpica: fix compilation error")  (4 days ago) <Matthieu Baerts>
3cb12d27ff65 ("Merge tag 'net-5.10-rc1' of git://git.kernel.org/pub/scm/linux/kernel/git/netdev/net")  (mptcp_net-next/net-next) (5 days ago) <Linus Torvalds>

syzkaller-reproducer:
```
# {Threaded:true Collide:true Repeat:true RepeatTimes:0 Procs:8 Sandbox:none Fault:false FaultCall:-1 FaultNth:0 Leak:false NetInjection:true NetDevices:true NetReset:true Cgroups:true BinfmtMisc:true CloseFDs:true KCSAN:false DevlinkPCI:false USB:false VhciInjection:false Wifi:false UseTmpDir:true HandleSegv:true Repro:false Trace:false}
r0 = socket$inet_mptcp(0x2, 0x1, 0x106)
bind$inet(r0, &(0x7f00000013c0)={0x2, 0x4e20}, 0x10)
listen(r0, 0x0)
r1 = socket$inet_mptcp(0x2, 0x1, 0x106)
connect$inet(r1, &(0x7f0000000040)={0x2, 0x4e20, @remote}, 0x10)
socket$inet_udp(0x2, 0x2, 0x0)
sendmmsg(r1, &(0x7f00000007c0)=[{{0x0, 0x0, &(0x7f00000011c0)=[{&(0x7f00000002c0)='w', 0x10003}], 0x1}}], 0x1, 0x0)
ioctl$sock_SIOCGIFVLAN_SET_VLAN_NAME_TYPE_CMD(r0, 0x8982, 0x0)
socket$inet_tcp(0x2, 0x1, 0x0)
```

**Comment by cpaasch** [comment]
Still happens on:

f590f84bdfb9 ("DO-NOT-MERGE: mptcp: enabled by default")  (HEAD, tag: export/20201119T122135, mptcp_net-next/export) (5 hours ago) <Matthieu Baerts>
0dbb372a76fd ("DO-NOT-MERGE: mptcp: use kmalloc on kasan build")  (5 hours ago) <Paolo Abeni>
5ffc66739ba3 ("mptcp: print out port and ahmac when receiving ADD_ADDR")  (5 hours ago) <Geliang Tang>
4c67d472a561 ("mptcp: add port parameter for mptcp_pm_announce_addr")  (5 hours ago) <Geliang Tang>
78a647776c1f ("mptcp: send out dedicated packet for ADD_ADDR using port")  (5 hours ago) <Geliang Tang>
dd48e13964f0 ("mptcp: add the outgoing ADD_ADDR port support")  (5 hours ago) <Geliang Tang>
0d630ad7f4d7 ("mptcp: use adding up size to get ADD_ADDR length")  (5 hours ago) <Geliang Tang>
033d49e9295d ("mptcp: add port support for ADD_ADDR suboption writing")  (5 hours ago) <Geliang Tang>
3954d880381b ("mptcp: unify ADD_ADDR and ADD_ADDR6 suboptions writing")  (5 hours ago) <Geliang Tang>
64db857df90c ("mptcp: unify ADD_ADDR and echo suboptions writing")  (5 hours ago) <Geliang Tang>
c77dbc7e029c ("mptcp: refine MPTCP-level ack scheduling")  (5 hours ago) <Paolo Abeni>
ff15ab9ba2b0 ("mptcp: track window announced to peer")  (5 hours ago) <Florian Westphal>
566216b2a18a ("selftests: mptcp: add ADD_ADDR IPv6 test cases")  (5 hours ago) <Geliang Tang>
b9af7b82b8b2 ("mptcp: send out dedicated ADD_ADDR packet")  (5 hours ago) <Geliang Tang>
4a6e7393f623 ("mptcp: change add_addr_signal type")  (5 hours ago) <Geliang Tang>
5d9bded54b03 ("mptcp: keep unaccepted MPC subflow into join list")  (5 hours ago) <Paolo Abeni>
9e4341bcd1d3 ("selftests: mptcp: add link failure test case")  (5 hours ago) <Florian Westphal>
d3e9aa3b2647 ("mptcp: skip to next candidate if subflow has unacked data")  (5 hours ago) <Florian Westphal>
48c62fbc993f ("bpf:selftests: add bpf_mptcp_sock() verifier tests")  (5 hours ago) <Nicolas Rybowski>
1b0925d58a3e ("bpf:selftests: add MPTCP test base")  (5 hours ago) <Nicolas Rybowski>
c451b33c4445 ("bpf: add 'bpf_mptcp_sock' structure and helper")  (5 hours ago) <Nicolas Rybowski>
dda9790164d8 ("mptcp: attach subflow socket to parent cgroup")  (5 hours ago) <Nicolas Rybowski>
e1b1fef075cf ("bpf: expose is_mptcp flag to bpf_tcp_sock")  (5 hours ago) <Nicolas Rybowski>
92a781d36dbb ("mptcp: fix state tracking for fallback socket")  (5 hours ago) <Paolo Abeni>
5d026294a8e0 ("mptcp: drop WORKER_RUNNING status bit")  (5 hours ago) <Paolo Abeni>
c2a10b972788 ("mptcp: update rtx timeout only if required.")  (5 hours ago) <Paolo Abeni>
e76d795ecb5b ("nfc: s3fwrn5: Change the error code")  (mptcp_net-next/net-next) (15 hours ago) <Bongsu Jeon>

CONFIG-file: 
[CONFIG.txt](https://github.com/multipath-tcp/mptcp_net-next/files/5568357/CONFIG.txt)

**Comment by pabeni** [comment]
the PM/workqueue is racing withinet_csk_listen_stop()/inet_child_forget() on some unaccepted ssk. hard to fix IMHO

**Comment by matttbe** [comment]
Can be closed thanks to this commit from @pabeni 

  46712436b452: mptcp: link MPC subflow into msk only after accept
