### ISSUE TITLE
[syzkaller] general protection fault in skb_release_data

### ISSUE THREAD

**Issue by cpaasch** [multipath-tcp/mptcp_net-next#104]
```
TCP: request_sock_subflow: Possible SYN flooding on port 20000. Sending cookies.  Check SNMP counters.
general protection fault, probably for non-canonical address 0xdffffc0000044762: 0000 [#1] SMP KASAN
KASAN: probably user-memory-access in range [0x0000000000223b10-0x0000000000223b17]
CPU: 1 PID: 2183 Comm: kworker/1:3 Not tainted 5.10.0-rc6 #52
Hardware name: QEMU Standard PC (i440FX + PIIX, 1996), BIOS rel-1.13.0-0-gf21b5a4aeb02-prebuilt.qemu.org 04/01/2014
Workqueue: events mptcp_worker
RIP: 0010:compound_head include/linux/page-flags.h:185 [inline]
RIP: 0010:put_page include/linux/mm.h:1180 [inline]
RIP: 0010:__skb_frag_unref include/linux/skbuff.h:3024 [inline]
RIP: 0010:skb_release_data+0x217/0x7c0 net/core/skbuff.c:609
Code: 8e ec 00 00 00 e8 29 3f d9 fe 48 89 d8 48 c1 e8 03 42 80 3c 30 00 0f 85 bd 04 00 00 48 8b 2b 48 8d 7d 08 48 89 f8 48 c1 e8 03 <42> 80 3c 30 00 0f 85 da 04 00 00 48 8b 45 08 31 ff 49 89 c4 48 89
RSP: 0018:ffffc90000140858 EFLAGS: 00010202
RAX: 0000000000044762 RBX: ffff88810431e8f0 RCX: ffffffff825be503
RDX: 0000000000000000 RSI: ffffffff825be577 RDI: 0000000000223b10
RBP: 0000000000223b08 R08: ffff888102074740 R09: ffffed1020863d1d
R10: ffff88810431e8e3 R11: ffffed1020863d1c R12: ffff88810431e8c0
R13: 0000000000000000 R14: dffffc0000000000 R15: ffff888023118dc0
FS:  0000000000000000(0000) GS:ffff88811b500000(0000) knlGS:0000000000000000
CS:  0010 DS: 0000 ES: 0000 CR0: 0000000080050033
CR2: 0000001b33422000 CR3: 000000010c873001 CR4: 0000000000170ee0
Call Trace:
 <IRQ>
 skb_release_all+0x46/0x60 net/core/skbuff.c:669
 __kfree_skb+0x11/0x20 net/core/skbuff.c:683
 tcp_data_queue+0x2505/0x4770 net/ipv4/tcp_input.c:4930
 tcp_rcv_established+0x851/0x1c80 net/ipv4/tcp_input.c:5870
 tcp_v4_do_rcv+0x602/0x8b0 net/ipv4/tcp_ipv4.c:1673
 tcp_v4_rcv+0x2533/0x2e60 net/ipv4/tcp_ipv4.c:2055
 ip_protocol_deliver_rcu+0x2b/0x200 net/ipv4/ip_input.c:204
 ip_local_deliver_finish net/ipv4/ip_input.c:231 [inline]
 NF_HOOK include/linux/netfilter.h:409 [inline]
 ip_local_deliver+0x2da/0x390 net/ipv4/ip_input.c:252
 dst_input include/net/dst.h:447 [inline]
 ip_rcv_finish net/ipv4/ip_input.c:428 [inline]
 ip_rcv_finish net/ipv4/ip_input.c:414 [inline]
 NF_HOOK include/linux/netfilter.h:409 [inline]
 ip_rcv+0xef/0x140 net/ipv4/ip_input.c:539
 __netif_receive_skb_one_core+0x197/0x1e0 net/core/dev.c:5305
 __netif_receive_skb+0x27/0x1c0 net/core/dev.c:5419
 process_backlog+0x1e5/0x6e0 net/core/dev.c:6309
 napi_poll net/core/dev.c:6787 [inline]
 net_rx_action+0x3fa/0xe30 net/core/dev.c:6870
 __do_softirq+0x187/0x585 kernel/softirq.c:298
 asm_call_irq_on_stack+0x12/0x20
 </IRQ>
 __run_on_irqstack arch/x86/include/asm/irq_stack.h:26 [inline]
 run_on_irqstack_cond arch/x86/include/asm/irq_stack.h:77 [inline]
 do_softirq_own_stack+0x32/0x40 arch/x86/kernel/irq_64.c:77
 do_softirq.part.0+0x26/0x30 kernel/softirq.c:343
 do_softirq arch/x86/include/asm/preempt.h:26 [inline]
 __local_bh_enable_ip+0x46/0x50 kernel/softirq.c:195
 local_bh_enable include/linux/bottom_half.h:32 [inline]
 rcu_read_unlock_bh include/linux/rcupdate.h:730 [inline]
 ip_finish_output2+0x71e/0x17e0 net/ipv4/ip_output.c:231
 __ip_finish_output+0x516/0x880 net/ipv4/ip_output.c:308
 dst_output include/net/dst.h:441 [inline]
 ip_local_out+0x18a/0x1f0 net/ipv4/ip_output.c:126
 __ip_queue_xmit+0x77c/0x1500 net/ipv4/ip_output.c:532
 __tcp_transmit_skb+0x2bed/0x36a0 net/ipv4/tcp_output.c:1405
 __tcp_send_ack.part.0+0x3f0/0x660 net/ipv4/tcp_output.c:3971
 __tcp_send_ack net/ipv4/tcp_output.c:3977 [inline]
 tcp_send_ack+0x7d/0xa0 net/ipv4/tcp_output.c:3977
 mptcp_pm_nl_add_addr_send_ack+0x19c/0x330 net/mptcp/pm_netlink.c:428
 mptcp_pm_create_subflow_or_signal_addr+0xd42/0x1090 net/mptcp/pm_netlink.c:330
 pm_work net/mptcp/protocol.c:2181 [inline]
 mptcp_worker+0x1003/0x1560 net/mptcp/protocol.c:2277
 process_one_work+0x8d3/0x1200 kernel/workqueue.c:2272
 worker_thread+0x9c/0x1090 kernel/workqueue.c:2418
 kthread+0x303/0x410 kernel/kthread.c:292
 ret_from_fork+0x22/0x30 arch/x86/entry/entry_64.S:296
Modules linked in:
Dumping ftrace buffer:
   (ftrace buffer empty)
---[ end trace 3ab598cf6b077bbe ]---
RIP: 0010:compound_head include/linux/page-flags.h:185 [inline]
RIP: 0010:put_page include/linux/mm.h:1180 [inline]
RIP: 0010:__skb_frag_unref include/linux/skbuff.h:3024 [inline]
RIP: 0010:skb_release_data+0x217/0x7c0 net/core/skbuff.c:609
Code: 8e ec 00 00 00 e8 29 3f d9 fe 48 89 d8 48 c1 e8 03 42 80 3c 30 00 0f 85 bd 04 00 00 48 8b 2b 48 8d 7d 08 48 89 f8 48 c1 e8 03 <42> 80 3c 30 00 0f 85 da 04 00 00 48 8b 45 08 31 ff 49 89 c4 48 89
RSP: 0018:ffffc90000140858 EFLAGS: 00010202
RAX: 0000000000044762 RBX: ffff88810431e8f0 RCX: ffffffff825be503
RDX: 0000000000000000 RSI: ffffffff825be577 RDI: 0000000000223b10
RBP: 0000000000223b08 R08: ffff888102074740 R09: ffffed1020863d1d
R10: ffff88810431e8e3 R11: ffffed1020863d1c R12: ffff88810431e8c0
R13: 0000000000000000 R14: dffffc0000000000 R15: ffff888023118dc0
FS:  0000000000000000(0000) GS:ffff88811b500000(0000) knlGS:0000000000000000
CS:  0010 DS: 0000 ES: 0000 CR0: 0000000080050033
CR2: 0000001b33422000 CR3: 000000010c873001 CR4: 0000000000170ee0
```

HEAD is at
05cb27b258ba ("DO-NOT-MERGE: mptcp: enabled by default")  (HEAD, tag: export/20201209T060936, mptcp_net-next/export) (12 hours ago) <Matthieu Baerts>
525593cf6729 ("DO-NOT-MERGE: mptcp: add GitHub Actions")  (12 hours ago) <Matthieu Baerts>
6aa8731bf964 ("DO-NOT-MERGE: mptcp: use kmalloc on kasan build")  (12 hours ago) <Paolo Abeni>
2227bfd2f6bd ("mptcp: let MPTCP create max size skbs")  (12 hours ago) <Paolo Abeni>
908c6322325f ("mptcp: pm: simplify select_local_address()")  (12 hours ago) <Paolo Abeni>
a771b76cf445 ("mptcp: parse and act on incoming FASTCLOSE option")  (12 hours ago) <Florian Westphal>
7dbc6b7828a9 ("tcp: parse mptcp options contained in reset packets")  (12 hours ago) <Florian Westphal>
4598a67e2407 ("mptcp: hold mptcp socket before calling tcp_done")  (12 hours ago) <Florian Westphal>
363050070e94 ("mptcp: use MPTCPOPT_HMAC_LEN macro")  (12 hours ago) <Geliang Tang>
905c00c9fd2b ("selftests: mptcp: add the flush addrs testcase")  (12 hours ago) <Geliang Tang>
2d0de9b2d12d ("mptcp: remove address when netlink flushes addrs")  (12 hours ago) <Geliang Tang>
389cb8de6149 ("mptcp: use the variable sk instead of open-coding")  (12 hours ago) <Geliang Tang>
62ad6da7d479 ("mptcp: rename add_addr_signal and mptcp_add_addr_status")  (12 hours ago) <Geliang Tang>
56607a997374 ("mptcp: drop rm_addr_signal flag")  (12 hours ago) <Geliang Tang>
f5614981a113 ("mptcp: print out port and ahmac when receiving ADD_ADDR")  (12 hours ago) <Geliang Tang>
faec918a7bb5 ("mptcp: add port parameter for mptcp_pm_announce_addr")  (12 hours ago) <Geliang Tang>
1bab32fc5774 ("mptcp: send out dedicated packet for ADD_ADDR using port")  (12 hours ago) <Geliang Tang>
a7429bbd1f46 ("mptcp: add the outgoing ADD_ADDR port support")  (12 hours ago) <Geliang Tang>
a8787a82b5a1 ("mptcp: use adding up size to get ADD_ADDR length")  (12 hours ago) <Geliang Tang>
1690597e3a47 ("mptcp: add port support for ADD_ADDR suboption writing")  (12 hours ago) <Geliang Tang>
4021cd88160f ("mptcp: unify ADD_ADDR and ADD_ADDR6 suboptions writing")  (12 hours ago) <Geliang Tang>
0b863095033d ("mptcp: unify ADD_ADDR and echo suboptions writing")  (12 hours ago) <Geliang Tang>
c855f8921120 ("bpf:selftests: add bpf_mptcp_sock() verifier tests")  (12 hours ago) <Nicolas Rybowski>
0eaea54e6080 ("bpf:selftests: add MPTCP test base")  (12 hours ago) <Nicolas Rybowski>
eed59abf1b73 ("bpf: add 'bpf_mptcp_sock' structure and helper")  (12 hours ago) <Nicolas Rybowski>
6dd1da955adf ("mptcp: attach subflow socket to parent cgroup")  (12 hours ago) <Nicolas Rybowski>
58a4d0cfd053 ("bpf: expose is_mptcp flag to bpf_tcp_sock")  (12 hours ago) <Nicolas Rybowski>
d188dfee6155 ("mptcp: be careful on subflows shutdown")  (12 hours ago) <Paolo Abeni>
99102016f674 ("mptcp: plug subflow context memory leak")  (12 hours ago) <Paolo Abeni>
ae1cd5eb674c ("mptcp: link MPC subflow into msk only after accept")  (12 hours ago) <Paolo Abeni>
afae3cc2da10 ("net: atheros: simplify the return expression of atl2_phy_setup_autoneg_adv()")  (mptcp_net-next/net-next) (18 hours ago) <Zheng Yongjun>

syzkaller reproducer:
```
# {Threaded:false Collide:false Repeat:true RepeatTimes:0 Procs:1 Sandbox:none Fault:false FaultCall:-1 FaultNth:0 Leak:false NetInjection:false NetDevices:true NetReset:false Cgroups:false BinfmtMisc:false CloseFDs:true KCSAN:false DevlinkPCI:false USB:false VhciInjection:false Wifi:false Sysctl:false UseTmpDir:false HandleSegv:false Repro:false Trace:false}
r0 = socket$nl_generic(0x10, 0x3, 0x10)
r1 = syz_genetlink_get_family_id$mptcp(&(0x7f00000000c0)='mptcp_pm\x00')
sendmsg$MPTCP_PM_CMD_ADD_ADDR(r0, &(0x7f00000003c0)={0x0, 0x0, &(0x7f0000000380)={&(0x7f00000002c0)={0x3c, r1, 0x1, 0x0, 0x0, {}, [@MPTCP_PM_ATTR_ADDR={0x28, 0x1, 0x0, 0x1, [@MPTCP_PM_ADDR_ATTR_ADDR6={0x14, 0x4, @private0={0xfc, 0x0, [0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x4]}}, @MPTCP_PM_ADDR_ATTR_FLAGS={0x8, 0x6, 0x5}, @MPTCP_PM_ADDR_ATTR_FAMILY={0x6, 0x1, 0xa}]}]}, 0x3c}}, 0x0)
r2 = socket$inet_mptcp(0x2, 0x1, 0x106)
bind$inet(r2, &(0x7f00000013c0)={0x2, 0x4e20}, 0x10)
listen(r2, 0x0)
r3 = socket$inet_mptcp(0x2, 0x1, 0x106)
connect$inet(r3, &(0x7f00000000c0)={0x2, 0x4e20, @local}, 0x10)
```

CONFIG-file attached.
[CONFIG.txt](https://github.com/multipath-tcp/mptcp_net-next/files/5681357/CONFIG.txt)

[UPDATE 12/11: Updated HEAD and CONFIG file]
[UPDATE 11/19: Updated HEAD and CONFIG file]
[UPDATE 11/02: Added syzkaller reproducer]
[UPDATE 11/02: Updated HEAD]

**Comment by geliangtang** [comment]
@cpaasch @matttbe @pabeni Bugfix for this issue has been sent to ML, named "mptcp: avoid using the main socket to send ack"

**Comment by geliangtang** [comment]
@pabeni @cpaasch @matttbe New patch has been sent out.
