### ISSUE TITLE
[syzkaller] memory leak in skb_ext_add

### ISSUE THREAD

**Issue by cpaasch** [multipath-tcp/mptcp_net-next#109]
```
BUG: memory leak
unreferenced object 0xffff88801bde2e80 (size 40):
  comm "syz-executor.4", pid 24102, jiffies 4295946495 (age 38.650s)
  hex dump (first 32 bytes):
    01 00 00 00 00 01 02 ff 05 00 00 00 00 00 00 00  ................
    00 00 00 00 00 00 00 00 00 21 de 1b 80 88 ff ff  .........!......
  backtrace:
    [<000000004fca31f6>] __skb_ext_alloc+0x19/0x80 net/core/skbuff.c:6172
    [<0000000083fa8328>] skb_ext_add+0x219/0x480 net/core/skbuff.c:6267
    [<00000000f9a336a3>] skb_set_kcov_handle include/linux/skbuff.h:4622 [inline]
    [<00000000f9a336a3>] skb_set_kcov_handle include/linux/skbuff.h:4612 [inline]
    [<00000000f9a336a3>] __alloc_skb+0x45a/0x660 net/core/skbuff.c:253
    [<00000000fd49d44b>] skb_copy+0x13d/0x2f0 net/core/skbuff.c:1512
    [<000000005e11c172>] tcp_send_synack+0x5da/0x1470 net/ipv4/tcp_output.c:3481
    [<00000000adcfad3f>] tcp_rcv_synsent_state_process net/ipv4/tcp_input.c:6229 [inline]
    [<00000000adcfad3f>] tcp_rcv_state_process+0x246b/0x5380 net/ipv4/tcp_input.c:6343
    [<00000000a2db7307>] tcp_v4_do_rcv+0x343/0x8b0 net/ipv4/tcp_ipv4.c:1674
    [<000000004407a6bc>] sk_backlog_rcv include/net/sock.h:1010 [inline]
    [<000000004407a6bc>] __release_sock+0x139/0x3b0 net/core/sock.c:2523
    [<0000000089268134>] release_sock+0x54/0x1b0 net/core/sock.c:3053
    [<000000001929426c>] tcp_sendmsg+0x36/0x40 net/ipv4/tcp.c:1460
    [<0000000040fae80d>] inet6_sendmsg+0xb5/0x140 net/ipv6/af_inet6.c:641
    [<0000000040a5daeb>] sock_sendmsg_nosec net/socket.c:651 [inline]
    [<0000000040a5daeb>] sock_sendmsg net/socket.c:671 [inline]
    [<0000000040a5daeb>] ____sys_sendmsg+0x3c1/0x990 net/socket.c:2353
    [<00000000fcb758dd>] ___sys_sendmsg+0xff/0x170 net/socket.c:2407
    [<000000001185eae3>] __sys_sendmmsg+0x195/0x470 net/socket.c:2497
    [<00000000d5a6e588>] __do_sys_sendmmsg net/socket.c:2526 [inline]
    [<00000000d5a6e588>] __se_sys_sendmmsg net/socket.c:2523 [inline]
    [<00000000d5a6e588>] __x64_sys_sendmmsg+0x99/0x100 net/socket.c:2523
    [<00000000ad0f4319>] do_syscall_64+0x33/0x40 arch/x86/entry/common.c:46
```

No reproducer yet...

HEAD:
2d7e2cfcc130 ("DO-NOT-MERGE: mptcp: enabled by default")  (HEAD, tag: export/20201105T061029, mptcp_net-next/export) (7 days ago) <Matthieu Baerts>
b05f8b3a652b ("DO-NOT-MERGE: mptcp: use kmalloc on kasan build")  (7 days ago) <Paolo Abeni>
10caf376e969 ("mptcp: track window announced to peer")  (7 days ago) <Florian Westphal>
418ca1fe433b ("selftests: mptcp: add ADD_ADDR IPv6 test cases")  (7 days ago) <Geliang Tang>
1eedcb850333 ("mptcp: send out dedicated ADD_ADDR packet")  (7 days ago) <Geliang Tang>
e88e50820922 ("mptcp: change add_addr_signal type")  (7 days ago) <Geliang Tang>
318dfb33afd5 ("mptcp: keep unaccepted MPC subflow into join list")  (7 days ago) <Paolo Abeni>
11643ffeba22 ("selftests: mptcp: add link failure test case")  (7 days ago) <Florian Westphal>
a7bd7ed62509 ("mptcp: skip to next candidate if subflow has unacked data")  (7 days ago) <Florian Westphal>
bb42d1416bf8 ("mptcp: send explicit ack on delayed ack_seq incr")  (7 days ago) <Paolo Abeni>
36c6e9976eae ("mptcp: keep track of advertised windows right edge")  (7 days ago) <Florian Westphal>
e518da8ade94 ("mptcp: rework poll+nospace handling")  (7 days ago) <Florian Westphal>
e81af88302e1 ("mptcp: try to push pending data on snd una updates")  (7 days ago) <Paolo Abeni>
1cd22284eda5 ("mptcp: move page frag allocation in mptcp_sendmsg()")  (7 days ago) <Paolo Abeni>
92fd8af5e25f ("mptcp: refactor shutdown and close")  (7 days ago) <Paolo Abeni>
404eb18a6379 ("mptcp: introduce MPTCP snd_nxt")  (7 days ago) <Paolo Abeni>
8521f48a11fc ("mptcp: add accounting for pending data")  (7 days ago) <Paolo Abeni>
00637a928c4c ("mptcp: reduce the arguments of mptcp_sendmsg_frag")  (7 days ago) <Paolo Abeni>
63f59dabb61e ("mptcp: introduce mptcp_schedule_work")  (7 days ago) <Paolo Abeni>
6f83f9992bc0 ("tcp: factor out __tcp_close() helper")  (7 days ago) <Paolo Abeni>
46e323657c32 ("mptcp: use tcp_build_frag()")  (7 days ago) <Paolo Abeni>
b7cfbf903413 ("tcp: factor out tcp_build_frag()")  (7 days ago) <Paolo Abeni>
74c0724344d8 ("bpf:selftests: add bpf_mptcp_sock() verifier tests")  (7 days ago) <Nicolas Rybowski>
c82968a5ca08 ("bpf:selftests: add MPTCP test base")  (7 days ago) <Nicolas Rybowski>
238fb240869b ("bpf: add 'bpf_mptcp_sock' structure and helper")  (7 days ago) <Nicolas Rybowski>
66e73408b5b2 ("mptcp: attach subflow socket to parent cgroup")  (7 days ago) <Nicolas Rybowski>
2295ca4483a4 ("bpf: expose is_mptcp flag to bpf_tcp_sock")  (7 days ago) <Nicolas Rybowski>
b65ca4c38875 ("Merge git://git.kernel.org/pub/scm/linux/kernel/git/pablo/nf-next")  (mptcp_net-next/net-next) (8 days ago) <Jakub Kicinski>

**Comment by matttbe** [comment]
Should be fixed with the last export branch thanks to Paolo's patches: we no longer have the skb extension cache
https://patchwork.ozlabs.org/project/mptcp/list/?series=215516&archive=both&state=*

**Comment by cpaasch** [comment]
Still happening (updated HEAD above)

**Comment by pabeni** [comment]
I just noted the backtrace looks completely unrelated to MPTCP, can you reproduce it on an non MPTCP-enabled build?

**Comment by cpaasch** [comment]
You are right, looking at the syzkaller log, it is not even calling sendmmsg on an MPTCP-socket.
