### ISSUE TITLE
[syzkaller] WARNING in sk_stream_kill_queues

### ISSUE THREAD

**Issue by cpaasch** [multipath-tcp/mptcp_net-next#115]
```
------------[ cut here ]------------
WARNING: CPU: 0 PID: 17691 at net/core/stream.c:208 sk_stream_kill_queues+0x3fa/0x580 net/core/stream.c:208
Modules linked in:
CPU: 0 PID: 17691 Comm: syz-executor.5 Not tainted 5.10.0-rc6 #52
Hardware name: QEMU Standard PC (i440FX + PIIX, 1996), BIOS rel-1.13.0-0-gf21b5a4aeb02-prebuilt.qemu.org 04/01/2014
RIP: 0010:sk_stream_kill_queues+0x3fa/0x580 net/core/stream.c:208
Code: df 48 c1 ea 03 0f b6 04 02 84 c0 74 04 3c 03 7e 40 8b ab 00 01 00 00 e9 64 ff ff ff e8 bf 3c d7 fe 0f 0b eb 9b e8 b6 3c d7 fe <0f> 0b eb a4 e8 ad 3c d7 fe 0f 0b e9 a9 fe ff ff 4c 89 e7 e8 7e cd
RSP: 0018:ffffc900029a7870 EFLAGS: 00010293
RAX: ffff8880200eaac0 RBX: 0000000000000000 RCX: ffffffff825de78e
RDX: 0000000000000000 RSI: ffffffff825de7ea RDI: 0000000000000005
RBP: 0000000000000c28 R08: ffff8880200eaac0 R09: fffffbfff093e89d
R10: ffffffff849f44e7 R11: fffffbfff093e89c R12: ffff888017df9100
R13: ffffffff849f44e0 R14: ffffc900029a78f0 R15: 1ffff92000534f1a
FS:  0000000000000000(0000) GS:ffff88811b400000(0000) knlGS:0000000000000000
CS:  0010 DS: 0000 ES: 0000 CR0: 0000000080050033
CR2: 000000001ffffe40 CR3: 00000000219b7005 CR4: 0000000000170ef0
Call Trace:
 __mptcp_destroy_sock+0x4e9/0x780 net/mptcp/protocol.c:2562
 mptcp_close+0x57a/0x810 net/mptcp/protocol.c:2611
 inet_release+0xe9/0x1f0 net/ipv4/af_inet.c:434
 inet6_release+0x4c/0x70 net/ipv6/af_inet6.c:478
 __sock_release+0xd2/0x280 net/socket.c:596
 sock_close+0x15/0x20 net/socket.c:1255
 __fput+0x263/0x940 fs/file_table.c:281
 task_work_run+0x102/0x1c0 kernel/task_work.c:151
 exit_task_work include/linux/task_work.h:30 [inline]
 do_exit+0xa21/0x2880 kernel/exit.c:809
 do_group_exit+0x113/0x340 kernel/exit.c:906
 get_signal+0x423/0x1d10 kernel/signal.c:2758
 arch_do_signal+0x88/0x1ad0 arch/x86/kernel/signal.c:811
 exit_to_user_mode_loop kernel/entry/common.c:161 [inline]
 exit_to_user_mode_prepare+0x9b/0xf0 kernel/entry/common.c:191
 irqentry_exit_to_user_mode+0x5/0x20 kernel/entry/common.c:279
 exc_page_fault+0xb0/0x180 arch/x86/mm/fault.c:1488
 asm_exc_page_fault+0x1e/0x30 arch/x86/include/asm/idtentry.h:583
RIP: 0033:0x0
Code: Unable to access opcode bytes at RIP 0xffffffffffffffd6.
RSP: 002b:00000000200003d0 EFLAGS: 00010217
RAX: 0000000000000000 RBX: 000000000069bfe8 RCX: 00007f3dfff33469
RDX: 0000000000000000 RSI: 0000000000000058 RDI: 0000000020007f40
RBP: 000000000069bfe8 R08: 0000000000000000 R09: 0000000000000000
R10: 0000000000000000 R11: 0000000000000246 R12: 000000000069bff4
R13: 00007ffd5838a4af R14: 00000000004154ca R15: 0000000000000003
```

HEAD is:
05cb27b258ba ("DO-NOT-MERGE: mptcp: enabled by default")  (HEAD, tag: export/20201209T060936, mptcp_net-next/export) (12 hours ago) <Matthieu Baerts>
525593cf6729 ("DO-NOT-MERGE: mptcp: add GitHub Actions")  (12 hours ago) <Matthieu Baerts>
6aa8731bf964 ("DO-NOT-MERGE: mptcp: use kmalloc on kasan build")  (12 hours ago) <Paolo Abeni>
2227bfd2f6bd ("mptcp: let MPTCP create max size skbs")  (12 hours ago) <Paolo Abeni>
908c6322325f ("mptcp: pm: simplify select_local_address()")  (12 hours ago) <Paolo Abeni>
a771b76cf445 ("mptcp: parse and act on incoming FASTCLOSE option")  (12 hours ago) <Florian Westphal>
7dbc6b7828a9 ("tcp: parse mptcp options contained in reset packets")  (12 hours ago) <Florian Westphal>
4598a67e2407 ("mptcp: hold mptcp socket before calling tcp_done")  (12 hours ago) <Florian Westphal>
363050070e94 ("mptcp: use MPTCPOPT_HMAC_LEN macro")  (12 hours ago) <Geliang Tang>
905c00c9fd2b ("selftests: mptcp: add the flush addrs testcase")  (12 hours ago) <Geliang Tang>
2d0de9b2d12d ("mptcp: remove address when netlink flushes addrs")  (12 hours ago) <Geliang Tang>
389cb8de6149 ("mptcp: use the variable sk instead of open-coding")  (12 hours ago) <Geliang Tang>
62ad6da7d479 ("mptcp: rename add_addr_signal and mptcp_add_addr_status")  (12 hours ago) <Geliang Tang>
56607a997374 ("mptcp: drop rm_addr_signal flag")  (12 hours ago) <Geliang Tang>
f5614981a113 ("mptcp: print out port and ahmac when receiving ADD_ADDR")  (12 hours ago) <Geliang Tang>
faec918a7bb5 ("mptcp: add port parameter for mptcp_pm_announce_addr")  (12 hours ago) <Geliang Tang>
1bab32fc5774 ("mptcp: send out dedicated packet for ADD_ADDR using port")  (12 hours ago) <Geliang Tang>
a7429bbd1f46 ("mptcp: add the outgoing ADD_ADDR port support")  (12 hours ago) <Geliang Tang>
a8787a82b5a1 ("mptcp: use adding up size to get ADD_ADDR length")  (12 hours ago) <Geliang Tang>
1690597e3a47 ("mptcp: add port support for ADD_ADDR suboption writing")  (12 hours ago) <Geliang Tang>
4021cd88160f ("mptcp: unify ADD_ADDR and ADD_ADDR6 suboptions writing")  (12 hours ago) <Geliang Tang>
0b863095033d ("mptcp: unify ADD_ADDR and echo suboptions writing")  (12 hours ago) <Geliang Tang>
c855f8921120 ("bpf:selftests: add bpf_mptcp_sock() verifier tests")  (12 hours ago) <Nicolas Rybowski>
0eaea54e6080 ("bpf:selftests: add MPTCP test base")  (12 hours ago) <Nicolas Rybowski>
eed59abf1b73 ("bpf: add 'bpf_mptcp_sock' structure and helper")  (12 hours ago) <Nicolas Rybowski>
6dd1da955adf ("mptcp: attach subflow socket to parent cgroup")  (12 hours ago) <Nicolas Rybowski>
58a4d0cfd053 ("bpf: expose is_mptcp flag to bpf_tcp_sock")  (12 hours ago) <Nicolas Rybowski>
d188dfee6155 ("mptcp: be careful on subflows shutdown")  (12 hours ago) <Paolo Abeni>
99102016f674 ("mptcp: plug subflow context memory leak")  (12 hours ago) <Paolo Abeni>
ae1cd5eb674c ("mptcp: link MPC subflow into msk only after accept")  (12 hours ago) <Paolo Abeni>
afae3cc2da10 ("net: atheros: simplify the return expression of atl2_phy_setup_autoneg_adv()")  (mptcp_net-next/net-next) (18 hours ago) <Zheng Yongjun>

Reproducer:
```
# {Threaded:true Collide:true Repeat:true RepeatTimes:0 Procs:1 Sandbox:none Fault:false FaultCall:-1 FaultNth:0 Leak:false NetInjection:false NetDevices:true NetReset:false Cgroups:false BinfmtMisc:false CloseFDs:true KCSAN:false DevlinkPCI:false USB:false VhciInjection:false Wifi:false Sysctl:false UseTmpDir:false HandleSegv:false Repro:false Trace:false}
ioctl$BTRFS_IOC_SET_RECEIVED_SUBVOL(0xffffffffffffffff, 0x89a0, 0x0)
clock_nanosleep(0x2, 0x0, &(0x7f0000000340)={0x0, 0x3938700}, 0x0)
clone3(&(0x7f0000000140)={0x0, 0x0, 0x0, 0x0, {0x12}, &(0x7f00000000c0)=""/80, 0x50, 0x0, 0x0}, 0x58)
gettid()
socket$inet_mptcp(0x2, 0x1, 0x106)
r0 = creat(&(0x7f0000000440)='./file0\x00', 0x0)
write$P9_RFSYNC(r0, &(0x7f0000000000)={0x6}, 0xfffffdef)
```

CONFIG-file attached.
[CONFIG.txt](https://github.com/multipath-tcp/mptcp_net-next/files/5674159/CONFIG.txt)

[UPDATE 12/10: Updated crash-trace, HEAD, reproducer and config-file]
[UPDATE 11/30: Updated crash-trace, HEAD and CONFIG-file]
[UPDATE 11/20: Updated HEAD]

**Comment by cpaasch** [comment]
Closing...

**Comment by cpaasch** [comment]
Nope, actually this still happens...

**Comment by pabeni** [comment]
Just to be sure, this still happenon top of today's Florian squash to
patch, right?


Il ven 20 nov 2020, 20:21 Christoph Paasch <notifications@github.com> ha
scritto:

**Comment by cpaasch** [comment]
Yes, Florian's patch is in this export-branch.

**Comment by matttbe** [comment]
Maybe fixed with https://patchwork.ozlabs.org/project/mptcp/patch/0e80f1282034868082de4b9a76c8f5fde867f840.1606329599.git.pabeni@redhat.com/

**Comment by cpaasch** [comment]
Nope, still happening...

**Comment by dcaratti** [comment]
maybe related: https://lore.kernel.org/netdev/000000000000b4862805b54ef573@google.com/

**Comment by dcaratti** [comment]
@cpaasch , can you give a try with [forward allocation capped to 1M]( https://lore.kernel.org/netdev/3334d00d8b2faecafdfab9aa593efcbf61442756.1608584474.git.dcaratti@redhat.com/ ) ?

**Comment by matttbe** [comment]
Should be fixed thanks to Davide's patch: e7579d5d5b32 ("net: mptcp: cap forward allocation to 1M") in both -net and net-next.

**Comment by cpaasch** [comment]
Yes, can't trigger it anymore.

**Comment by matttbe** [comment]
Great, thank you both!
