### ISSUE TITLE
[syzkaller] WARNING in corrupted

### ISSUE THREAD

**Issue by cpaasch** [multipath-tcp/mptcp_net-next#116]
```
netlink: 'syz-executor.6': attribute type 10 has an invalid length.
------------[ cut here ]------------
------------[ cut here ]------------
WARNING: CPU: 1 PID: 1058 at net/core/stream.c:208 sk_stream_kill_queues+0x3fa/0x580 net/core/stream.c:208
WARNING: CPU: 0 PID: 6793 at net/core/stream.c:208 sk_stream_kill_queues+0x3fa/0x580 net/core/stream.c:208
Modules linked in:
Modules linked in:
CPU: 1 PID: 1058 Comm: kworker/1:3 Not tainted 5.10.0-rc3 #47
CPU: 0 PID: 6793 Comm: kworker/0:4 Not tainted 5.10.0-rc3 #47
Hardware name: QEMU Standard PC (i440FX + PIIX, 1996), BIOS rel-1.13.0-0-gf21b5a4aeb02-prebuilt.qemu.org 04/01/2014
Workqueue: events mptcp_worker
Hardware name: QEMU Standard PC (i440FX + PIIX, 1996), BIOS rel-1.13.0-0-gf21b5a4aeb02-prebuilt.qemu.org 04/01/2014
Workqueue: events mptcp_worker

RIP: 0010:sk_stream_kill_queues+0x3fa/0x580 net/core/stream.c:208

Code: df 48 c1 ea 03 0f b6 04 02 84 c0 74 04 3c 03 7e 40 8b ab 20 02 00 00 e9 64 ff ff ff e8 cf d4 cf fe 0f 0b eb 9b e8 c6 d4 cf fe <0f> 0b eb a4 e8 bd d4 cf fe 0f 0b e9 a9 fe ff ff 4c 89 e7 e8 ae 01
RSP: 0018:ffffc900014bfb20 EFLAGS: 00010293
RIP: 0010:sk_stream_kill_queues+0x3fa/0x580 net/core/stream.c:208

RAX: ffff88810a153100 RBX: 0000000000000000 RCX: ffffffff826a8ede
Code: df 48 c1 ea 03 0f b6 04 02 84 c0 74 04 3c 03 7e 40 8b ab 20 02 00 00 e9 64 ff ff ff e8 cf d4 cf fe 0f 0b eb 9b e8 c6 d4 cf fe <0f> 0b eb a4 e8 bd d4 cf fe 0f 0b e9 a9 fe ff ff 4c 89 e7 e8 ae 01
RSP: 0018:ffffc90004057b20 EFLAGS: 00010293
RDX: 0000000000000000 RSI: ffffffff826a8f3a RDI: 0000000000000005
RBP: 0000000000000a50 R08: ffff88810a153100 R09: fffffbfff0b97c01

R10: ffffffff85cbe007 R11: fffffbfff0b97c00 R12: ffff8881040f0220
R13: ffffffff85cbe000 R14: ffffc900014bfba0 R15: 1ffff92000297f70
RAX: ffff888118374980 RBX: 0000000000000000 RCX: ffffffff826a8ede
FS:  0000000000000000(0000) GS:ffff88811b300000(0000) knlGS:0000000000000000
CS:  0010 DS: 0000 ES: 0000 CR0: 0000000080050033
RDX: 0000000000000000 RSI: ffffffff826a8f3a RDI: 0000000000000005
RBP: 0000000000000a50 R08: ffff888118374980 R09: fffffbfff0b97c01
CR2: 0000562df34df218 CR3: 000000001d1f9002 CR4: 0000000000170ee0
Call Trace:
R10: ffffffff85cbe007 R11: fffffbfff0b97c00 R12: ffff888103d42220
R13: ffffffff85cbe000 R14: ffffc90004057ba0 R15: 1ffff9200080af70
 __mptcp_destroy_sock+0x4e9/0x780 net/mptcp/protocol.c:2487
FS:  0000000000000000(0000) GS:ffff88811b200000(0000) knlGS:0000000000000000
CS:  0010 DS: 0000 ES: 0000 CR0: 0000000080050033
 mptcp_worker+0xb6c/0x1400 net/mptcp/protocol.c:2218
CR2: 0000001b2e341000 CR3: 000000010bf07005 CR4: 0000000000170ef0
Call Trace:
 __mptcp_destroy_sock+0x4e9/0x780 net/mptcp/protocol.c:2487
 process_one_work+0xa2e/0x1680 kernel/workqueue.c:2272
 worker_thread+0x9e/0x1050 kernel/workqueue.c:2418
 mptcp_worker+0xb6c/0x1400 net/mptcp/protocol.c:2218
 kthread+0x34f/0x460 kernel/kthread.c:292
 ret_from_fork+0x22/0x30 arch/x86/entry/entry_64.S:296
```

HEAD is at:
502db67b77b3 ("DO-NOT-MERGE: mptcp: enabled by default")  (HEAD, tag: export/20201119T172519, mptcp_net-next/export) (25 hours ago) <Matthieu Baerts>
b02623a9370e ("DO-NOT-MERGE: mptcp: use kmalloc on kasan build")  (25 hours ago) <Paolo Abeni>
8c15885fe4f2 ("mptcp: use mptcp release_cb for delayed tasks")  (25 hours ago) <Paolo Abeni>
3db94ea13867 ("mptcp: avoid a few atomic ops in the rx path")  (25 hours ago) <Paolo Abeni>
94671cccf29b ("mptcp: allocate TX skbs in msk context")  (25 hours ago) <Paolo Abeni>
221cd6a2755e ("mptcp: protect the rx path with the msk socket spinlock")  (25 hours ago) <Paolo Abeni>
47c818c042d6 ("mptcp: implement wmem reservation")  (25 hours ago) <Paolo Abeni>
91e9b96e7c81 ("mptcp: open code mptcp variant for lock_sock")  (25 hours ago) <Paolo Abeni>
7a9b9e63f7ab ("mptcp: print out port and ahmac when receiving ADD_ADDR")  (25 hours ago) <Geliang Tang>
82ad40b0e57d ("mptcp: add port parameter for mptcp_pm_announce_addr")  (25 hours ago) <Geliang Tang>
9d78e637528c ("mptcp: send out dedicated packet for ADD_ADDR using port")  (25 hours ago) <Geliang Tang>
2a1b88e2dcdf ("mptcp: add the outgoing ADD_ADDR port support")  (25 hours ago) <Geliang Tang>
e9b1511fe28f ("mptcp: use adding up size to get ADD_ADDR length")  (25 hours ago) <Geliang Tang>
5e2fc1e26781 ("mptcp: add port support for ADD_ADDR suboption writing")  (25 hours ago) <Geliang Tang>
2b4071929af0 ("mptcp: unify ADD_ADDR and ADD_ADDR6 suboptions writing")  (25 hours ago) <Geliang Tang>
e2a0778d11a0 ("mptcp: unify ADD_ADDR and echo suboptions writing")  (25 hours ago) <Geliang Tang>
7854ff6bf788 ("mptcp: refine MPTCP-level ack scheduling")  (25 hours ago) <Paolo Abeni>
41d02ec809e1 ("mptcp: track window announced to peer")  (25 hours ago) <Florian Westphal>
744998ba35c1 ("selftests: mptcp: add ADD_ADDR IPv6 test cases")  (25 hours ago) <Geliang Tang>
f1d568449a76 ("mptcp: send out dedicated ADD_ADDR packet")  (25 hours ago) <Geliang Tang>
926556351906 ("mptcp: change add_addr_signal type")  (25 hours ago) <Geliang Tang>
e876b077563d ("mptcp: keep unaccepted MPC subflow into join list")  (25 hours ago) <Paolo Abeni>
3de7576b4f16 ("selftests: mptcp: add link failure test case")  (25 hours ago) <Florian Westphal>
bcbe32f447eb ("mptcp: skip to next candidate if subflow has unacked data")  (25 hours ago) <Florian Westphal>
340c6e13f798 ("bpf:selftests: add bpf_mptcp_sock() verifier tests")  (25 hours ago) <Nicolas Rybowski>
5dde145e0d89 ("bpf:selftests: add MPTCP test base")  (25 hours ago) <Nicolas Rybowski>
c9a9184c6329 ("bpf: add 'bpf_mptcp_sock' structure and helper")  (25 hours ago) <Nicolas Rybowski>
e8e3fe0a18b5 ("mptcp: attach subflow socket to parent cgroup")  (25 hours ago) <Nicolas Rybowski>
5ca0c980fcd0 ("bpf: expose is_mptcp flag to bpf_tcp_sock")  (25 hours ago) <Nicolas Rybowski>
4581679e8b27 ("mptcp: fix state tracking for fallback socket")  (25 hours ago) <Paolo Abeni>
4f384fcfdbdc ("mptcp: drop WORKER_RUNNING status bit")  (25 hours ago) <Paolo Abeni>
c3c899e50077 ("mptcp: update rtx timeout only if required.")  (25 hours ago) <Paolo Abeni>
e76d795ecb5b ("nfc: s3fwrn5: Change the error code")  (mptcp_net-next/net-next) (2 days ago) <Bongsu Jeon>

No reproducer yet.

CONFIG-file attached.
[CONFIG.txt](https://github.com/multipath-tcp/mptcp_net-next/files/5575319/CONFIG.txt)

**Comment by matttbe** [comment]
@cpaasch : thank you for the bug report!
By chance, do you think you could validate latest export branch updated a few minutes ago? :)

**Comment by cpaasch** [comment]
Closing...
