### ISSUE TITLE
Allow user-space to set endpoint ID

### ISSUE THREAD

**Issue by pabeni** [multipath-tcp/mptcp_net-next#117]
Currently the netlink PM APIs do not allow userspace to set the endpoint ID. Any value provided by netlink is overriden by the kernel. This makes the code simple, but makes user-space life hard.

Instead we could:

- use a per netns bitmask (256 bits) to keep track of in-use IDs. Also keep track of the highest ID currently in use
- if the user-space provides an ID at endpoint creation time, try to use it. If already in use, endpoint creation fails
- otherwise pick the first ID available after the highest currently in use, with wrap-around.

That will:
- preserve the current ID allocation schema, while user-space is not providing any ID
- allow the user-space to set the endpoint ID at endpoint creation time
- cope better with active backup scenario where 2 links are going up and down. The wrap-around will allow picking valid endpoint ID avoiding fast re-use

**Comment by geliangtang** [comment]
@pabeni @matttbe Hi Paolo & Matt, Is anyone working on this issue? If not, I can work on it.

**Comment by matttbe** [comment]
Hi Geliang,

As far as I know, nobody is looking at this issue.

Thanks for looking at it!

Cheers,
Matt

**Comment by matttbe** [comment]
Can be closed thanks to these commits from @geliangtang :

- f4b03aa16214: mptcp: add the address ID assignment bitmap
- 6636ac3e5e80: selftests: mptcp: add testcases for setting the address ID
- edac8433efa9: "squashed" in "mptcp: add the address ID assignment bitmap"
