### ISSUE TITLE
[interop] netnext is dropping packets, causing MPTCP-level retransmissions on mptcp.org

### ISSUE THREAD

**Issue by cpaasch** [multipath-tcp/mptcp_net-next#120]
I am running interop tests and one test is an iperf-test (test simple_iperf from https://github.com/multipath-tcp/mptcp-scripts/blob/master/testing/testing.py#L607), which creates two subflows. mptcp.org is the sender, and netnext is the receiver.

I see that netnext ends up dropping data after having acknowledged them at the TCP-layer. This makes the sender require an MPTCP-level retransmission timeout to reinject the missing data. I remember that we got this test-case working at one point, but couldn't find the commit where my test was passing (tried to bisect down to v5.8).

**Comment by pabeni** [comment]
Could you please have a look at/report the MIB counters on the receiver side?

Also, could you please enable the pr_debug() in mptcp_data_queue_ofo() during the test?

echo "func mptcp_data_queue_ofo +fmp" > /sys/kernel/debug/dynamic_debug/control

**Comment by cpaasch** [comment]
Attached are the logs:




[kern.log.zip](https://github.com/multipath-tcp/mptcp_net-next/files/5644165/kern.log.zip)
[ns_comp3_after.txt](https://github.com/multipath-tcp/mptcp_net-next/files/5644167/ns_comp3_after.txt)
