### ISSUE TITLE
[syzkaller] WARNING in corrupted

### ISSUE THREAD

**Issue by cpaasch** [multipath-tcp/mptcp_net-next#127]
```
------------[ cut here ]------------
WARNING: CPU: 1 PID: 10658 at net/core/stream.c:208 sk_stream_kill_queues+0x3fa/0x580 net/core/stream.c:208
FAULT_INJECTION: forcing a failure.
name fail_usercopy, interval 1, probability 0, space 0, times 0
Modules linked in:
CPU: 0 PID: 10662 Comm: syz-executor.4 Not tainted 5.10.0-rc6 #52
CPU: 1 PID: 10658 Comm: syz-executor.1 Not tainted 5.10.0-rc6 #52
Hardware name: QEMU Standard PC (i440FX + PIIX, 1996), BIOS rel-1.13.0-0-gf21b5a4aeb02-prebuilt.qemu.org 04/01/2014
Call Trace:
 __dump_stack lib/dump_stack.c:77 [inline]
 dump_stack+0xbe/0xf9 lib/dump_stack.c:118
 fail_dump lib/fault-inject.c:52 [inline]
 should_fail.cold+0x5/0xa lib/fault-inject.c:146
Hardware name: QEMU Standard PC (i440FX + PIIX, 1996), BIOS rel-1.13.0-0-gf21b5a4aeb02-prebuilt.qemu.org 04/01/2014
 _copy_from_user+0x1b/0xf0 lib/usercopy.c:14
 copy_from_user include/linux/uaccess.h:192 [inline]
 __copy_msghdr_from_user+0x91/0x4b0 net/socket.c:2213
RIP: 0010:sk_stream_kill_queues+0x3fa/0x580 net/core/stream.c:208
Code: df 48 c1 ea 03 0f b6 04 02 84 c0 74 04 3c 03 7e 40 8b ab 00 01 00 00 e9 64 ff ff ff e8 bf 3c d7 fe 0f 0b eb 9b e8 b6 3c d7 fe <0f> 0b eb a4 e8 ad 3c d7 fe 0f 0b e9 a9 fe ff ff 4c 89 e7 e8 7e cd
RSP: 0018:ffffc90013e17c78 EFLAGS: 00010293
 copy_msghdr_from_user+0x8d/0x120 net/socket.c:2264

RAX: ffff88810877c740 RBX: 0000000000000000 RCX: ffffffff825de78e
 recvmsg_copy_msghdr+0x3e/0x80 net/socket.c:2520
 ___sys_recvmsg+0xb1/0x150 net/socket.c:2592
RDX: 0000000000000000 RSI: ffffffff825de7ea RDI: 0000000000000005
RBP: 0000000000000c28 R08: ffff88810877c740 R09: fffffbfff093e89d
R10: ffffffff849f44e7 R11: fffffbfff093e89c R12: ffff88801fa7a100
R13: ffffffff849f44e0 R14: ffffc90013e17cf8 R15: 1ffff920027c2f9b
 do_recvmmsg+0x24c/0x6f0 net/socket.c:2696
FS:  00007f36a5cf2800(0000) GS:ffff88811b500000(0000) knlGS:0000000000000000
CS:  0010 DS: 0000 ES: 0000 CR0: 0000000080050033
 __sys_recvmmsg+0x23e/0x250 net/socket.c:2775
 __do_sys_recvmmsg net/socket.c:2798 [inline]
 __se_sys_recvmmsg net/socket.c:2791 [inline]
 __x64_sys_recvmmsg+0xde/0x130 net/socket.c:2791
 do_syscall_64+0x33/0x40 arch/x86/entry/common.c:46
 entry_SYSCALL_64_after_hwframe+0x44/0xa9
RIP: 0033:0x7f3cd4bd1469
Code: 00 f3 c3 66 2e 0f 1f 84 00 00 00 00 00 0f 1f 40 00 48 89 f8 48 89 f7 48 89 d6 48 89 ca 4d 89 c2 4d 89 c8 4c 8b 4c 24 08 0f 05 <48> 3d 01 f0 ff ff 73 01 c3 48 8b 0d ff 49 2b 00 f7 d8 64 89 01 48
RSP: 002b:00007f3cd52c1dc8 EFLAGS: 00000246 ORIG_RAX: 000000000000012b
RAX: ffffffffffffffda RBX: 000000000069bf40 RCX: 00007f3cd4bd1469
RDX: 0000000000000002 RSI: 0000000020007240 RDI: 0000000000000003
RBP: 00007f3cd52c1e00 R08: 0000000000000000 R09: 0000000000000000
R10: 0000000040000040 R11: 0000000000000246 R12: 000000000069bf4c
R13: 00007ffda59ae6cf R14: 000000000041e89c R15: 0000000000000003
CR2: 000000000044c040 CR3: 000000001c92c004 CR4: 0000000000170ee0
Call Trace:
 __mptcp_destroy_sock+0x4e9/0x780 net/mptcp/protocol.c:2562
 mptcp_close+0x57a/0x810 net/mptcp/protocol.c:2611
 inet_release+0xe9/0x1f0 net/ipv4/af_inet.c:434
 inet6_release+0x4c/0x70 net/ipv6/af_inet6.c:478
 __sock_release+0xd2/0x280 net/socket.c:596
 sock_close+0x15/0x20 net/socket.c:1255
 __fput+0x263/0x940 fs/file_table.c:281
 task_work_run+0x102/0x1c0 kernel/task_work.c:151
 tracehook_notify_resume include/linux/tracehook.h:188 [inline]
 exit_to_user_mode_loop kernel/entry/common.c:164 [inline]
 exit_to_user_mode_prepare+0xee/0xf0 kernel/entry/common.c:191
 syscall_exit_to_user_mode+0x22/0x140 kernel/entry/common.c:266
 entry_SYSCALL_64_after_hwframe+0x44/0xa9
RIP: 0033:0x7f36a58cb28d
Code: c1 20 00 00 75 10 b8 03 00 00 00 0f 05 48 3d 01 f0 ff ff 73 31 c3 48 83 ec 08 e8 ee fb ff ff 48 89 04 24 b8 03 00 00 00 0f 05 <48> 8b 3c 24 48 89 c2 e8 37 fc ff ff 48 89 d0 48 83 c4 08 48 3d 01
RSP: 002b:00007ffde0c8baf0 EFLAGS: 00000293 ORIG_RAX: 0000000000000003
RAX: 0000000000000000 RBX: 0000000000000004 RCX: 00007f36a58cb28d
RDX: 0000000000000000 RSI: 00000000e386920f RDI: 0000000000000003
RBP: 0000000000000001 R08: 00000000e3869213 R09: 0000000000000000
R10: 00007ffde0c8bc10 R11: 0000000000000293 R12: 000000000000012c
R13: 00000000006a0248 R14: 00000000000001f4 R15: 000000000013d85c
```

HEAD:
05cb27b258ba ("DO-NOT-MERGE: mptcp: enabled by default")  (HEAD, tag: export/20201209T060936, mptcp_net-next/export) (12 hours ago) <Matthieu Baerts>
525593cf6729 ("DO-NOT-MERGE: mptcp: add GitHub Actions")  (12 hours ago) <Matthieu Baerts>
6aa8731bf964 ("DO-NOT-MERGE: mptcp: use kmalloc on kasan build")  (12 hours ago) <Paolo Abeni>
2227bfd2f6bd ("mptcp: let MPTCP create max size skbs")  (12 hours ago) <Paolo Abeni>
908c6322325f ("mptcp: pm: simplify select_local_address()")  (12 hours ago) <Paolo Abeni>
a771b76cf445 ("mptcp: parse and act on incoming FASTCLOSE option")  (12 hours ago) <Florian Westphal>
7dbc6b7828a9 ("tcp: parse mptcp options contained in reset packets")  (12 hours ago) <Florian Westphal>
4598a67e2407 ("mptcp: hold mptcp socket before calling tcp_done")  (12 hours ago) <Florian Westphal>
363050070e94 ("mptcp: use MPTCPOPT_HMAC_LEN macro")  (12 hours ago) <Geliang Tang>
905c00c9fd2b ("selftests: mptcp: add the flush addrs testcase")  (12 hours ago) <Geliang Tang>
2d0de9b2d12d ("mptcp: remove address when netlink flushes addrs")  (12 hours ago) <Geliang Tang>
389cb8de6149 ("mptcp: use the variable sk instead of open-coding")  (12 hours ago) <Geliang Tang>
62ad6da7d479 ("mptcp: rename add_addr_signal and mptcp_add_addr_status")  (12 hours ago) <Geliang Tang>
56607a997374 ("mptcp: drop rm_addr_signal flag")  (12 hours ago) <Geliang Tang>
f5614981a113 ("mptcp: print out port and ahmac when receiving ADD_ADDR")  (12 hours ago) <Geliang Tang>
faec918a7bb5 ("mptcp: add port parameter for mptcp_pm_announce_addr")  (12 hours ago) <Geliang Tang>
1bab32fc5774 ("mptcp: send out dedicated packet for ADD_ADDR using port")  (12 hours ago) <Geliang Tang>
a7429bbd1f46 ("mptcp: add the outgoing ADD_ADDR port support")  (12 hours ago) <Geliang Tang>
a8787a82b5a1 ("mptcp: use adding up size to get ADD_ADDR length")  (12 hours ago) <Geliang Tang>
1690597e3a47 ("mptcp: add port support for ADD_ADDR suboption writing")  (12 hours ago) <Geliang Tang>
4021cd88160f ("mptcp: unify ADD_ADDR and ADD_ADDR6 suboptions writing")  (12 hours ago) <Geliang Tang>
0b863095033d ("mptcp: unify ADD_ADDR and echo suboptions writing")  (12 hours ago) <Geliang Tang>
c855f8921120 ("bpf:selftests: add bpf_mptcp_sock() verifier tests")  (12 hours ago) <Nicolas Rybowski>
0eaea54e6080 ("bpf:selftests: add MPTCP test base")  (12 hours ago) <Nicolas Rybowski>
eed59abf1b73 ("bpf: add 'bpf_mptcp_sock' structure and helper")  (12 hours ago) <Nicolas Rybowski>
6dd1da955adf ("mptcp: attach subflow socket to parent cgroup")  (12 hours ago) <Nicolas Rybowski>
58a4d0cfd053 ("bpf: expose is_mptcp flag to bpf_tcp_sock")  (12 hours ago) <Nicolas Rybowski>
d188dfee6155 ("mptcp: be careful on subflows shutdown")  (12 hours ago) <Paolo Abeni>
99102016f674 ("mptcp: plug subflow context memory leak")  (12 hours ago) <Paolo Abeni>
ae1cd5eb674c ("mptcp: link MPC subflow into msk only after accept")  (12 hours ago) <Paolo Abeni>
afae3cc2da10 ("net: atheros: simplify the return expression of atl2_phy_setup_autoneg_adv()")  (mptcp_net-next/net-next) (18 hours ago) <Zheng Yongjun>

No reproducer.

CONFIG-file:
[CONFIG.txt](https://github.com/multipath-tcp/mptcp_net-next/files/5674175/CONFIG.txt)

[Update 12/15: Updated crash-trace]

**Comment by pabeni** [comment]
@cpaasch  the backtrace does not match the issue subject ?!? The reported backtrace looks like issues/115, which should be addressed by the pending patch "mptcp: fix pending data accounting"

**Comment by cpaasch** [comment]
Oups... :-) Fixed that!

**Comment by cpaasch** [comment]
Sorry... I'm lacking coffee...

**Comment by cpaasch** [comment]
Seems like each of these traces in "corrupted" have sk_stream_kill_queues... It's probably indeed a dupe of #115

**Comment by cpaasch** [comment]
Closing as it is a dupe.
