### ISSUE TITLE
replace some/most pr_debug with trace events

### ISSUE THREAD

**Issue by pabeni** [multipath-tcp/mptcp_net-next#131]
the debug messages are useful in debug sessions, but have several downside:
- they requires debug build
- turning the debug messages on slow down the system a lot, likely impacting the to-be-debugged races/scenarios
- it's difficult to handle the amount of data produced by not-so-short runs
We can improve the situation replacing some debug messages with trace events.

Why trace event at all? we could use perf-probe instead.
- probes can't be attached in any place
- not all the local variables are available for perf probes.

Note: the to-be-defined trace event should be considered carefully - it's better is that interface is as stable as possible.

**Comment by geliangtang** [comment]
@pabeni Hi Paolo, I'll add the trace events for MPTCP recently.

**Comment by geliangtang** [comment]
As Paolo suggested, we should add the tracepoints at "the packet scheduler and the mapping status" first.

In get_mapping_status, the tracepoint should be enough to get the full mapping info, in case of no error
and the complete error reason elsewhere.

In mptcp_subflow_get_send, the tracepoint should be enough to understand the packet scheduler decision.

**Comment by matttbe** [comment]
Can be closed thanks to these new commits from Geliang:

- 00ed6f03febe: mptcp: export mptcp_subflow_active
- e4421bbffd09: mptcp: add tracepoint in mptcp_subflow_get_send
- 12abe4c31032: mptcp: add tracepoint in get_mapping_status
- 88a550c12ce4: mptcp: add tracepoint in ack_update_msk
- 769badb3d5a3: mptcp: add tracepoint in subflow_check_data_avail
- Results: e245e136bb73..f574fcfd3f60

(one patch is still pending but we will continue to track it on Patchwork)
