### ISSUE TITLE
[syzkaller] WARNING in __mptcp_destroy_sock

### ISSUE THREAD

**Issue by cpaasch** [multipath-tcp/mptcp_net-next#135]
```
------------[ cut here ]------------
WARNING: CPU: 1 PID: 22151 at net/mptcp/protocol.c:2545 __mptcp_destroy_sock+0x553/0x6c0 net/mptcp/protocol.c:2545
Modules linked in:
CPU: 1 PID: 22151 Comm: kworker/1:1 Not tainted 5.11.0-rc2 #59
Hardware name: QEMU Standard PC (i440FX + PIIX, 1996), BIOS rel-1.13.0-0-gf21b5a4aeb02-prebuilt.qemu.org 04/01/2014
Workqueue: events mptcp_worker
RIP: 0010:__mptcp_destroy_sock+0x553/0x6c0 net/mptcp/protocol.c:2545
Code: 5f c3 e8 50 85 82 fe 48 89 ef e8 f8 b2 ab ff eb b7 e8 41 85 82 fe be 03 00 00 00 4c 89 e7 e8 b4 0a 08 ff eb a3 e8 2d 85 82 fe <0f> 0b e9 f0 fe ff ff e8 21 85 82 fe 0f 0b e9 28 ff ff ff e8 15 31
RSP: 0018:ffffc90000f0fc10 EFLAGS: 00010293
RAX: 0000000000000000 RBX: 0000000000000300 RCX: 0000000000000000
RDX: ffff88801ea0d880 RSI: ffffffff82b36943 RDI: 0000000000000003
RBP: ffff88803995c000 R08: 0000000000000000 R09: 0000000000000003
R10: ffffffff82b36832 R11: 0000000000000001 R12: ffffc90000f0fc48
R13: dffffc0000000000 R14: ffffc90000f0fc48 R15: 1ffff920001e1f85
FS:  0000000000000000(0000) GS:ffff88811b300000(0000) knlGS:0000000000000000
CS:  0010 DS: 0000 ES: 0000 CR0: 0000000080050033
CR2: 00007f37e8ae0ef8 CR3: 00000001080bf004 CR4: 0000000000170ee0
Call Trace:
 mptcp_worker+0x7dd/0x1610 net/mptcp/protocol.c:2272
 process_one_work+0x896/0x1170 kernel/workqueue.c:2275
 worker_thread+0x605/0x1350 kernel/workqueue.c:2421
 kthread+0x344/0x410 kernel/kthread.c:292
 ret_from_fork+0x22/0x30 arch/x86/entry/entry_64.S:296
```

HEAD:
0ba8e381319a ("mptcp: fix locking in mptcp_disconnect()")  (HEAD) (3 hours ago) <Paolo Abeni>
2231a14a0d42 ("DO-NOT-MERGE: mptcp: enabled by default")  (tag: export/20210114T060000, mptcp_net-next/export) (13 hours ago) <Matthieu Baerts>
bdb95de71fe6 ("DO-NOT-MERGE: mptcp: add GitHub Actions")  (13 hours ago) <Matthieu Baerts>
37e13d6e5600 ("DO-NOT-MERGE: mptcp: use kmalloc on kasan build")  (13 hours ago) <Paolo Abeni>
89c6174b783e ("mptcp: schedule work for better snd subflow selection")  (13 hours ago) <Paolo Abeni>
e61bdd4536e3 ("mptcp: do not queue excessive data on subflows")  (13 hours ago) <Paolo Abeni>
22a5014b0c10 ("mptcp: re-enable sndbuf autotune")  (13 hours ago) <Paolo Abeni>
5ec4e3d81ae3 ("mptcp: always graft subflow socket to parent")  (13 hours ago) <Paolo Abeni>
c7a8b478d036 ("bpf:selftests: add bpf_mptcp_sock() verifier tests")  (13 hours ago) <Nicolas Rybowski>
4aad7af6b076 ("bpf:selftests: add MPTCP test base")  (13 hours ago) <Nicolas Rybowski>
71880f981f7f ("bpf: add 'bpf_mptcp_sock' structure and helper")  (13 hours ago) <Nicolas Rybowski>
197e7ab42147 ("bpf: expose is_mptcp flag to bpf_tcp_sock")  (13 hours ago) <Nicolas Rybowski>
127854a8dd50 ("linux: handle MPTCP consistently with TCP")  (13 hours ago) <Paolo Abeni>
fe5b34dc31e8 ("mptcp: better msk-level shutdown.")  (13 hours ago) <Paolo Abeni>
cdca68586d28 ("mptcp: more strict state checking for acks")  (13 hours ago) <Paolo Abeni>
0ae5b43d6dde ("tcp: assign skb hash after tcp_event_data_sent")  (mptcp_net-next/net-next) (15 hours ago) <Yuchung Cheng>

No reproducer

CONFIG-file:
[CONFIG.txt](https://github.com/multipath-tcp/mptcp_net-next/files/5816454/CONFIG.txt)

**Comment by pabeni** [comment]
this looks like a dup of #136: same calltrace and warning triggered by the same [bad] status (leaked forward memory, likely due to leaked or corrupted rmem_released)

**Comment by cpaasch** [comment]
Yep, dupe.
