### ISSUE TITLE
RM_ADDR: remove a list of addresses

### ISSUE THREAD

**Issue by geliangtang** [multipath-tcp/mptcp_net-next#140]
In RFC 8684 3.4.2, REMOVE_ADDR option can remove not only a previously added address, but also a list of addresses:
 
```
                     1                   2                   3
 0 1 2 3 4 5 6 7 8 9 0 1 2 3 4 5 6 7 8 9 0 1 2 3 4 5 6 7 8 9 0 1
+---------------+---------------+-------+-------+---------------+
|     Kind      |Length = 3 + n |Subtype|(resvd)|   Address ID  | ...
+---------------+---------------+-------+-------+---------------+
                           (followed by n-1 Address IDs, if required)
```

In our implementation, only one single address is supported, removing a list of addresses need to be implemented.

**Comment by matttbe** [comment]
Thank you @geliangtang for your work!

This is now in our tree!

- 1c96937632b9: mptcp: add rm_list in mptcp_out_options
- 3fdf49c516da: mptcp: add rm_list_tx in mptcp_pm_data
- 7aee779e6946: mptcp: add rm_list in mptcp_options_received
- 3edb9adea339: mptcp: add rm_list_rx in mptcp_pm_data
- 6eed48ec95a3: mptcp: remove multi addresses in PM
- b2144a3313f8: mptcp: remove multi subflows in PM
- 125ef24bb692: mptcp: remove multi addresses and subflows in PM
- bb2f562e7c86: mptcp: remove a list of addrs when flushing
- 0a0186b2d7b2: selftests: mptcp: add invert argument for chk_rm_nr
- 12f49b51c3de: selftests: mptcp: set addr id for removing testcases
- 9373d5c3f215: selftests: mptcp: add testcases for removing addrs
- Results: 312a753c50d7..d5fb4935cee8

Before closing this ticket, do you plan to add the similar support in packetdrill to ease the validations and bug reproductions?

Cheers,
Matt

**Comment by geliangtang** [comment]
@matttbe @dcaratti I think we should add RM_ADDR support in packetdrill. If you have time to add this, I'd appreciate it.

**Comment by dcaratti** [comment]
hi Geliang,

> @matttbe @dcaratti I think we should add RM_ADDR support in packetdrill. If you have time to add this, I'd appreciate it.

I'm about to add a couple of tests, covering single `RM_ADDR` with / without 'port' and multiple `RM_ADDR`. Stay tuned :-)

**Comment by geliangtang** [comment]
TODO: rm_addr with id 0

Here's the comments about rm_addr with id 0:

---

> Have you tested what happens if there's an incoming rm_addr with id 0, since we never send an ADD_ADDR for the initial subflow?

Id 0 is still not supported in this removing address version, since we only use this code to shutdown and close the subsocket in mptcp_pm_nl_rm_addr_received/mptcp_pm_nl_rm_subflow_received:

    mptcp_subflow_shutdown(sk, ssk, how);
    mptcp_close_ssk(sk, ssk, subflow);

It's problematic to use them to shutdown and close the initial subflow.

I think we need to use something like:

    mptcp_shutdown(sk, how);
    mptcp_close(sk, timeout);

to deal with the initial subflow, but it doesn't work too. It will take me some time to solve it.

---

**Comment by mjmartineau** [comment]
Running the mp_join.sh tests with the series applied from http://patchwork.ozlabs.org/project/mptcp/list/?series=230623 I don't see the initial subflow being closed early:

[mp_join-08-ns1-0-K3U2Yl.pcap.gz](https://github.com/multipath-tcp/mptcp_net-next/files/6053468/mp_join-08-ns1-0-K3U2Yl.pcap.gz)

If I filter using `tcp.options.mptcp.subtype == 4` to find the RM_ADDRs, the second RM_ADDR is sent to 10.0.1.1 at frame 110. Two subflows are closed right after that, but the initial subflow between 10.0.1.2 and 10.0.1.1 remains active until DATA_FIN is exchanged at the end of the test. So it appears that nothing is happening to remove subflow 0?

Note: I had to edit mp_join.sh to set `capture = 1` at the beginning, the `-c` flag isn't working for capture right now - didn't notice the duplicate flag name when I approved the mp_join.sh refactor

**Comment by matttbe** [comment]
We can now close this ticket thanks to the last patches from @geliangtang and reviewed by @mjmartineau :

- efa9a9885fe7: mptcp: remove all subflows involving id 0 address
- e753cdf39596: mptcp: unify RM_ADDR and RM_SUBFLOW receiving
- 01a0acddf9ee: mptcp: remove id 0 address
- 1cfe9d6a9351: selftests: mptcp: add addr argument for del_addr
- 52221e28e3ef: selftests: mptcp: remove id 0 address testcases
- Results: 31d85a0e0974..b6772f0348c6
