### ISSUE TITLE
packetdrill: support injecting ADD_ADDR echo bit

### ISSUE THREAD

**Issue by matttbe** [multipath-tcp/mptcp_net-next#142]
Packetdrill currently segfaults with this line:

```
+0 < . 1:1(0) ack 1 win 257 <add_address addr[saddr],dss dack8=1 ssn=1 dll=0 nocs>
```

While parsing one is OK.
To respect the RFC, the receiver should ACK the ADD_ADDR by re-sending it without the hmac but an echo bit set.

**Comment by dcaratti** [comment]
> Packetdrill currently segfaults with this line:
> 
> ```
> +0 < . 1:1(0) ack 1 win 257 <add_address addr[saddr],dss dack8=1 ssn=1 dll=0 nocs>
> ```
> 
> While parsing one is OK.
> To respect the RFC, the receiver should ACK the ADD_ADDR by re-sending it without the hmac but an echo bit set.

the support for echo bit is in there; anyway the segfault happens because address id is unassigned, and the inbound parser tries to "guess"  it from the IP address contained in the "echoed" ADD_ADDR:
```
1955                 if((s8)add_addr_script->data.add_addr.address_id == UNDEFINED){
1956                         struct mp_address *addr;
1957                         for(addr = mp_state.packetdrill_addrs; addr; addr = addr->next)
1958                                 if(is_equal_ip(&addr->ip, &endpoint->ip))
1959                                         break;
1960                         add_addr_live->data.add_addr.address_id = addr->addr_id;
                                                    addr is NULL here :)  ^^^
1961                 }
```

**Comment by matttbe** [comment]
Can be closed thanks to @dcaratti 's modifications there: https://github.com/multipath-tcp/packetdrill/pull/46
