### ISSUE TITLE
Packetdrill: ADD_ADDR for v6 only socket should only contain v6 addresses

### ISSUE THREAD

**Issue by matttbe** [multipath-tcp/mptcp_net-next#143]
For the moment, some scripts in fastclose and mp_join folders are not launched in v6 only because the names are suffixed with `v4`. So only v4 and v4mapped tests are launched.

But these tests don't pass in v6 because the script tries to send a v4 address in the ADD_ADDR message while the socket is in v6 only so we should only have v6 addresses there.

**Comment by matttbe** [comment]
In https://github.com/multipath-tcp/packetdrill/commit/8057e7e48395bfd2f075bd876e9ab6db38e17dfb , we have to be in v4 only because of this issue. We don't want to close this one.

**Comment by dcaratti** [comment]
server scripts still need to be differentiated between `v4` and `v6`, because outbound ADD_ADDR without port numbers still carry the DSS option, so it's not possible to match them in a generic packetdrill script. Other test cases should pass after fixing the kernel in order to [harmonize outbound addr_echo](https://lore.kernel.org/mptcp/aeb4b7f3044e2f869ae026f950eb70c4398dad63.1616761454.git.dcaratti@redhat.com/).

**Comment by matttbe** [comment]
> Other test cases should pass after fixing the kernel in order to [harmonize outbound addr_echo](https://lore.kernel.org/mptcp/aeb4b7f3044e2f869ae026f950eb70c4398dad63.1616761454.git.dcaratti@redhat.com/).

Thanks for that!

> server scripts still need to be differentiated between `v4` and `v6`, because outbound ADD_ADDR without port numbers still carry the DSS option, so it's not possible to match them in a generic packetdrill script. 

It makes sense to have a `_v4` and a `_v6` even if they are almost the same. We have to follow the protocol (due to TCP Options restrictions). :)
Are you looking at adding these v6 server tests? :)

**Comment by matttbe** [comment]
From our weekly meeting:

      - For the moment, we need two different scripts for the server part because in v4, DSS is included in the ADD_ADDR, not in v6
      - Davide is looking at the possibility to have MP_JOIN without having to send ADD_ADDR
      - → we could then have dedicated tests just for ADD_ADDR (one for v4, one for v6)
      - → other tests would be unified, without ADD_ADDR → and also shorter!
