### ISSUE TITLE
reduce mptcp_out_option struct size

### ISSUE THREAD

**Issue by pabeni** [multipath-tcp/mptcp_net-next#15]
the tcp_out_option struct is allocated on the stack memset()-ed by tcp_make_synack() and __tcp_transmit_skb().

The 'TCP' part of it is 24 bytes, the MPTCP options account for 120 bytes.

Since we control MPTCP option creation/insertion and we do not allow simult MPC,MPJ or DSS we could put most MPTCP fields under an union.

Additionally option writing could be cleaned-up a bit avoiding several conditionals - no need to check for anything else after MPC or MPJ

**Comment by matttbe** [comment]
Can be closed thanks to @pabeni 's series:
- 9030cfa001f6: "squashed" (with conflicts) in "mptcp: move drop_other_suboptions check under pm lock"
- ef6b13c8bbad: mptcp: optimize out option generation
- 7547285ef776: mptcp: shrink mptcp_out_options struct
