### ISSUE TITLE
Only 1 ADD_ADDR has been sent when signalling multi invalid addresses

### ISSUE THREAD

**Issue by geliangtang** [multipath-tcp/mptcp_net-next#151]
Here is the test case for signalling multi invalid addresses:

         # signal invalid addresses
         reset
         ip netns exec $ns1 ./pm_nl_ctl limits 3 3
         ip netns exec $ns1 ./pm_nl_ctl add 10.0.12.1 flags signal
         ip netns exec $ns1 ./pm_nl_ctl add 10.0.13.1 flags signal
         ip netns exec $ns1 ./pm_nl_ctl add 10.0.14.1 flags signal
         ip netns exec $ns2 ./pm_nl_ctl limits 3 3
         run_tests $ns1 $ns2 10.0.1.1
         chk_join_nr "signal invalid addresses" 0 0 0
         chk_add_nr 1 1

It added three invalid addresses, but only got 1 ADD_ADDR and 1 ECHO.

mptcp_pm_create_subflow_or_signal_addr was only triggered once when the msk is established. Since the first address is an
invalid one, the subflow for it cannot be created successfully. So mptcp_pm_nl_subflow_established could not be invoked. The last two addresses didn't have a chance to be announced.

**Comment by geliangtang** [comment]
@pabeni  Here is Paolo's suggestions for this issue:

---

I think the "correct" behaviour would be announcing 3 addresses. Setting and maintaining correct list of addresses is up to the user-space/path-manger.

The kernel could teorerically watch out for local IP address changes, but even announcing only IPs that are locally available would not guarantee the related subflow to be established - for a gazillion of reasons, last but not least the address could be removed by the admin after being announced and before subflow creation.

Overall I think the kernel should not filter the addresses to be announced in any way.

Eventually we could change how add_addr events are scheduled, e.g. moving to the next address after that the previous one has been echoed by the peer.

As I said I think it's not an huge priority, we have plenty of bugs to fix first ;) So I would just keep the current result, possibly adding a TODO/FIXME note in the test and/or in the relevant kernel code.

---

**Comment by geliangtang** [comment]
Mat's comment:

---

Before we close #151, what happens if the peer does not send echoes or echoes are lost? Should there be another patch to also call mptcp_pm_create_subflow_or_signal_addr when an ADD_ADDR has been retransmitted the maximum number of times?

---

**Comment by matttbe** [comment]
Should be closed thanks to patches from Geliang:

- 4877b4409cd8: mptcp: export lookup_anno_list_by_saddr
- 57e57640c326: mptcp: move to next addr when subflow creation fail
- 608768e00068: selftests: mptcp: signal addresses testcases
- d63677a633cf: mptcp: drop argument port from mptcp_pm_announce_addr
- c7ef42ed2451: mptcp: skip connecting the connected address
- a681ac4046d5: conflict in t/mptcp-add-rm_list_tx-in-mptcp_pm_data
- 1d7d152ed66f: mptcp: move to next addr when timeout
- 9f635adaa8c3: selftests: mptcp: add cfg_do_w for cfg_remove
- da596d8d5312: selftests: mptcp: timeout testcases for multi addresses
- Results: de59595c18b3..8a82f6b7cf01
