### ISSUE TITLE
iproute2: change backup mode (MP_PRIO) for active connections

### ISSUE THREAD

**Issue by matttbe** [multipath-tcp/mptcp_net-next#158]
Issue #51 added `MP_PRIO` support but this support cannot be validated with the current version of iproute2.

With iproute2, you can interact with MPTCP PM to add and remove addresses with different properties. But you cannot change these properties for active addresses. The idea would be to support `ip mptcp endpoint change ADDRESS backup [on/off]` or similar.

Once this support is added, emitting MP_PRIO can be validated with packetdrill.

- [x] iproute2: support a `change` mode
- [ ] packetdrill validation

**Comment by dcaratti** [comment]
> Issue #51 added `MP_PRIO` support but this support cannot be validated with the current version of iproute2.
> 
> With iproute2, you can interact with MPTCP PM to add and remove addresses with different properties. But you cannot change these properties for active addresses. The idea would be to support `ip mptcp endpoint change ADDRESS backup [on/off]` or similar.
> 
> Once this support is added, emitting MP_PRIO can be validated with packetdrill.
> 
> * [x]  iproute2: support a `change` mode
> * [ ]  packetdrill validation

@matttbe, I see that the current kernel is expecting address family + address (and optionally port number) for selecting which subflows should send the MP_PRIO, instead of 'id'. Is there a reason behind this? (if not, I can try to write a small patch for Linux that changes this)

**Comment by matttbe** [comment]
As discussed at the last meeting:

> Is there a reason behind this?

Probably we didn't think about adding support for the ID, we certainly focus on testing this with `pm_nl` where we already had the IP + port and we only implemented that.

But consistency is important, so yes please add support for that in the Linux kernel :)

**Comment by matttbe** [comment]
kernel and iproute2 patches have been sent upstream
