### ISSUE TITLE
allow ss dumping msk socket in TCP_LISTEN status

### ISSUE THREAD

**Issue by pabeni** [multipath-tcp/mptcp_net-next#163]
currently we see only sockets with a valid token, which is created at connect() or at syn reception time. LISTEN sockets are just unobservable with 'ss'

**Comment by matttbe** [comment]
These patches from Florian closes this issue:

New patches for t/upstream:
- 0432b1c61654: mptcp: diag: switch to context structure
- ba9e26b62530: mptcp: remove locking in mptcp_diag_fill_info
- b433728093dd: mptcp: listen diag dump support
- a9cc2c58bf79: selftests/mptcp: add diag listen tests
- Results: ccc95f7c14d9..3b82e3d7eed2 (export)
