### ISSUE TITLE
allow non 'backup' subflows creation

### ISSUE THREAD

**Issue by pabeni** [multipath-tcp/mptcp_net-next#17]
the PM allows setting/controlling the backup flag in the newly created subflows, but we set it unconditionally in the MPJ handshake.

Let MPJ handshake value be really controlled by the PM, so that we can establish non backup subflow.

The above should/will enable sending data on multiple subflow simult and will likely need some/many fixes to the RX and TX path - notably we may want to pick a different subflow if/when the peer closes the window for the current one.

**Comment by matttbe** [comment]
Patches are in the export branch, e.g. 808f42dcee6226132584787298305102ca19a230
