### ISSUE TITLE
allow 'force to MPTCP' mode: sysctl

### ISSUE THREAD

**Issue by pabeni** [multipath-tcp/mptcp_net-next#18]
we need a system/per netns switch to allow forcing existing, unmodified, application to create by default MPTCP sockets instead of TCP one.

A current, naive, approach is via syscall hijacking:

https://github.com/pabeni/mptcp-tools/tree/master/use_mptcp

possible alternatives could be via systemtap, eBPF (do we have a suitable eBPF hook?) or per netns sysctl.

**Comment by mjmartineau** [comment]
We don't have a suitable eBPF hook yet. We've discussed adding BPF_CGROUP_SOCKET to allow per-cgroup override of proto in the socket() call.

**Comment by matttbe** [comment]
Another way to do that, here with systemtap, from @dcaratti :

```c
#! /usr/bin/env stap

%{
#include <linux/in.h>
#include <linux/ip.h>
%}

/* according to [1], RSI contains 'type' and RDX
 * contains 'protocol'.
 * [1] https://github.com/torvalds/linux/blob/master/arch/x86/entry/entry_64.S#L79
 */

function mptcpify () %{
    if (CONTEXT->kregs->si == SOCK_STREAM &&
        (CONTEXT->kregs->dx == IPPROTO_TCP ||
         CONTEXT->kregs->dx == 0)) {
                CONTEXT->kregs->dx = IPPROTO_MPTCP;
                STAP_RETVALUE = 1;
    } else {
         STAP_RETVALUE = 0;
    }
%}

probe kernel.function("__sys_socket") {
        if (mptcpify() == 1) {
                printf("command %16s mptcpified\n", execname());
        }
}
```

**Comment by ericcurtin** [comment]
This is what I get when I try this on my linux system @matttbe 

```
curtine@G5-5587:~/git$ uname -a
Linux G5-5587 5.8.5-050805-generic #202008270831 SMP Thu Aug 27 08:33:39 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
curtine@G5-5587:~/git$ sudo stap -vg mpctp.stap
Pass 1: parsed user script and 476 library scripts using 115492virt/90800res/7356shr/83308data kb, in 160usr/20sys/183real ms.
semantic error: while resolving probe point: identifier 'kernel' at mpctp.stap:24:7
        source: probe kernel.function("__sys_socket") {
                      ^

semantic error: missing x86_64 kernel/module debuginfo [man warning::debuginfo] under '/lib/modules/5.8.5-050805-generic/build'

Pass 2: analyzed script: 0 probes, 0 functions, 1 embed, 0 globals using 117340virt/93232res/7980shr/85156data kb, in 50usr/60sys/115real ms.
Pass 2: analysis failed.  [man error::pass2]
Tip: /usr/share/doc/systemtap/README.Debian should help you get started.
```

Any ideas?

**Comment by dcaratti** [comment]
On Mon, 2020-08-31 at 11:17 -0700, Eric Curtin wrote:
> This is what I get when I try this on my linux system @matttbe
> 
> curtine@G5-5587:~/git$ uname -a
> Linux G5-5587 5.8.5-050805-generic #202008270831 SMP Thu Aug 27 08:33:39 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
> curtine@G5-5587:~/git$ sudo stap -vg mpctp.stap
> Pass 1: parsed user script and 476 library scripts using 115492virt/90800res/7356shr/83308data kb, in 160usr/20sys/183real ms.
> semantic error: while resolving probe point: identifier 'kernel' at mpctp.stap:24:7
>         source: probe kernel.function("__sys_socket") {                      ^

hello,

> semantic error: missing x86_64 kernel/module debuginfo [man warning::debuginfo] under '/lib/modules/5.8.5-050805-generic/build'

mptcp.stap builds a kernel probe and attachs to __sys_socket() to change
IPPROTO_TCP into IPPROTO_MPTCP. In your case, I see that stap fails
finding the debug information for the kernel executable. On Fedora, it's
fixed installing kernel-debuginfo- stuff. On Ubuntu, I think you need to
do this:

$ sudo apt-get install linux-image-$(uname -r)-dbgsym

(more instructions at https://wiki.ubuntu.com/Kernel/Systemtap)

thanks!
-- 
davide

**Comment by matttbe** [comment]
From Paolo:

> I propose to close issues/18 as wontfix, since we have simple tool (mptcpize) available in an established software (mptcpd) for that

Indeed, it is probably enough and I'm not sure net maintainers will be OK for us modifying the socket syscall (or maybe?).
Anyway if someone thinks it is needed, feel free to comment here.

Thank you for looking at these old tickets.
