### ISSUE TITLE
implement data_fin ack retransmission for subflow in  TIME_WAIT state

### ISSUE THREAD

**Issue by pabeni** [multipath-tcp/mptcp_net-next#181]
if the subflows land in timewait status, e.g. receive and ack a DATA_FIN after having their closed their own xmit side, and the data fin ack is lost, that last packet is never retransmitted, as the TIME_WAIT tcp socket does not include MPTCP options when they generate replies.

We need to provide mptcp extensions for timewait sockets (as we did for tcp_request_sock) and keep adding DATA_FIN ack in there if/as needed.

Additionally it would be nice pktdrills for the above scenario

**Comment by matttbe** [comment]
@pabeni Thank you for adding this ticket!
To you, is it more a bug or a new feature? :)

**Comment by fw-strlen** [comment]
One solution would be to prevent the transition of the subflow socket to the timewait state (i.e. the tw_sock mini-state) if there is an outstanding data_fin ack. I'll send a test case and RFC patch to the ML shortly.

**Comment by matttbe** [comment]
As discussed at the last meeting, there is no issue here, we can close it
