### ISSUE TITLE
Sending data over multiple subflow Kernel  - 5.10.0-051000-generic

### ISSUE THREAD

**Issue by VenkateswaranJ** [multipath-tcp/mptcp_net-next#184]
I'm trying to send data over multiple subflow as mentioned in this [changelog](https://github.com/multipath-tcp/mptcp_net-next/wiki).

![mptcp_fallback_version1](https://user-images.githubusercontent.com/45777176/116008324-3d200f00-a614-11eb-8922-029cd2aef0b8.png)

**Server and Client OS**: Ubuntu 20.04 (kernel - 5.10.0-051000-generic) with mptcp enabled.
**Router OS**: Ubuntu 20.04 (Kernel 5.8 - generic) mptcp not enabled.

I have done source routing on both client and server and also set some iptable rule on the router to separate both links.
so 10.100.66.2 only able to talks to 10.100.64.2 and same for another link.

**Test Steps:**
1. Set **add_addr_accepted** and **subflow** to 2 on both server and client.
2. Created **signal** endpoint at server for the second interface (i.e 10.100.130.2).

**Expected Result:**
Create two subflow, each per link. Data should be scheduled on both link and if one subflow fails the data has to be carried over via another subflow.

**Problem:**

I can only able to create a master subflow on the first link.

 This [iproute2](https://man7.org/linux/man-pages/man8/ip-mptcp.8.html) command only gives the possibility to set source address on all three different connection type (signal, subflow, backup) and the ip command assumes destination address as the master subflow destination address. Because of this, I have the below problems.

- **signal**: 
![mptcp_signal](https://user-images.githubusercontent.com/45777176/116010095-4b265d80-a61d-11eb-9343-5106a8101b09.png)

- **subflow**: If I change the endpoint type from signal to subflow again I have the same kind of problem.
![subflow](https://user-images.githubusercontent.com/45777176/116010160-ac4e3100-a61d-11eb-97ce-9c5327ea57fd.png)

- **backup**: If I change the endpoint to backup then nothing happened.

**1. Is there any way to achieve two subflow on the above setup with the iproute2 command?**
**2. it's not possible to add/remove subflow in the middle of client-server communication using the ip command, isn't it?**

Please let me know if you need any other info.

**Comment by matttbe** [comment]
Hi,

Which IPRoute2 commands did you run exactly?

In theory, you need to:
- increase the limits (OK)
- add a new `endpoint` on the server side to `signal` an IP (10.100.130.2)
- add a new `endpoint` on the client side to create a new `subflow` using the second IP (10.100.128.2)
- add routing rules to make sure the traffic from one IP is using the correct interface (`ip rule from ... table ...` + `ip route add default via ... table ...`).
- you can also add rules not to allow some subflows, e.g. from one IP to another one using `ip route ... unreachable/prohibit ...`

The kernel will "simply" follow the routing policies that are in place.

**Comment by VenkateswaranJ** [comment]
> add a new endpoint on the server side to signal an IP (10.100.130.2)

ip mptcp endpoint add 10.100.130.2 dev enp0s8 signal

> add a new endpoint on the client side to create a new subflow using the second IP (10.100.128.2)

ip mptcp endpoint add 10.100.128.2 dev enp0s8 subflow

> add routing rules to make sure the traffic from one IP is using the correct interface (ip rule from ... table ... + ip route add default via ... table ...).

I just followed this https://multipath-tcp.org/pmwiki.php/Users/ConfigureRouting and verified that source routing is working via ping.

> you can also add rules not to allow some subflows, e.g. from one IP to another one using ip route ... unreachable/prohibit ...

server:
`ip route del unreachable 10.100.128.2 from 10.100.66.2 table 1` // link 1
`ip route del unreachable 10.100.64.2 from 10.100.130.2 table 2` // link 2

client:
`ip route add unreachable 10.100.130.2 from 10.100.64.2 table 1`
`ip route add unreachable 10.100.66.2 from 10.100.128.2 table 2`

After configuring this **unreachable** on both sides, now the client not even trying **Join connection** to the server for the second subflow. Because according to this command on the client-side `ip mptcp endpoint add 10.100.128.2 dev enp0s8 subflow` **I'm telling mptcp to create the second subflow from source address 10.100.128.2  but what's the destination IP it will try?** As far as I tested **it'll try for destination IP of master subflow** (which is 10.100.66.2), but since I make that path unreachable it silently drops the second subflow creation.

**Is it possible to create a subflow from the specific source address to a specific destination address via Netlink API?**

**Comment by matttbe** [comment]
> I'm telling mptcp to create the second subflow from source address 10.100.128.2 but what's the destination IP it will try?

The client should try to create a subflow:
- from all allowed IPs: initial one + flagged as `subflow` with `ip mptcp` command
- to all known IP of the server: initial one + all the one that have been signalled via ADD_ADDR sent by the server

Note that I think older releases stop creating new subflows if one has failed. Please check if you have this fix: 557963c383e8209b14de91bf2a0301a41b94d8c4

But best is probably to validate this setup with our `export` branch.

> Is it possible to create a subflow from the specific source address to a specific destination address via Netlink API?

No. Not yet: `MPTCP_CMD_SUB_CREATE` has not been implemented yet.

**Comment by VenkateswaranJ** [comment]
> Note that I think older releases stop creating new subflows if one has failed. Please check if you have this fix: 557963c
> 
> But best is probably to validate this setup with our export branch.

@matttbe  Do you mean to patch the export branch with my kernel manually? Does **[kernel 5.10.32](https://www.kernel.org/)** (Release date 2021-04-21) has this patch ?

> No. Not yet: MPTCP_CMD_SUB_CREATE has not been implemented yet.

Thanks for the info, **is it available in out-of-tree implementation?**

**Comment by matttbe** [comment]
> Does kernel 5.10.32 (Release date 2021-04-21) has this patch ?

I guess it doesn't contain this patch.
Would it be possible to compile the kernel using our export branch?

But if you don't have errors to create subflows (maybe the `ip route unreachable` would cause one, not sure), the kernel should try to create the different connections.
I don't know if we have debug message when we fail to create a new connection. But traces commands can still be used.

> Thanks for the info, is it available in out-of-tree implementation?

Yes it is. You need to listen for events and get the token of an MPTCP connection. From there, you can use this command to create a new subflow per connection.

**Comment by VenkateswaranJ** [comment]
> I guess it doesn't contain this patch.
> Would it be possible to compile the kernel using our export branch?

I tried to compile the export branch but unfortunately, I couldn't make it. Will that patch available in kernel release 5.12?

**Comment by matttbe** [comment]
I'm not sure, this might be considered as a change behaviour (more subflows would be created)
But again, that's only if you have errors creating subflows.

**Comment by VenkateswaranJ** [comment]
Where can I see those errors ? In dmesg ? Should I need to enable any debug flag for that ?

**Comment by matttbe** [comment]
I think there should be debug lines but you need to enable it (e.g. via dynamic debug)

  echo "file net/mptcp/* +fmp" > /sys/kernel/debug/dynamic_debug/control

I think there were other important modifications later like supporting IPv4 mapped in IPv6.

**Comment by VenkateswaranJ** [comment]
I tried with kernel 5.10.0 but there is no luck (it still tries for the master flow destination IP).

@matttbe  Can you give me a hint on **which MPTCP implementation (or RFC version) is used by most of the mobile devices and data centres? are they using upstream kernel implementation ( RFC 8684)?**
 
You can close this question with the answer to my above question.

**Comment by matttbe** [comment]
All major deployments I know are using the out of tree implementation. Simply because these projects have been started way before the beginning of this MPTCP Upstream project and switching implementation is a big move. New projects should use the latest kernel.

I'm pretty sure that there is no mobile devices with MPTCP upstream so far because it is too recent. I guess phones released recently are still using a kernel <= 4.19. This year we will start seeing mobile devices with a kernel 5.4 but we have time before seeing ones with a kernel 5.10 which is the first LTS version with MPTCP support.

Please note that the out of tree implementation also implements the RFC8684 in the dev version. No stable release so far with this support.

Apple devices are certainly all implementing the RFC6824 for the moment.

MPTCPv1 (RFC8684) is deprecating MPTCPv0 (RFC6824). Existing projects are looking at switching to MPTCPv1 but it might take time.

One last thing, 5G specs includes MPTCP (ATSSS) but only the one defined with the RFC8684.
