### ISSUE TITLE
kernel warning when processes exit with unaccepted connections in the backlog

### ISSUE THREAD

**Issue by matttbe** [multipath-tcp/mptcp_net-next#185]
@geliangtang noticed in #176  that when running the BPF selftests, this message is printed in kernel logs:

    Attempt to release TCP socket in state 8

@darkwrat noticed that it is not related to BPF only:

> I've noticed `Attempt to release TCP socket in state 8` errors appear when a process exits, that had unaccepted connections in backlog. Here is a simple reproducer.

```c
#include <netinet/in.h>

int main(void)
{
	struct sockaddr_in sa;
	sa.sin_family = AF_INET;
	sa.sin_port = htons(12345);
	sa.sin_addr.s_addr = htonl(INADDR_LOOPBACK);

	int lfd = socket(AF_INET, SOCK_STREAM, IPPROTO_MPTCP);
	bind(lfd, (struct sockaddr *)&sa, sizeof(sa));
	listen(lfd, 100);

	for (int i = 0; i < 10; i++) {
		int sock = socket(AF_INET, SOCK_STREAM, IPPROTO_MPTCP);
		connect(sock, (struct sockaddr *)&sa, sizeof(sa));
	}
}
```

> I have not loaded any BPF programs. And I have tried changing protocol to IPPROTO_TCP for both client and server sockets, one at a time. `Attempt to release TCP socket in state 8` is only observable when both of them are IPPROTO_MPTCP,  on 5.11.13-200.fc33.x86_64 and also on mptcp_net-next kernel from 0ef01ab.

**Comment by fw-strlen** [comment]
Probably due to "mptcp: create msk early". The unaccepted tcp connections reference an msk that isn't exposed to userspace.
Should be easily fixable by some minor annotation via flag in mptcp_sock structure.

**Comment by fw-strlen** [comment]
As Paolo pointed out, this bug was added with the DATA_FIN state machine.  If a DATA_FIN is sent, socket transitions from ESTABLISHED to CLOSE_WAIT, which in turn causes the code supposed to deal with the cloned msk socket to get skipped.
Patch has been sent, it adjusts the test in mptcp_sock_destruct to cover CLOSE_WAIT as well:

```
-       if (sk->sk_state == TCP_ESTABLISHED) {
+       if ((1 << sk->sk_state) & (TCPF_ESTABLISHED | TCPF_CLOSE_WAIT)) {
```
