### ISSUE TITLE
add recvmsg support for ancillary data

### ISSUE THREAD

**Issue by fw-strlen** [multipath-tcp/mptcp_net-next#187]
Add support for cmsg(3) to mptcps receive path so we can support SO_TIMESTAMP(NS) option and possibly introduce mptcp-specific notifications in the future.

**Comment by matttbe** [comment]
@fw-strlen if I'm not mistaken, this issue can be closed thanks to your patches:

- 480085ab2b4f: sock: expose so_timestamp options for mptcp
- 1dec92e1a886: sock: expose so_timestamping options for mptcp
- 1939fa553ab4: mptcp: sockopt: propagate timestamp request to subflows
- b31cc28dde50: mptcp: setsockopt: handle SOL_SOCKET in one place only
- e353d974b686: tcp: export timestamp helpers for mptcp
- b1555bde4528: mptcp: receive path cmsg support
- 7a134f51c2c2: selftests: mptcp_connect: add SO_TIMESTAMPNS cmsg support
- Results: 36f31371c969..36a7db06660a

Which are already in net-next:

  - [net-next,1/7] sock: expose so_timestamp options for mptcp
    https://git.kernel.org/netdev/net-next/c/371087aa476a
  - [net-next,2/7] sock: expose so_timestamping options for mptcp
    https://git.kernel.org/netdev/net-next/c/ced122d90f52
  - [net-next,3/7] mptcp: sockopt: propagate timestamp request to subflows
    https://git.kernel.org/netdev/net-next/c/9061f24bf82e
  - [net-next,4/7] mptcp: setsockopt: handle SOL_SOCKET in one place only
    https://git.kernel.org/netdev/net-next/c/7a009a70ff8a
  - [net-next,5/7] tcp: export timestamp helpers for mptcp
    https://git.kernel.org/netdev/net-next/c/892bfd3ded0e
  - [net-next,6/7] mptcp: receive path cmsg support
    https://git.kernel.org/netdev/net-next/c/b7f653b297a4
  - [net-next,7/7] selftests: mptcp_connect: add SO_TIMESTAMPNS cmsg support
    https://git.kernel.org/netdev/net-next/c/5e6af0a729b6

Is it correct or is there still something missing? :)

Also, does it make sense to support the send part? If yes, it is probably best to create a new issue.

**Comment by fw-strlen** [comment]
Agree, we can open new issues if needed, initial cmsg support was added by those commits, thus closing.
