### ISSUE TITLE
Wireshark / TCPDump doesn't understand option subtype 8 (MP_TCPRST)

### ISSUE THREAD

**Issue by matttbe** [multipath-tcp/mptcp_net-next#189]
Linked to #53 : we need to adapt these tools for `MP_TCPRST`

- [x] Wireshark support
- [x] TCPDump support

**Comment by dcaratti** [comment]
I can have a look at this, while re-validating the MP_RESET packetdrill tests (see #143)

**Comment by dcaratti** [comment]
> Linked to #53 : we need to adapt these tools for `MP_TCPRST`
> 
> * [ ]  Wireshark support

https://gitlab.com/wireshark/wireshark/-/merge_requests/2995

**Comment by matttbe** [comment]
Everything has been merged!
- https://github.com/the-tcpdump-group/tcpdump/pull/918
- https://gitlab.com/wireshark/wireshark/-/merge_requests/2995

Thanks!
