### ISSUE TITLE
Wireshark doesn't understand MP_CAPABLE C flag

### ISSUE THREAD

**Issue by mjmartineau** [multipath-tcp/mptcp_net-next#190]
The RFC 8684 C flag is still interpreted as a reserved flag bit in Wireshark 3.4.4, needs to be updated for "don't join on initial subflow addr/port" C flag.

- [ ] Wireshark support
- [ ] TCPDump support

**Comment by RuiCunhaM** [comment]
Hi!
So I noticed this issue when doing some tests, and I was about to submit a fix for Wireshark, but I'm in doubt about the best designation for the flag. From the RFC I was going with "No more Subflows", but reading this issue and the

> "don't join on initial subflow addr/port"

part I am no longer sure what is the most intuitive designation.
Ideas in which one is the best?

**Comment by matttbe** [comment]
Hi @RuiCunhaM 

Thank you for looking at that.

> From the RFC I was going with "No more Subflows", but reading this issue (...) I am no longer sure what is the most intuitive designation.

Good point, indeed this option is not clear. When a host set this flag in the MP_CAPABLE option, it means "_do NOT send an additional subflow request to this source IP and port_":

> The third bit, labeled "C", is set to 1 to indicate that the sender of this option will not accept additional MPTCP subflows to the source address and port, and therefore the receiver MUST NOT try to open any additional subflows toward this address and port.

I don't know how many words we can have here but it is not easy to only use a few words while still having a clear explanation :)
Maybe: _No more subflows on initial addr/port_ if it is not too long!
If you have any other suggestions, feel free to share ;-)

**Comment by RuiCunhaM** [comment]
Hi @matttbe, thanks for answering.

To be honest in Wireshark there is a decent amount of room to work with, so I believe your suggestion fits perfectly. I definitely agree that saying "initial addr/port" it's important to reflect what is stated in the RFC.

In TCPDump however, now that I also looked at it, they seem to be a bit more conservative, so it will be a bit more difficult to fully describe the flag.

**Comment by matttbe** [comment]
> To be honest in Wireshark there is a decent amount of room to work with, so I believe your suggestion fits perfectly. I definitely agree that saying "initial addr/port" it's important to reflect what is stated in the RFC.

Great, let's try this then!

> In TCPDump however, now that I also looked at it, they seem to be a bit more conservative, so it will be a bit more difficult to fully describe the flag.

Yes, I was thinking about that too. We might have to mention a very few words I guess,  something like `C flag` or just `C`.

**Comment by RuiCunhaM** [comment]
> Great, let's try this then!

https://gitlab.com/wireshark/wireshark/-/merge_requests/3890

> something like `C flag` or just `C`

Probably, I don't think we can get a way with much more than that.

**Comment by matttbe** [comment]
Thanks!

I hope you don't mind if I assign this task to you not to have someone else working on it (even if I hope people read comments before starting implementing something ;-) )

**Comment by RuiCunhaM** [comment]
> I hope you don't mind if I assign this task to you not to have someone else working on it (even if I hope people read comments before starting implementing something ;-) )

Haha no problem at all

**Comment by RuiCunhaM** [comment]
Everything has been merged:

TCPDump: https://github.com/the-tcpdump-group/tcpdump/pull/934

Wireshark: https://gitlab.com/wireshark/wireshark/-/merge_requests/3890

I think this can be closed.

**Comment by matttbe** [comment]
Great, thank you, it looks good!

Do not hesitate if you see any missing features or issues ;-)
