### ISSUE TITLE
Fullmesh path manager support

### ISSUE THREAD

**Issue by geliangtang** [multipath-tcp/mptcp_net-next#193]
Implement the in-kernel fullmesh path manager like on the mptcp.org kernel.

**Comment by matttbe** [comment]
@geliangtang: did you already look how far we are from a fullmesh one when using the current in-kernel PM with Netlink support?
By chance, do you have a list of what is missing?

**Comment by geliangtang** [comment]
@matttbe: Hi Matt, the fullmesh path manager patches are nearly ready. I'll send out the first version next week.

**Comment by matttbe** [comment]
Can be closed thanks to Geliang's patches:

- 8235745392a1: mptcp: drop flags and ifindex arguments
- 31e4fdaf9c0b: mptcp: remote addresses fullmesh
- 6ad65bd12896: mptcp: local addresses fullmesh
- 3faae7f56182: selftests: mptcp: set and print the fullmesh flag
- ee6f6d4a5b48: selftests: mptcp: add fullmesh testcases
- 68e72848611e: selftests: mptcp: delete uncontinuous removing ids
- Results: d5c73e4f859d..dcbca66e0658
- 22876224b527: "squashed" in "mptcp: drop flags and ifindex arguments"
- Results: dcbca66e0658..b1d5eb590503
