### ISSUE TITLE
Round-robin packet scheduler support

### ISSUE THREAD

**Issue by geliangtang** [multipath-tcp/mptcp_net-next#194]
Implement the round-robin packet scheduler like on the mptcp.org kernel.

**Comment by cpaasch** [comment]
Just wondering: What is the use-case for the round-robin scheduler? As far as I can see, the round-robin scheduler has probably the worst possible performance in about any metric.

**Comment by geliangtang** [comment]
No use-case for the round-robin scheduler. I just want to port some other schedulers from the mptcp.org kernel, and the round-robin is the simplest one, so I chose it to implement first. It has the worst performance indeed, let's use it for testing only.

**Comment by matttbe** [comment]
Hi Geliang,

Thank you for having created the ticket!

It might be good to discuss about the architecture for that prior any implementations. I think it would be good to extend / change the behaviour with BPF. We could have the RR packet scheduler as an example.

**Comment by matttbe** [comment]
At a previous meeting, we decided to close this ticket. A Round-Robin packet scheduler has no real use-case. The only benefit is that it is easy to check everything is working as expected.

In other words, it can be useful to implement a RR scheduler in BPF (#75) to demonstrate it works. Probably best to close this ticket to avoid confusions.
