### ISSUE TITLE
reduce hooking in TCP code

### ISSUE THREAD

**Issue by pabeni** [multipath-tcp/mptcp_net-next#2]
the mptcp_rcv_synsent() hook can be dropped moving the related code in subflow_finish_connect()

**Comment by matttbe** [comment]
Note: can be closed when this series is applied: https://patchwork.ozlabs.org/project/mptcp/list/?series=173810&state=%2A&archive=both

**Comment by matttbe** [comment]
> Note: can be closed when this series is applied: https://patchwork.ozlabs.org/project/mptcp/list/?series=173810&state=%2A&archive=both

This series has been applied, we can close this issue.

**Comment by matttbe** [comment]
not sure why Github is saying this issue is still opened...
