### ISSUE TITLE
fallback rx path is broken

### ISSUE THREAD

**Issue by pabeni** [multipath-tcp/mptcp_net-next#200]
ok, it's almost as drastic as it sounds:

In fallback mode, tcp_rcv_established() we hit the fastpath/header prediction. Incoming data is usually enqueued via direct call to tcp_queue_rcv() and the mptcp_incoming_options() hook in tcp_data_queue() is usually not reached.

As a result, we could end-up delaying the writer wake-up or even stalling it completely.

That is somewhat perceivable even with self-tests: sometimes fallback self-tests are considerably slower than non fallback one.

Possible solutions:

- explicitly disable tcp header prediction for fallback socket, e.g. setting a 0 'tp->tcp_header_len'
- add more mptcp hooks in tcp()
- ??? both the above are ugly!!!

**Comment by mjmartineau** [comment]
If the maintainers won't accept one more `unlikely()` branch on the fast path (hey, md5 gets a call in `tcp_v4_rcv()`), I don't know what option we have other than turning off header prediction. Can anything be plugged in elsewhere on the rx path that could nudge the MPTCP code?
