### ISSUE TITLE
Checksum interop problem with mptcp_trunk

### ISSUE THREAD

**Issue by mjmartineau** [multipath-tcp/mptcp_net-next#205]
I did some tests with connections with checksums enabled, between the export branch and the multipath-tcp.org mptcp_trunk branch (v1 mode).

----
When the multipath-tcp.org kernel was listening, the connection would always fall back to TCP when the first data was sent by the upstream kernel. The multipath-tcp.org kernel was the first to fall back and stop sending MPTCP headers.

Wireshark doesn't complain about the MPTCP checksum value, and the MPTCP option parses cleanly.

Fallback appears to have more to do with mptcp_trunk's handling for MP_CAPABLE + data. I turned on debug output on the mptcp_trunk side and saw:

`mptcp_prevalidate_skb: mptcp_prevalidate_skb 0xc20cfa4 will fallback - pi 1 from tcp_data_queue+0x444/0x600, seq 2884338481 mptcp-flags 0x0`

This might be the problem in mptcp_trunk's mptcp.h:

```
#define MPTCPV1_SUB_LEN_CAPABLE_DATA            22
#define MPTCPV1_SUB_LEN_CAPABLE_DATA_CSUM       22   // <---- should be 24
```

----
When the upstream kernel was listening, the multipath-tcp.org kernel would send corrupt TCP options with the first data packet (the first time a DSS option was sent). The upstream kernel would then send TCP RST.

The MPTCP option (MP_CAPABLE+data) is not of the correct length to contain a checksum, and the bytes after the MPTCP option are getting interpreted by Wireshark as a separate (broken) option. That broken option looks like random bytes: invalid option number and way-too-large option length. The above definition of MPTCPV1_SUB_LEN_CAPABLE_DATA_CSUM looks suspicious for this too.

----

The test program I used happens to cause both kernels to send MP_CAPABLE+data packets.

These results were the same when only one side of the connection had checksums enabled, or if both kernels did.

----

Adapted from email conversation with @pabeni (https://lore.kernel.org/mptcp/aedffae2-61ad-eb44-c083-e674f736fd96@linux.intel.com/t/#u)

PCAP attached, showing both the bad option and the fallback cases.
[checksum-interop.pcapng.gz](https://github.com/multipath-tcp/mptcp_net-next/files/6651962/checksum-interop.pcapng.gz)

**Comment by pabeni** [comment]
@mjmartineau: this looks a mptcp.org bug???

**Comment by mjmartineau** [comment]
@pabeni: Yes, I think so. Just wanted to get something recorded to share the pcap while figuring out the details of the problem.

**Comment by mjmartineau** [comment]
I think it's better to track this in multipath-tcp/mptcp#427, I'll add more information there.
