### ISSUE TITLE
MPTCP-level retransmission strategy is probably too aggressive.

### ISSUE THREAD

**Issue by pabeni** [multipath-tcp/mptcp_net-next#206]
in #196 Maxim reported several stats acquired in MPTCP transparent proxy deployment.

The number of MPTCP-level retransmission looks patologically high:

MPTcpExtMPTCPRetrans            249559             0.0
[...]
MPTcpExtOFOQueueTail            275929             0.0
MPTcpExtOFOQueue                283950             0.0
MPTcpExtOFOMerge                262221             0.0

because is comparable to the number of incoming OoO DSM

Maxim also reported the the links in use have very different latency.

I suppose the current MPTCP-level RTX timeout is too aggressive in such scenario: we could end-up using the low-latency RTT as a baseline data xmitted over the high-latency link.

**Comment by matttbe** [comment]
Can be closed thanks to Paolo's patches from last week:

12375127  [v2,mptcp-next,8/8] selftests: mptcp: add testcase for active-back 
12375125  [v2,mptcp-next,7/8] mptcp: backup flag from incoming MPJ ack option 
12375121  [v2,mptcp-next,6/8] mptcp: add mibs for stale subflows processing 
12375123  [v2,mptcp-next,5/8] mptcp: faster active backup recovery 
12375119  [v2,mptcp-next,4/8] mptcp: cleanup sysctl data and helpers 
12375117  [v2,mptcp-next,3/8] mptcp: handle pending data on closed subflow 
12375115  [v2,mptcp-next,2/8] mptcp: less aggressive retransmission stragegy 
12375113  [v2,mptcp-next,1/8] mptcp: more accurate timeout
