### ISSUE TITLE
Quicker use of backup subflows

### ISSUE THREAD

**Issue by matttbe** [multipath-tcp/mptcp_net-next#209]
The RFC mentions that backup subflows should be used only if there is no other non backup subflows.

As discussed at the last meeting, the path manager could decide to close subflows if they are considered as defunct. (#207 is then required)

Another way is to mark subflows as defunct and let the packets scheduler to use backup subflow if needed.

We could imagine marking a subflow as defunct if no packets are acked within X ms. Or if the CC is in "lost state"

**Comment by matttbe** [comment]
> the path manager could decide to close subflows if they are considered as defunct. (#207 is then required)

It looks like this should be done by the link layer, not the transport one: it could be transient.

**Comment by matttbe** [comment]
@pabeni no objection for me to close this ticket? :)

**Comment by pabeni** [comment]
implemented by:

ff5a0b421cb2 mptcp: faster active backup recovery
