### ISSUE TITLE
sort-out {set,get}sockopt handling

### ISSUE THREAD

**Issue by pabeni** [multipath-tcp/mptcp_net-next#21]
{set,get}sockopt should be usable even for non-fallback socket.

A possible implementation can be:

sort all possible setsockopt (SOCKET, IP, TCP level) values in different sets:

* options applied (set) to all subflows and read (get) from the first one
  (e.g. most/all??? IP level options)

* options applied/read only to the first subflow 
  (???TCP_INFO, SO_BINDTODEVICE???)

* options available only for fallback socket (or only when a single sub-flow is available)
  (???TCP_INFO, SO_BINDTODEVICE???,  TCP_CC_INFO, TCP_REPAIR*)

[possibly get rid of one of the last 2 sets]

Add an MPTCP_SUBFLOW_NR getsockopt to fetch the current number of subflows and a MPTCP_SUBFLOW {get/set}sockopt to get/set on the specified subflow the specified option,

**Comment by pabeni** [comment]
We will likely also need some additional hooking in net/socket.c:__sys_setsockopt() or net/core/sock.c:sock_setsockopt() to handle properly SOL_SOCKET setsockopt - currently msk is modified, but no change is reflected on the subflow[s]

**Comment by matttbe** [comment]
@pabeni: is this issue related to what Florian did?

**Comment by pabeni** [comment]
> @pabeni: is this issue related to what Florian did?

yes, if Florian agrees, I think we can close it

**Comment by matttbe** [comment]
We can create new issues for the points raised by Florian. Let's close this one.
