### ISSUE TITLE
Accept new subflows when the listening socket is closed or bind to one IP?

### ISSUE THREAD

**Issue by matttbe** [multipath-tcp/mptcp_net-next#210]
For the moment, we don't accept new subflows even if the PM is configured to accept more except if the connection is done to a new endpoint with port (inconsistency?)

Note that (only few?) apps close the listening socket to accept only one connection. Maybe it is an exception?

Also some apps bind on one specific IP: then it is not OK to establish subflows to another endpoint. Maybe a wrong configuration?

Allowing these subflows might not be easy or hacky, e.g. not really closing subflows / restrict the bind to one IP/dev to accept new subflows.

At least we should document the current behaviour.

**Comment by matttbe** [comment]
Also, it can be interesting to document how to dimension the SYN backlog size if this is taken into consideration for new subflows (SYN+MP_JOIN)

**Comment by kmaloor** [comment]
@matttbe  Don't the userspace PM changes address this issue?

**Comment by matttbe** [comment]
@kmaloor : thanks for the message!

I think we could even have closed it before as it is very similar to #203 (and not very well described :) ).
