### ISSUE TITLE
support for setsockopt(SOL_IP)

### ISSUE THREAD

**Issue by dcaratti** [multipath-tcp/mptcp_net-next#220]
add kernel support for `setsockopt(SOL_IP)`, since `mptcp_supported_sockopt()` [returns](https://elixir.bootlin.com/linux/v5.14-rc3/source/net/mptcp/sockopt.c#L409) `true` but then nobody [handles](https://elixir.bootlin.com/linux/v5.14-rc3/source/net/mptcp/sockopt.c#L612) `SOL_IP` in `mptcp_setsockopt()`.

implement support for IP_TOS and assess  the correct behavior using packetdrill

**Comment by dcaratti** [comment]
@spoorva is working on this

**Comment by matttbe** [comment]
@spoorva : please assign yourself on this ticket once you joined mptcp-upstream-devs team.

**Comment by spoorva** [comment]
Adding the packetdrill test for the above here - 

    --tolerance_usecs=100000
    `../common/defaults.sh`
     
    +0    `../common/client.sh`
     
    +0.0    socket(..., SOCK_STREAM, IPPROTO_MPTCP) = 7                          
    +0.0    setsockopt(7, SOL_IP, IP_TOS, [4], 4) = 0                        
    //+0.200  getsockopt(7, SOL_IP, IP_TOS, [4], [4]) = 0  
     
    +0.0  fcntl(7, F_GETFL) = 0x2 (flags O_RDWR)
    +0.0  fcntl(7, F_SETFL, O_RDWR|O_NONBLOCK) = 0
     
    +0.0  connect(7, ..., ...) = -1  EINPROGRESS (Operation now in progress)
     
     
     
    +0.0    > [tos 0x04]    addr[caddr0] > addr[saddr0]  S   0:0(0)                        <mss 1460, sackOK, TS val 4074410674 ecr 0,          nop, wscale 8, mpcapable v1 flags[flag_h] nokey>
     
    +0.0    <                                            S.  0:0(0)      ack 1  win 65535  <mss 1460, sackOK, TS val 4074410674 ecr 4074410674, nop, wscale 8, mpcapable v1 flags[flag_h] key[skey=2]>
     
    +0.0    > [tos 0x04]                                 .  1:1(0)      ack 1             <nop, nop,         TS val 4074410674 ecr 4074410674,                mpcapable v1 flags[flag_h] key[ckey, skey]>
     
    //+0.2  getsockopt(7, SOL_IP, IP_TOS, [4], [4]) = 0
    +0.0  fcntl(7, F_SETFL, O_RDWR) = 0   // set back to blocking
     
     +0.2    setsockopt(7, SOL_IP, IP_TOS, [4], 4) = 0
     
    +1.0  write(7, ..., 2) = 2
    +0.0    >  [tos 0x04]                             P.  1:3(2)      ack 1             <nop, nop, TS val 4074418292 ecr 4074410674,                        mpcapable v1 flags[flag_h] key[ckey, skey] mpcdatalen 2, nop, nop>
    +0.0    <                                          .  1:1(0)      ack 3  win 256    <nop, nop, TS val 4074418293 ecr 4074418292,       add_address addr[saddr1] hmac=auto>
     
     +0.2    setsockopt(7, SOL_IP, IP_TOS, [4], 4) = 0
     
     
    +0.0    >  [tos 0x04]               > addr[saddr1]  S   0:0(0)                        <mss 1460, sackOK, TS val 448955294 ecr 0,         nop, wscale 8, mp_join_syn     address_id=0 token=sha256_32(skey)>
    +0.0    >  [tos 0x04]               > addr[saddr0]   .  3:3(0)      ack 1             <nop, nop,         TS val 448955294 ecr 448955294, add_address addr[saddr1] addr_echo>
    +0.0    <                                           S.  0:0(0)      ack 1  win 65535  <mss 1460, sackOK, TS val 448955294 ecr 448955294, nop, wscale 8, mp_join_syn_ack address_id=1 sender_hmac=auto>
    +0.0    >  [tos 0x04]                                .  1:1(0)      ack 1             <nop, nop,         TS val 448955294 ecr 448955294,                mp_join_ack                  sender_hmac=auto>
     
    //+0.0    setsockopt(7, SOL_IP, IP_TOS, [4], 4) = 0
     
     
    +0.1  close(7) = 0
     
    +0.0    >   addr[caddr0] > addr[saddr0]   .  3:3(0)      ack 1    win 256         <nop, nop, TS val 4074418292 ecr 4074418293,dss dack4=1 dsn8=3 ssn=0 dll=1  nocs fin, nop, nop>
     
    +0.0    >                                 .  1:1(0)      ack 1  win 256         <nop, nop, TS val 4074418292 ecr 4074418293,dss dack4=1 dsn8=3 ssn=0 dll=1  nocs fin, nop, nop>

**Comment by matttbe** [comment]
FYI, the CI found some issues with the last patch you sent:
- https://cirrus-ci.com/task/5316374168862720
- https://cirrus-ci.com/task/6442274075705344

**Comment by spoorva** [comment]
> FYI, the CI found some issues with the last patch you sent:
> 
>     * https://cirrus-ci.com/task/5316374168862720
> 
>     * https://cirrus-ci.com/task/6442274075705344

Looking into it.

**Comment by matttbe** [comment]
@spoorva before closing this ticket, may you create a PR to add your new test script in our packetdrill repo please?
