### ISSUE TITLE
dmesg giving wrong output regarding MPTCP

### ISSUE THREAD

**Issue by somnathjena2011** [multipath-tcp/mptcp_net-next#228]
I was configuring a new linux kernel 5.6.9 from my Ubuntu 20.04 linux kernel 5.11.0-27-generic.
On doing **dmesg | grep MPTCP** in **5.11.0-27-generic**, following was the output:
[    1.084739] MPTCP token hash table entries: 4096 (order: 4, 98304 bytes, linear) 

On doing **dmesg | grep MPTCP** in **5.6.9**, following the output was NULL

Here are the **configurations regarding MPTCP in 5.11.0-27-generic**:
```
CONFIG_MPTCP=y
CONFIG_INET_MPTCP_DIAG=m
CONFIG_MPTCP_IPV6=y
```

Here are the **configurations regarding MPTCP in 5.6.9**:
```
CONFIG_MPTCP=y
CONFIG_MPTCP_IPV6=y
## CONFIG_MPTCP_HMAC_TEST is not set
```

My question is since MPTCP is included in the configuration and also for IPv6, why is dmesg not showing the version number?

**Comment by matttbe** [comment]
> My question is since MPTCP is included in the configuration and also for IPv6, why is dmesg not showing the version number?

I'm not sure to understand your question.

MPTCP in the upstream kernel is still under development: https://github.com/multipath-tcp/mptcp_net-next/wiki#changelog
Some features have been added later like the token hash table.
If you don't see it in your v5.6 kernel, it doesn't mean MPTCP is not available. There are other ways to check MPTCP is available: https://developers.redhat.com/blog/2020/08/19/multipath-tcp-on-red-hat-enterprise-linux-8-3-from-0-to-1-subflows/

Can we close the ticket?

**Comment by somnathjena2011** [comment]
Thanks very much for the clarification. I checked using the sysctl command
and think MPTCP is enabled.
You can close it now.

**Comment by matttbe** [comment]
:+1: 

One last thing before closing this ticket: MPTCP on a v5.6 has very limited features. It was enough to start getting some apps ready but not sure there is an interest to use MPTCP with only one subflow :)
https://github.com/multipath-tcp/mptcp_net-next/wiki#changelog
