### ISSUE TITLE
sockopt: support TCP_CORK and TCP_NODELAY

### ISSUE THREAD

**Issue by matttbe** [multipath-tcp/mptcp_net-next#243]
This is important to cover proxy use-cases.

@darkwrat already sent patches and packetdrill tests.

**Comment by matttbe** [comment]
Patches are now in our tree:

- 46bc37d252e9: tcp: expose __tcp_sock_set_cork and __tcp_sock_set_nodelay
- 6d902bda5f72: mptcp: expose mptcp_check_and_set_pending
- 54c2d9725869: mptcp: support TCP_CORK and TCP_NODELAY
- Results: 2cb2e25a2eea..ca3b812b57ae

**Comment by jeff277** [comment]
Hi @matttbe 
My system is running Linux 5.15, and I cannot upgrade the kernel, but I need the functionality provided by that patch. I have two questions:

1、Does enabling the TCP_NODELAY feature depend on any additional patches?
2、If I directly merge that patch into Linux 5.15 and enable TCP_NODELAY, will it cause mptcp to become unstable or function improperly?

**Comment by matttbe** [comment]
Hi @jeff277 

> 1、Does enabling the TCP_NODELAY feature depend on any additional patches?

Probably, best to check.

> 2、If I directly merge that patch into Linux 5.15 and enable TCP_NODELAY, will it cause mptcp to become unstable or function improperly?

Same as for the previous question: it is hard to tell without trying. I guess it should be safe as it is "on the side". We cannot backport new features to the stable versions, so we will not do that. Plus these patches are 3 to 4 years old, hard to remember by heart how the code was at that time. Backporting such features take time.

> My system is running Linux 5.15, and I cannot upgrade the kernel, but I need the functionality provided by that patch. 

In 5.15, MPTCP was still under heavy development. I understand you might be stuck on an old kernel, but in terms of features I would recommend switching to the latest stable kernel, or latest LTS, or at least the v6.1.

**Comment by darkwrat** [comment]
@jeff277 you should also take the related patch from https://github.com/multipath-tcp/mptcp_net-next/issues/244

update: nevermind, it was backported to 5.15, so you should be good wrt that bug
