### ISSUE TITLE
see mptcp options when running iperf locally

### ISSUE THREAD

**Issue by teto** [multipath-tcp/mptcp_net-next#247]
I would like to capture some MPTCP traffic locally (I've `sysctl net.mptcp.enabled = 1`), yet when I run an iperf3 transfer localhost, I dont see any MPTCP option in the TCP headers (capturling localhost with wireshark 3.4.9). I run  5.15.4. The out of tree linux mptcp multipath-tcp.org/ had some code to disable mptcp on localhost (and I had patched it to run my tests). Is it the same with net-next ? I had a quick look at the code but could not find anything similar.

**Comment by matttbe** [comment]
Hi Matthieu,

> I would like to capture some MPTCP traffic locally (I've sysctl net.mptcp.enabled = 1), yet when I run an iperf3 transfer localhost, I dont see any MPTCP option in the TCP headers (capturling localhost with wireshark 3.4.9).

What did you do to have IPerf3 creating an MPTCP socket? I guess you noticed your app has to create a specific MPTCP socket and not a regular TCP one. (Linked to [How to use MPTCP?](https://github.com/multipath-tcp/mptcp_net-next/wiki#how-to-use-mptcp) section in our wiki.)

When you use your modified/ld_preloaded IPerf3 with other interface, is it OK?

**Comment by teto** [comment]
thanks again mattt for helping me ;) 
arf I had completely missed the wiki info thanks. I run both client and server with `mptcpize` like `mptcpize iperf -s` yet wireshark still showed a TCP only transfer. Could anyone confirm whether they had success with mptcpize and iperf3 ? 

I haven't tested https://github.com/pabeni/mptcp-tools.git yet but that would be my next try.

I might take a stab at https://github.com/multipath-tcp/mptcp_net-next/issues/213 once I can get sthg running. I was looking in `man tcp` to have a description of net.mptcp.enabled but even there nothing. I wish I can at least fix that.

**Comment by vandit86** [comment]
Hello, 
_`mptcpize`_ does not work for me either. I use [this wrapper from wiki](https://github.com/pabeni/mptcp-tools/tree/master/use_mptcp) to generate mptcp traffic.

**Comment by matttbe** [comment]
The best would be to use this patched version of IPerf: https://github.com/esnet/iperf/pull/1166

If it works, please mention that on the IPerf PR, not sure why it has not been merged yet.

**Comment by pabeni** [comment]
On Thu, Dec 9, 2021 at 7:27 PM Matthieu Coudron ***@***.***>
wrote:

> arf I had completely missed the wiki info thanks. I run both client and
> server with mptcpize like mptcpize iperf -s yet wireshark still showed a
> TCP only transfer.
>
Note that you must use the 'mptcpize' on both sides, e.g.:

mptcpize iperf -s
mptcpize iperf -c 127.0.0.1


> Could anyone confirm whether they had success with mptcpize and iperf3 ?
>

Current mptcpize is known to work well with iperf3. If it's not working for
you, please provide the 'strace' traces for both the client and the server,
e.g.:

strace -f -o out.server mptcpize iperf -s &
strace -f -o out.client mptcpize iperf -c 127.0.0.1 -n 10000

the '-n' option is provided to limit the transfer to a few bytes and avoid
long reports

Cheers,

Paolo

**Comment by teto** [comment]
with the patched iperf I can make it work thanks, I will give a try at mptcpize again but I had launched it for both client and server as well.

**Comment by pabeni** [comment]
> with the patched iperf I can make it work thanks, I will give a try at mptcpize again but I had launched it for both client and server as well.

Note that you need a recent version of the tool, specifically containing the commit:

commit 5633f08e35552295b2f9414ff32ca4e8e081b2f2
Author: Paolo Abeni <paolo.abeni@gmail.com>
Date:   Tue Oct 12 19:24:33 2021 +0200

    mptcpize: force MPTCP usage for IPPROTO_IP, too (#159)

No released version contain the above yet: you must use the current git snapshot.

**Comment by teto** [comment]
ha that must have been it, I was using 0.8.
I've tried with the master version of mptcpd and with vanilla iperf3 I get:
```
❯ result/bin/mptcpize run iperf3 -s 
-----------------------------------------------------------
Server listening on 5201 (test #1)
-----------------------------------------------------------
iperf3: error - unable to set TCP/SCTP NODELAY: Operation not supported
```
while truing to connect with
```
result/bin/mptcpize run  iperf -c 192.168.1.17 --cport 2042 -4
iperf3: error - unable to set TCP/SCTP NODELAY: Operation not supported
```
Should I set cap_net_admin or some specific capability ? I've tried with `sudo result/bin/mptcpize run iperf3 -s ` with the same effect.

**Comment by matttbe** [comment]
Is there an option for IPerf not to use NODELAY?
If not, maybe the easiest is to use a v5.16 kernel (or our `export` branch).

**Comment by teto** [comment]
there is a `-N`. For some reason I've installed mptcpize and I dont see the `unable to set TCP/SCTP NODELAY` error anymore but iperf3 doesn't create an mptcp session either. For now I am happy with using @pabeni's fork so closing this. Thanks all for the help.

**Comment by Monika-Research** [comment]
Hi,
I don't see this issue with iperf 3.9. Only versions beyond 3.9 reports "unable to set TCP/SCTP NODELAY: Operation not supported". I won't be able to use 3.9 as our devices might lose some features if we downgrade. Kindly let me know if there is any patch to get mptcpize working with iperf 3.10 and above version or  what can be the best way to get away with this issue?

Appreciate support and help.

Thanks,
Monika
