### ISSUE TITLE
selftests: connect: checksum failed

### ISSUE THREAD

**Issue by geliangtang** [multipath-tcp/mptcp_net-next#255]
I got the checksum failures when runing the command

    # ./mptcp_connect.sh -C

It seems easy to reproduce.

Here I attached the kernel log and pcap files.

[61ee2768-fvDu6X-ns1-ns2-MPTCP-MPTCP-10007.tar.gz](https://github.com/multipath-tcp/mptcp_net-next/files/7922634/61ee2768-fvDu6X-ns1-ns2-MPTCP-MPTCP-10007.tar.gz)

**Comment by matttbe** [comment]
From the last meeting we just had:

- @pabeni tried to reproduce the issue but he was not able to.
- @geliangtang: was there anything else applied on top of the export branch?

**Comment by geliangtang** [comment]
@matttbe @pabeni

I reproduced this issue just using the export branch, no other patch applied.

I used a loop to run mptcp_connect.sh:

> for i in `seq 1 10`; do sudo ./mptcp_connect.sh -C; done

And monitor the kernel log to check if the checksum failures happened:

> sudo cat /proc/kmsg | grep MP_FAIL
