### ISSUE TITLE
MPTCP is enabled but not working

### ISSUE THREAD

**Issue by rezapoorzare1** [multipath-tcp/mptcp_net-next#272]
Hello there,

first of all, thank you o much for the great protocol.

I have installed mptcp in Ubuntu 22 and, sysctl net.mptcp.enabled is returning 1, but I can not see mptcp in uname -a, and in the net/mptcp folder threre are only five files. What can be wrong? Would you please help me.

Thanks a lot

**Comment by pabeni** [comment]
> I have installed mptcp in Ubuntu 22 and, sysctl net.mptcp.enabled is returning 1, but I can not see mptcp in uname -a, and in the net/mptcp folder threre are only five files. What can be wrong? Would you please help me.

Reading the above I suspect you are referring to the documentation of some legacy/out-of-tree MPTCP implementation. Please be sure to have a look at:

https://github.com/multipath-tcp/mptcp_net-next/wiki#how-to-use-mptcp

for general guidance on how to use MPTCP.

Note that: 
- the MPTCP can be enabled regardless of 'mptcp' string being present into the uname info. What is relevant is the kernel version 
- only a bunch of sysctl are available, and end-user configuration should be performed via the iproute2 tool.
- the kernel version 5.15 supports MPTCP, but you would be better off with a more recent kernel version (ideally latest and greatest).

**Comment by rezapoorzare1** [comment]
Thanks a lot for your answer

The way I am doing the procedure is this:

I have upgraded the kernel to 5.17.5-051705-generic

I have downloaded the package from: https://github.com/multipath-tcp/mptcp_net-next

I did the menuconfig then make to compile the 4.19.234 mptcp kernel, it the procedure right until here?

Thanks a lot

**Comment by VenkateswaranJ** [comment]
There are two different implementations of MPTCP
1. https://github.com/multipath-tcp/mptcp (out-of-tree) 
    You can use this implementation by patching the Linux kernel via apt or rpm or manually (as described here https://multipath-tcp.org/pmwiki.php/Users/HowToInstallMPTCP?). Once you patched the kernel then you will see the **mptcp** string in `uname -a`
Note: This implementation only supports [Mptcp version 0](https://datatracker.ietf.org/doc/html/rfc6824) fully and partially supports [Mptcp version 1](https://datatracker.ietf.org/doc/html/rfc8684)

3. https://github.com/multipath-tcp/mptcp_net-next (upstream)
    from Linux kernel >= 5.6, shipped with upstream mptcp implantation, you won't see in `uname -a`  but once you enable the mptcp your TCP connection will become mptcp and you can check them in Wireshark or tcpdump. 
Note: It's still in progress and with each kernel release [you will get new features](https://github.com/multipath-tcp/mptcp_net-next/wiki#changelog).

**Comment by rezapoorzare1** [comment]
Thanks you so much.
I almost know all of the mentioned, just one question:
how to patch upstream mptcp to the kernel after downloading?

Thanks a lot

**Comment by VenkateswaranJ** [comment]
Hmm, I don't understand why you want to patch the upstream kernel as it already has mptcp implementation. If you want the latest upstream kernel mptcp changes then just directly build the kernel from [export branch](https://github.com/multipath-tcp/mptcp_net-next/tree/export) 

Here is some example of how you can build the kernel in Debian and generate deb files to install https://wiki.debian.org/BuildADebianKernelPackage

If you want to patch out-of-tree mptcp implementation to the kernel < 5.6 then follow these steps https://multipath-tcp.org/pmwiki.php/Users/HowToInstallMPTCP

**Comment by rezapoorzare1** [comment]
Thank you for the clarification.
My mistake was that I was thinking like MPTCP V0, upstream is not included in the kernel. 

Sorry another question, does the upstream one support different congestion controls like LIA, OLIA, ..., if yes, how to change between the them in this version? 

Thanks a lot

**Comment by VenkateswaranJ** [comment]
Sorry! I'm not sure about you can do that in the upstream kernel. Hope someone else could clarify this.

**Comment by pabeni** [comment]
> Sorry another question, does the upstream one support different congestion controls like LIA, OLIA, ..., if yes, how to change between the them in this version?

The available CCAs are those provided by the stock TCP implementation (no MPTCP-specific CCA is available). You can select the relevant CCA either via the net.ipv4.tcp_congestion_control sysctl or via the TCP_CONGESTION socket option.

Please consider joining the #MPTCP IRC channel on libera net for this kind of questions.

**Comment by rezapoorzare1** [comment]
Thanks a lot for your time and response.

So, to conclude, There are two mptcp implementations, one based on RFC 6824, which needs kernel compilation, and can manipulated by using sysctl command in term of schedulers and congestion control mechanisms.
The other one is based on RFC 8684, which is included in the new kernels and does not need compilation and is ready to be deployed (am I right), but with less flexibility on congestion control mechanism selection and stuff like that. The only thing is to make the configuration based on https://multipath-tcp.org/pmwiki.php/Users/ConfigureRouting and ready to go, right?

I appreciate the time that you spend on answering the questions

**Comment by pabeni** [comment]
>The only thing is to make the configuration based on https://multipath-tcp.org/pmwiki.php/Users/ConfigureRouting and ready to go, right?

You should additionally ensuring the relevant application is using MPTCP - the 3rd bullet on https://github.com/multipath-tcp/mptcp_net-next/wiki#how-to-use-mptcp.

Then you likely want to really configure and use multiple paths - the 5th bullet in the same list. This last part is likely the more complex one - and we likely need to expand the available documentation. Again feel free to join the IRC channel for more info.

**Comment by rezapoorzare1** [comment]
Thank you so much for your detailed explanation.
I think I have done all parts"

The output of grep:
CONFIG_MPTCP=y
CONFIG_INET_MPTCP_DIAG=m
CONFIG_MPTCP_IPV6=y

The output of sysctl net.mptcp.enabled
net.mptcp.enabled = 1

I have done the routing and the outputs are correct.

Now I want to download files from http://multipath-tcp.org/snapshots/ to see whether Wireshark traces mptcp or not.

I have some problems with bullet 3 and 5 and cannot understand them well.
 
Please, lets start with bullet 5:
ip mptcp endpoint add <ip> dev <iface> <subflow|signal>
what should I put in the IP field, the IP of the destination?!
What about iface, the name of the NIC? for example,  wlp0s20f3?
and what about subflow|signal? I down have any clues about this one.

Would you please guide me on bullet three and using mptcpize?

I really appreciate you time and guidance

**Comment by pabeni** [comment]
> Now I want to download files from http://multipath-tcp.org/snapshots/ to see whether Wireshark traces mptcp or not.

That will fail, as the server only supports mptcp v0, while the upstream kernel only support v1 - for good reasons.

> Please, lets start with bullet 5:
> ip mptcp endpoint add dev <subflow|signal>

Hopefully the ip-mptcp man page should explain the above:

https://man7.org/linux/man-pages/man8/ip-mptcp.8.html

Some more info here:

https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/9-beta/html/configuring_and_managing_networking/getting-started-with-multipath-tcp_configuring-and-managing-networking#using-iproute2-to-configure-and-enable-multiple-paths-for-mptcp-applications_getting-started-with-multipath-tcp

**Comment by rezapoorzare1** [comment]
Thanks a lot.

Which servers support this version, so connecting to them will show mptcp in wireshark?

**Comment by rezapoorzare1** [comment]
I have checked the subflows by the following command and can see the subflows are established, correct?
How can I test the mptcp? Which servers support the upstream one?

ip mptcp endpoint show 
fe80::cb4c:1cde:6094:9609 id 1 dev wlp0s20f3 
10.164.148.82 id 2 dev wlp0s20f3 
fe80::f09e:d89b:1201:d65b id 3 dev enp0s31f6 
10.181.120.151 id 4 dev enp0s31f6 

Thanks a lot

**Comment by rezapoorzare1** [comment]
and sorry one more question, how can we change the schedulers in the upstream version? For example, from default to round-robin and vice verca.

Thanks a lot

**Comment by matttbe** [comment]
> Which servers support this version, so connecting to them will show mptcp in wireshark?

We still need to put in place public test servers. I don't know any public one you can use.

But you can easily install `mptcpize` on Ubuntu 22.04 and run an IPerf server as described there: https://www.tombarbette.be/mptcp-on-windows-with-wsl2/

> how can we change the schedulers in the upstream version?

There is only one packets scheduler in v5.15 kernel. It is being developed, see #75.

**Comment by rezapoorzare1** [comment]
Thanks a lot for your answer.
I appreciate the time you spend clearing stuff for me.

**Comment by matttbe** [comment]
Great!
I think we can close this ticket, right?
