### ISSUE TITLE
selftests: `mptcp_join.sh`: `delete and re-add` test is regularly failing

### ISSUE THREAD

**Issue by matttbe** [multipath-tcp/mptcp_net-next#274]
The new test (`104 delete and re-add`) is regularly failing on the public CI and Tessares' one, e.g.

```
# 104 delete and re-add                    after delete[ ok ]
#                                          after re-add[fail] got 0:0 subflows expected 2
# State Recv-Q Send-Q Local Address:Port Peer Address:PortProcess
```
(without a debug kernel)
https://api.cirrus-ci.com/v1/artifact/task/5992746505732096/summary/summary.txt

or

```
# 104 delete and re-add                    after delete[fail] got 0:0 subflows expected 1
# State Recv-Q Send-Q Local Address:Port Peer Address:PortProcess
#                                          after re-add[fail] got 0:0 subflows expected 2
# State Recv-Q Send-Q Local Address:Port Peer Address:PortProcess
```
(with a debug kernel)
https://api.cirrus-ci.com/v1/artifact/task/5429796552310784/summary/summary.txt

Note that the patch introducing this new test has not been upstreamed yet:

https://patchwork.kernel.org/project/mptcp/patch/df068e913873450bfbcabe98f4d4461178278264.1651165091.git.pabeni@redhat.com/
(cc: @pabeni)

**Comment by matttbe** [comment]
@pabeni suggested this patch:

```diff
diff --git a/tools/testing/selftests/net/mptcp/mptcp_join.sh b/tools/testing/selftests/net/mptcp/mptcp_join.sh
index a5e90532eaea..fd35603bc21a 100755
--- a/tools/testing/selftests/net/mptcp/mptcp_join.sh
+++ b/tools/testing/selftests/net/mptcp/mptcp_join.sh
@@ -2839,7 +2839,7 @@ endpoint_tests()
 		pm_nl_set_limits $ns1 1 1
 		pm_nl_set_limits $ns2 1 1
 		pm_nl_add_endpoint $ns2 10.0.2.2 id 2 dev ns2eth2 flags subflow
-		run_tests $ns1 $ns2 10.0.1.1 0 0 0 slow &
+		run_tests $ns1 $ns2 10.0.1.1 4 0 0 slow &
 
 		wait_mpj $ns2
 		pm_nl_del_endpoint $ns2 2 10.0.2.2

```

It seems helping! On my side, it was easy to reproduce the issue before the patch with a debug kernel config. With the patch, this test ran 1667 times without issues.

Thanks!

**Comment by matttbe** [comment]
@pabeni: do you mind if I already apply this patch so we avoid errors when validating other patches? :)

**Comment by pabeni** [comment]
> @pabeni: do you mind if I already apply this patch so we avoid errors when validating other patches? :)

@matttbe: please go ahead...

**Comment by matttbe** [comment]
Thank you!
Just applied in our tree:

- b195639989ab: "squashed" in "selftests: mptcp: add subflow limits test-cases"
- Results: ffee67422349..825394fc0bc5 (export)
- Results: a2c76d73f38a..ca8b19c6d86b (export-net)


Builds and tests are now in progress:

https://cirrus-ci.com/github/multipath-tcp/mptcp_net-next/export/20220506T172517
https://github.com/multipath-tcp/mptcp_net-next/actions/workflows/build-validation.yml?query=branch:export

https://cirrus-ci.com/github/multipath-tcp/mptcp_net-next/export-net/20220506T172517
https://github.com/multipath-tcp/mptcp_net-next/actions/workflows/build-validation.yml?query=branch:export-net
