### ISSUE TITLE
PM: in-kernel: support for MPC prio exchange 

### ISSUE THREAD

**Issue by daire-byrne** [multipath-tcp/mptcp_net-next#285]
The MP_CAPABLE handshake doesn't have room to include the backup frags (no priority information can be passed along during the MPC handshake). In other words, to have the initial subflow set as "backup", it is then required to send a dedicated `MP_PRIO` message after the establishment of the connection.

The in-kernel PM should be able to do that. `MPTCP_PM_CMD_SET_FLAGS` netlink command needs to be modified to handle subflow ID 0. Same for the in-kernel path manager to react after the establishment of the connection to send this `MP_PRIO` if needed.

------------------------

(_Original message_)

Sorry to spam your github issues list, but I couldn't find the right active mailing list to ask this question (happy to ask it there if you point me in the right direction).

I have a slightly odd topology and I just can't seem to figure out how to implement it with (kernel) mptcp (if it's possible).

I have a server with 3 IPs and a client with 3 IPs all routing to each other in pairs. I would like to be able to initiate the connection between them on the first IP pair (using mptcpize), but then once the connection is up, only transfer bulk data on the second and third IP pairs.

It seems like the connecting IP pair needs to be part of the subsequent mptcp connection no matter what and no amount of removing it as an endpoint or changing the type (signal, subflow, backup) makes much difference. I got a bit lost in the handshake details and subflow setup literature....

The reason I ask is that I would like 2 pairs of IPs to do the bulk transfers but if one goes down or is not routeable, I'd still like to use a common "management" IP for applications to initiate new connections without having to change the destination IP. The routing between the first pair is designed to be fault tolerant and the other two "bulk" pairs are not.

I probably haven't explained that very well but there is method to this madness!

Thanks for all the hard work on getting this into the kernel BTW, we're really excited to start using this for lots of different applications.

Daire

**Comment by mjmartineau** [comment]
I think the mailing list you're looking for is mptcp@lists.linux.dev, but no problem submitting the issue here.

Which version of the kernel are you using?

The way you're trying to force data on to specific subflows is exactly what the 'backup' flag addresses for endpoints handled by the in-kernel path manager. If you were trying to make any subflow other than the initial one (ID = 0) be the non-bulk path, the 'backup' flag would do so with the `ip mptcp endpoint add` or `ip mptcp endpoint change` commands. But the initial subflow is a special case and the MPTCP netlink API for the in-kernel path manager doesn't have a way to flag that subflow as a backup.

For the in-kernel path manager, an option is to modify the `MPTCP_PM_CMD_SET_FLAGS` netlink command to handle subflow ID 0, and use it to set a namespace-wide default to set the backup bit on all initial subflows. At this point, the earliest kernel with such a feature would be v5.20 or later.

I think this also highlights a gap in our upcoming userspace path manager for kernel v5.19 and later: it looks like we don't have a way to adjust subflow priority for userspace-managed subflows after they are created.

Another feature we have in development is a BPF-based packet scheduler. If that was available, you could implement a custom scheduler that de-prioritized the initial subflow. However, this is another v5.20 or later feature.

**Comment by daire-byrne** [comment]
Thanks Mat, I'll subscribe to the mailing list as I'm bound to have more annoying questions as I go along.

I am currently using the v5.17.6 kernel with the RHEL 8.5 toolset. But I can easily use v5.18+ too.

I did also play around with setting the connection endpoints to be backup but as you say, it seems like that currently has no effect when you initiate the connection on them. I have also been running the mptcpd service but again, it doesn't seem like there is a way to configure the topology that I want.

For the time being, I have just setup a qdisc htb limit of 50mbit between the initial connecting pair so that the majority of the bulk transfers happen on the second and third pairs of interfaces (which essentially map to two different ISPs).

It's not ideal and I worry that it will impact the performance of initiating more connections but it's the best I could come up with for now.

It sounds like I'll have to wait until at least v5.20 until we can do this in a better way.

Thanks for the feedback!

Daire

**Comment by matttbe** [comment]
Hello,

@mjmartineau can we consider this story as a duplicated of #286 ? Or is it not enough to add `MPTCP_PM_CMD_SET_FLAGS` support?

**Comment by mjmartineau** [comment]
@matttbe: I opened #286 to cover userspace PM MP_PRIO functionality. I think this issue (285) is still relevant for in-kernel PM changes to accommodate priority changes on the initial subflow.

**Comment by pabeni** [comment]
> For the in-kernel path manager, an option is to modify the `MPTCP_PM_CMD_SET_FLAGS` netlink command to handle subflow ID 0, and use it to set a namespace-wide default to set the backup bit on all initial subflows. At this point, the earliest kernel with such a feature would be v5.20 or later.

More discussion on this topic following the latest public mtg:
as the MP_CAPABLE handshake ignores the backup frags (no priority information can be passed along during the MPC handshake), modify the `MPTCP_PM_CMD_SET_FLAGS` netlink command to handle subflow ID 0 would not be enough.

Additionally we need to update the in-kernel path manager to let it apply such setting.

A possible implementation could hook into the MPTCP_FULLY_ESTABLISHED event, check if the first subflow priority matches the priority configured via netlink and e.v. triggering the MP_PRIO exchange.

Once that the last point above is in place, no need to handle `MPTCP_PM_CMD_SET_FLAGS` for subflow ID 0: the user could create endpoints for each local available addresses, and set the priority as preferred. e.g.

Let's suppose that the host has 2 addresses A and B, the main default route uses address A as source. The user configures 2 endpoints: E-A on top of address A and E-B on top of address B. E-A has the 'backup' flag set, both have the 'subflow' flag set. At mptcp socket creation time, the first subflow will use address A as source. At MPTCP socket establishment time the in-kernel path manager will flip the priority to backup,  and will try to create the 2nd subflow using address B as source.

**Comment by matttbe** [comment]
This can be closed thanks to @pabeni 's patches, thanks!

New patches for t/upstream:
- 063213e73149: mptcp: introduce and use mptcp_pm_send_ack()
- 69bc499efccb: mptcp: address lookup improvements
- 0417a959d55e: mptcp: allow the in kernel PM to set MPC subflow priority
- 084ba8b4dc1a: mptcp: more accurate MPC endpoint tracking
- 267566754670: selftests: mptcp: add MPC backup tests
- Results: c47b82c7b9aa..7d868133e0d9 (export)

Tests results: https://cirrus-ci.com/github/multipath-tcp/mptcp_net-next/export/20220706T170628

**Comment by daire-byrne** [comment]
I just wanted to follow up on this and say that I have tested v6.0-rc1 and setting the initial connection IP endpoints to be "backup" subflows is now working as we wanted.

We can initiate the connections on the backup subflow endpoints but then see all subsequent transfer traffic on the configured bulk (signal) subflows.

Many thanks!

**Comment by matttbe** [comment]
@daire-byrne Thank you for having validated that!
