### ISSUE TITLE
Make MPTCP_PM_CMD_SET_FLAGS usable with the userspace PM

### ISSUE THREAD

**Issue by mjmartineau** [multipath-tcp/mptcp_net-next#286]
The userspace PM doesn't have a way to send MP_PRIO commands.

When looking at #285, I thought maybe the userspace PM could help with setting MP_PRIO on subflow 0. But the current code only looks up entries in the in-kernel PM `local_addr_list`, so it's not usable for userspace-PM-managed connections.

I suggest we modify `MPTCP_PM_CMD_SET_FLAGS` to allow sending MP_PRIO updates for userspace PM connections by using the presence of a `MPTCP_ATTR_TOKEN` attribute to operate in a different mode, where `MPTCP_ATTR_TOKEN`, `MPTCP_PM_ADDR_ATTR_ID`, and `MPTCP_PM_ADDR_FLAG_BACKUP` are used to directly send MP_PRIO.

**Comment by geliangtang** [comment]
@mjmartineau Mat, I don't know whether Kishen will complete this issue. If no one is looking at this yet, I'm willing to do it. If so, please assign this issue to me, and I'll try to finish it in the near future. Thanks.

**Comment by mjmartineau** [comment]
@geliangtang I did check with @kmaloor yesterday and he does have time to look at this. So, I'll assign it and set the 'bug' label since this is something we overlooked with the userspace PM series.

**Comment by mjmartineau** [comment]
The attributes I requested for this command turn out to be too limiting: they only allow changing the subflow priority for all subflows using a specific local endpoint. After looking at the mptcpd code for setting subflow priority that uses the multipath-tcp.org netlink API, I think the attributes for  `MPTCP_PM_CMD_SET_FLAGS` should be:

- `MPTCP_ATTR_TOKEN`
- `MPTCP_PM_ATTR_ADDR` (local endpoint address and port)
- `MPTCP_PM_ATTR_ADDR_REMOTE` (remote address and port)
- `MPTCP_PM_ADDR_FLAG_BACKUP`
