### ISSUE TITLE
Not possible to `connect()` after a disconnect for a passive socket

### ISSUE THREAD

**Issue by matttbe** [multipath-tcp/mptcp_net-next#290]
@pabeni reported that it is not possible to do a `connect()` after a disconnect for a passive socket.

It fails because the passive MPTCP socket -- created after an `accept()` -- has the `struct socket` missing for the first subflow.

A solution would be to allocate new `struct socket` at the disconnect time but then unexpected errors might happen, e.g. ENOMEM. Quite unexpected at the disconnect time, it might not be handled properly on the userspace side.

**Comment by matttbe** [comment]
The patch initially fixing this issue has been reverted, see #352

**Comment by pabeni** [comment]
should be addressed by the recent msk->subflow refactor:

b5b697343d7f mptcp: get rid of msk->subflow
