### ISSUE TITLE
Meaning of newly added sysctl fields in upstream kernel

### ISSUE THREAD

**Issue by VenkateswaranJ** [multipath-tcp/mptcp_net-next#297]
Hello,

I already have written a userspace path manager for the mptcp v0 out-of-tree kernel and currently exploring mptcp v1 (upstream) implementation. I came to know that there are some new fields added in systctl to change mptcp kernel parameters, It would be great if someone explains what they exactly mean.

> net.mptcp.add_addr_timeout = 120

I know that in Mptcp v1 we are no more using dup ask to announce subflow address. So it's gonna be a normal TCP request, is this field related to that?

> net.mptcp.allow_join_initial_addr_port = 1

something to do with remote accepting the `create subflow command`. Please explain what it exactly means.

> net.mptcp.pm_type = 0

what are the available pm types in the upstream kernel? where can I find them? does 0 mean fullmesh

> net.mptcp.stale_loss_cnt = 4

no idea what this means

**Comment by matttbe** [comment]
Hello,

Good you are looking at switching to MPTCP Upstream (note that MPTCPv1 spec is also supported by the out-of-tree kernel).

Does this doc answer your questions?

https://github.com/multipath-tcp/mptcp_net-next/blob/export/Documentation/networking/mptcp-sysctl.rst

**Comment by vandit86** [comment]
Hello, 
check this link : 
https://www.kernel.org/doc/html/v5.19/networking/mptcp-sysctl.html?highlight=mptcp

**Comment by VenkateswaranJ** [comment]
@matttbe & @vandit86 Thanks for the links. Still need some little clarifications on the things.

> **allow_join_initial_addr_port - BOOLEAN**
Allow peers to send join requests to the IP address and port number used by the initial subflow if the value is 1. This controls a flag that is sent to the peer at connection time, and whether such join requests are accepted or denied.
Joins to addresses advertised with ADD_ADDR are not affected by this value.

I don't get this. Usually, the server advertises its second IP address via ADD_ADDR and the client tries to create the subflow by sending a join. In which scenario client wants to send a join request to the initial subflow address?

> **pm_type - INTEGER**
> Set the default path manager type to use for each new MPTCP socket. In-kernel path management will control subflow connections and address advertisements according to per-namespace values configured over the MPTCP Netlink API. Userspace path management puts per-MPTCP-connection subflow connection decisions and addresses advertisements under the control of a privileged userspace program, at the cost of more Netlink traffic to propagate all of the related events and commands.
> This is a per-namespace sysctl.
> 0 - In-kernel path manager
> 1 - Userspace path manager

Does this mean that we don't have any kernel space path manager implementation in the upstream kernel (similar to some of them we have in out-of-tree)? either we can use the `ip` command ([man page](https://manpages.debian.org/unstable/iproute2/ip-mptcp.8.en.html)) or some userspace path manager like mptcpd. What do we mean by `In-kernel path manager` here? Is it those flags (signal, subflow, backup, fullmesh) used in the `ip` command while endpoint creation?

If that's the case I have another two question

1. I read in some thread that in upstream kernel implementation mptcp server is only allowed to announce signals and the client is only allowed to create subflow, in this case, what happens if I endpoint in the server side with the `subflow` flag instead of `signal` flag?
2. I can use the Netlink API (commands and events) from user space even though the `pm_type` is set to 0 and the only difference is that the path manager will be applied for all the MPTCP connections in the namespace when pm_type is 0 and to individual MPTCP connection when pm_type is 1.

Do we have the `redundant scheduler` in the upstream kernel?

**Comment by matttbe** [comment]
> @matttbe & @vandit86 Thanks for the links. Still need some little clarifications on the things.
> 
> > **allow_join_initial_addr_port - BOOLEAN**
> > Allow peers to send join requests to the IP address and port number used by the initial subflow if the value is 1. This controls a flag that is sent to the peer at connection time, and whether such join requests are accepted or denied.
> > Joins to addresses advertised with ADD_ADDR are not affected by this value.
> 
> I don't get this. Usually, the server advertises its second IP address via ADD_ADDR and the client tries to create the subflow by sending a join. In which scenario client wants to send a join request to the initial subflow address?

This is linked to the `C` flag in the MP_CAPABLE message (Do not attempt to establish new subflows to the source address.), see https://www.rfc-editor.org/rfc/rfc8684.html#section-3.1-20.6

That's an indication the server can give. This is useful for some load balancers.

> > **pm_type - INTEGER**
> > Set the default path manager type to use for each new MPTCP socket. In-kernel path management will control subflow connections and address advertisements according to per-namespace values configured over the MPTCP Netlink API. Userspace path management puts per-MPTCP-connection subflow connection decisions and addresses advertisements under the control of a privileged userspace program, at the cost of more Netlink traffic to propagate all of the related events and commands.
> > This is a per-namespace sysctl.
> > 0 - In-kernel path manager
> > 1 - Userspace path manager
> 
> Does this mean that we don't have any kernel space path manager implementation in the upstream kernel (similar to some of them we have in out-of-tree)? either we can use the `ip` command ([man page](https://manpages.debian.org/unstable/iproute2/ip-mptcp.8.en.html)) or some userspace path manager like mptcpd. What do we mean by `In-kernel path manager` here? Is it those flags (signal, subflow, backup, fullmesh) used in the `ip` command while endpoint creation?

Both 'in-kernel' and 'userspace' PM can be controlled via Netlink. The 'in-kernel' PM has "global" settings for all connections (of the current net namespace) while the 'userspace' accepts commands per connection.

So you control the 'in-kernel' PM with tools like `ip mptcp` or the latest version of Network Manager.
Please note that the latest version of mptcpd can control both the 'in-kernel' and 'userspace' PM: per namespace or per connection basis.

> If that's the case I have another two question
> 
>     1. I read in some thread that in upstream kernel implementation mptcp server is only allowed to announce signals and the client is only allowed to create subflow

(I don't remember if @kmaloor ended up removing this limitation or not)

> in this case, what happens if I endpoint in the server side with the `subflow` flag instead of `signal` flag?

It will not announce this endpoint. The PM "simply" iterates over the 'subflow' endpoints list when looking at establishing new subflow (client mode) and over the 'signal' endpoints list when looking at announcing new addresses (server mode).

>     2. I can use the Netlink API (commands and events) from user space even though the `pm_type` is set to 0 and the only difference is that the path manager will be applied for all the MPTCP connections in the namespace when pm_type is 0 and to individual MPTCP connection when pm_type is 1.

Is it a question or a comment? Because I'm not sure, the best would be to look at the code or experiment.
If I remember well, the idea was to restrict "automatic" actions from the 'in-kernel' PM by adding a few `mptcp_pm_is_userspace()` in `pm_netlink.c` code. So if I still remember that correctly, yes, you can send commands (and receive events) when the `pm_type` is set to 0. The only different when setting `1` is that no subflow will be created for clients except if you send a command for this connection. Same for the server side and the announced IP.

> Do we have the `redundant scheduler` in the upstream kernel?

No yet: see [patchwork](https://patchwork.kernel.org/project/mptcp/list/?series=655328&state=*)

**Comment by VenkateswaranJ** [comment]
@matttbe Thanks for your comments. Do we have any To Do task (or github issue) for adding a redundant scheduler? so that I can track it to know when it will get added.

**Comment by matttbe** [comment]
> Do we have any To Do task (or github issue) for adding a redundant scheduler? so that I can track it to know when it will get added.

It is somehow part of #75 for the moment.

**Comment by matttbe** [comment]
I guess I can close this ticket, right?

**Comment by VenkateswaranJ** [comment]
@matttbe you can close this issue.
