### ISSUE TITLE
ssh restart does not work

### ISSUE THREAD

**Issue by cpaasch** [multipath-tcp/mptcp_net-next#30]
When restarting ssh on a kernel which default-enables MPTCP I get the following error:

```
May 29 17:09:02 server sshd[4931]: error: Bind to port 22 on 0.0.0.0 failed: Address already in use.
May 29 17:09:02 server sshd[4931]: error: setsockopt IPV6_V6ONLY: Operation not supported
May 29 17:09:02 server sshd[4931]: error: Bind to port 22 on :: failed: Address already in use.
May 29 17:09:02 server sshd[4931]: fatal: Cannot bind any address.
May 29 17:09:02 server systemd[1]: ssh.service: Main process exited, code=exited, status=255/EXCEPTION
May 29 17:09:02 server systemd[1]: ssh.service: Failed with result 'exit-code'.
May 29 17:09:02 server systemd[1]: Failed to start OpenBSD Secure Shell server.
```

When doing this while being logged in to the host. I guess it's a missing socket-option (SO_REUSE*?).

**Comment by pabeni** [comment]
mptcp_{set,get}sockopt require some love. We have several issues there:

- SOCKET level {set,get}sockopt are always a no-op, __sys_setsockopt() calls sock_setsockopt() and that change msk bits, which are mostly unused. A possible fix would be copying from the msk into subflow before bind/connect/listen the relevant bits.

- SOL_IP/SOL_TCP can't work before bind()/listen()/connect(), as we need a first subflow to operate them and such subflow is created via __mptcp_socket_create() by the above syscall(). We likely want to move __mptcp_socket_create() into mptcp_init_sock()

- even after bind()/listen()/connect(), SOL_IP/SOL_TCP support is pretty much randomic as they only work after a fallback 

To fix ssh restart we need to address at lest the first point

Note that this partially overlaps with #21

**Comment by pabeni** [comment]
should be fixed with:

commit bdd2ed272151d89f8dc81a5a4046e3f8273b970d
Merge: f551e2fdaf81 c9b95a135987
Author: David S. Miller <davem@davemloft.net>
Date:   Sat Jul 4 17:56:22 2020 -0700
