### ISSUE TITLE
how to get mptcp subflow info 

### ISSUE THREAD

**Issue by VenkateswaranJ** [multipath-tcp/mptcp_net-next#301]
In mptcp out-of tree implementation, it's possible to get the subflow information by scraping **/proc/net/mptcp_net/mptcp**, but this file doesn't exist anymore in the upstream kernel. Do we have any other proc file to provide this info? or we need to read it via Netlink.

**Comment by matttbe** [comment]
Netdev maintainers are pushing to have all the info only available through Netlink (INET_DIAG). `ss` can list all MPTCP connections and subflows (with ULP layer info).

Does it answer your question?

**Comment by VenkateswaranJ** [comment]
Thanks
