### ISSUE TITLE
understanding ip-mptcp command behaviour

### ISSUE THREAD

**Issue by VenkateswaranJ** [multipath-tcp/mptcp_net-next#302]
1. I see that [ip-mptcp ](https://man7.org/linux/man-pages/man8/ip-mptcp.8.html) will configure every ip as an endpoint with a flag signal, even though it's not useful on the client side because the client endpoint has to be configured as subflow. Is it the right behaviour of the ip-mptcp program?

2. It establishes the second sublow between server and client at the initial stage of the mptcp connection, but once the two subflow got established it's not possible to remove one subflow and add a new one, for example in the case of an ip address changed in one interface. `ip mptcp endpoint del id 2` is sending `remove address` command but the subflow stays there when checking with `ss -nti '( sport :8000 )'`
So this kind of runtime management is not possible with ip-mptcp? should we use Netlink path manager for that?

**Comment by matttbe** [comment]
> I see that [ip-mptcp ](https://man7.org/linux/man-pages/man8/ip-mptcp.8.html)will configure every ip as an endpoint with a flag signal, even though it's not useful on the client side because the client endpoint has to be configured as subflow. Is it the right behaviour of the ip-mptcp program?

Sorry, I'm not sure to understand.
With `ip mptcp`, you can do the configuration you want: you can add endpoint with the IP you selected, with the `signal` or `subflow` flag but it will not do any automatic operations (e.g. every IP, only the `signal`flag).

> `ip mptcp endpoint del id 2` is sending `remove address` command but the subflow stays there when checking with `ss -nti '( sport :8000 )'`

I guess it might make more sense to also remove the subflows associated to the endpoint you just removed. That's a behaviour that seems to make more sense but to be discussed (and implemented).

It might be probably best to open a dedicated ticket for (2) if it is a behaviour to change (`feature` I suppose)

**Comment by VenkateswaranJ** [comment]
> Sorry, I'm not sure to understand.
> With ip mptcp, you can do the configuration you want: you can add endpoint with the IP you selected, with the signal or subflow flag but it will not do any automatic operations (e.g. every IP, only the signalflag).

I have installed ubuntu 22.04 and updated the kernel to 5.19 and also installed `mptcpize`, I didn't do anything other than that. Now, when I run `ip mptcp endpoint show` I expect it to be empty, but It list all my ip's added as an endpoint including ipv6 and they are added by default, so I need to run `ip mptcp endpoint flush` to clear those default endpoints and re-configure according to my purpose.

**Comment by pabeni** [comment]
> I have installed ubuntu 22.04 and updated the kernel to 5.19 and also installed `mptcpize`, I didn't do anything other than that. Now, when I run `ip mptcp endpoint show` I expect it to be empty, but It list all my ip's added as an endpoint including ipv6 and they are added by default, so I need to run `ip mptcp endpoint flush` to clear those default endpoints and re-configure according to my purpose.

both mptcpd and NetworkManger (starting from version 1.40) can/will create automatically endpoints for your local address. You can configure and/or disable such behavior via the respective configurations

**Comment by matttbe** [comment]
@VenkateswaranJ did you check if it was mptcpd (or NM 1.40.0) who was adding all these endpoints? Can we close this ticket?

**Comment by VenkateswaranJ** [comment]
yes, we can close it.
