### ISSUE TITLE
Allow MPTCP + SYN_COOKIES

### ISSUE THREAD

**Issue by cpaasch** [multipath-tcp/mptcp_net-next#31]
Just as a "reminder" so it is tracked as a task:

MPTCP + SYN_COOKIES support is important to allow webservers to enable MPTCP. Currently we are falling back to regular TCP when SYN-cookies are kicking in.

**Comment by matttbe** [comment]
This is supported in v5.9 thanks to modifications done by Florian, e.g. 9466a1ccebbe54ac57fb8a89c2b4b854826546a8 (but also other commits)
