### ISSUE TITLE
[Question] on using MPTCP for proxy

### ISSUE THREAD

**Issue by DevlopD** [multipath-tcp/mptcp_net-next#311]
Hello,

I am trying to run an MPTCP-TCP proxy with Ubuntu 22.04 (Linux 5.15), where proxy maintains MPTCP session at one side and TCP connection at the other side, and I wonder if there is any reference or verified proxy which runs with MPTCP.
I have used mptcpize to modify an existing nginx application with MPTCP socket, but it failed and proxy always closed the session when the client requested large file although it could perfectly work as backend MPTCP server.
SOCKS proxy altered by mptcpize like dante or shadowsocks might be good alternatives, but It was too hard to find benchmark tool for client to generate SOCKS request over MPTCP (some open sources are written in golang, and mptcpize seems not to work with them).

I would appreciate if you let me know any insight about running MPTCP proxy. Thank you in advance.

**Comment by matttbe** [comment]
Hello,

> I am trying to run an MPTCP-TCP proxy with Ubuntu 22.04 (Linux 5.15), where proxy maintains MPTCP session at one side and TCP connection at the other side, and I wonder if there is any reference or verified proxy which runs with MPTCP.

I don't have references but a quick research on Internet pointed me to two things:
* Using ShadowSOCKS with MPTCP: https://www.tessares.net/mptcp-proxy-setup-at-home-easier-now/
* A proxy implementation dedicated to MPTCP in GO: https://github.com/naoki9911/MPTCP-Proxy

>  I have used mptcpize to modify an existing nginx application with MPTCP socket, but it failed and proxy always closed the session when the client requested large file although it could perfectly work as backend MPTCP server.

May you retry with a recent kernel (e.g. 6.0 ; download and install all .deb from: [kernel-ppa](https://kernel.ubuntu.com/~kernel-ppa/mainline/v6.0/amd64/)) and report errors in a new ticket please? Because it should work and if not, we need to understand why.

> It was too hard to find benchmark tool for client to generate SOCKS request over MPTCP

Mmh, I don't where you can find that but feel free to share if you find/generate some.

> I would appreciate if you let me know any insight about running MPTCP proxy. Thank you in advance.

I'm not sure you will find many details here as it is focussed on the kernel dev. Here you are talking about a specific use case.

**Comment by DevlopD** [comment]
Hello,

Thanks for your kind reply, and I'm sorry to comment late.
First, After upgrading my kernel to Linux 6.0, the MPTCP socket issue on nginx was removed. My target was to use proxy which communicate with client over MPTCP, and server over TCP. I still have no idea why nginx proxy failed on Linux 5.15, but It might be not very important as it seems already fixed.

> Using ShadowSOCKS with MPTCP: https://www.tessares.net/mptcp-proxy-setup-at-home-easier-now/
A proxy implementation dedicated to MPTCP in GO: https://github.com/naoki9911/MPTCP-Proxy

I tested your suggested ones. Although I found that these are not proper for my own project (because of using SOCKS protocol or not written in C/C++), again thank you for sharing related information with me.

I also tested HAProxy and Squid web cache as MPTCP-TCP proxy. While HAProxy perfectly worked well in Linux 6.0, Squid (as system service) could not create MPTCP socket after "mptcpize". As I only tried running Squid in default configuration, this might be simply due to my setting miss and you might ignore my error case on Squid.

One more small question is that I experienced that nginx web server (not proxy) performed less goodput after mptcpize to establish MPTCP session with 2 subflows, even though I double checked on performance tuning and verified no packet was dropped during evaluation. Anyway, it is not directly related on this issue nor this git repository, and I think we can close this. Thank you!

**Comment by matttbe** [comment]
Hello,

Thank you for the feedback.

Do not hesitate to ask devs from HAProxy, Squid, nginx, etc. to support MPTCP without having to use mptcpize.
In theory, they just have to add one parameter when creating the socket. They can find some examples there: https://github.com/mptcp-apps/mptcp-hello

If you have performances issues, it is still good to report it here. Maybe there is something to improve on the kernel side. For example, if you use two networks where one has a very high throughput and the other one is very bad, see #307
