### ISSUE TITLE
packetdrill: `add_addr` test is regularly failing: packets arriving before the expected time

### ISSUE THREAD

**Issue by matttbe** [multipath-tcp/mptcp_net-next#312]
It is usually failing when executing the `retry` job, in v4, v6mapped and v6):

```
# FAIL [/opt/packetdrill/gtests/net/mptcp/add_addr/add_addr_retry_v4.pkt (ipv4-mapped-v6)]
# stdout: 
# stderr: 
# add_addr_retry_v4.pkt:22: error handling packet: timing error: expected outbound packet at 3.214190 sec but happened at 2.384757 sec; tolerance 0.800000 sec
# script packet:  3.214190 . 1:1(0) ack 1 <add_address address_id: 1 ipv4: 192.168.0.3 hmac: 10354569113664661296>
# actual packet:  2.384757 . 1:1(0) ack 1 win 256 <add_address address_id: 1 ipv4: 192.168.0.3 hmac: 10354569113664661296>
```

Note that on the public CI, the tests are running with a higher tolerance than what is written in the scripts:
- times 4 with a non debug kernel config (0.8s here with this test)
- times 10 with a debug kernel config (2s here with this test)

Reproduced quite regularly these last days on the public CI:
- [summary](https://api.cirrus-ci.com/v1/artifact/task/4828720966926336/summary/summary.txt) - [task](https://cirrus-ci.com/task/4828720966926336)
- [summary](https://api.cirrus-ci.com/v1/artifact/task/5652247928373248/summary/summary.txt) - [task](https://cirrus-ci.com/task/5652247928373248)
- [summary](https://api.cirrus-ci.com/v1/artifact/task/5473372170616832/summary/summary.txt) - [task](https://cirrus-ci.com/task/5473372170616832)
- [summary](https://api.cirrus-ci.com/v1/artifact/task/6036322124038144/summary/summary.txt) - [task](https://cirrus-ci.com/task/6036322124038144)
- [summary](https://api.cirrus-ci.com/v1/artifact/task/6536734736384000/summary/summary.txt) - [task](https://cirrus-ci.com/task/6536734736384000)
- [summary](https://api.cirrus-ci.com/v1/artifact/task/5904508302655488/summary/summary.txt) - [task](https://cirrus-ci.com/task/5904508302655488)
- [summary](https://api.cirrus-ci.com/v1/artifact/task/5452558155120640/summary/summary.txt) - [task](https://cirrus-ci.com/task/5452558155120640)
- [summary](https://api.cirrus-ci.com/v1/artifact/task/6015508108541952/summary/summary.txt) - [task](https://cirrus-ci.com/task/6015508108541952)

**Comment by matttbe** [comment]
Less regularly, the "server" test fails as well

```
# FAIL [/opt/packetdrill/gtests/net/mptcp/add_addr/add_addr4_server.pkt (ipv6)]
# stdout: 
# stderr: 
# add_addr4_server.pkt:20: error handling packet: timing error: expected outbound packet at 7.925402 sec but happened at 14.886888 sec; tolerance 2.000000 sec
# script packet:  7.925402 . 1:1(0) ack 1 <add_address address_id: 1 ipv4: 198.51.100.2 hmac: 4866319833858278738>
# actual packet: 14.886888 . 1:1(0) ack 1 win 256 <add_address address_id: 1 ipv4: 198.51.100.2 hmac: 4866319833858278738>
```

This one is more surprising because the ADD_ADDR is supposed to be sent just after the accept and here it is sent a very long time after! (debug kernel config)

- [summary](https://api.cirrus-ci.com/v1/artifact/task/5459989220294656/summary/summary.txt) - [task](https://cirrus-ci.com/task/5459989220294656)

**Comment by pabeni** [comment]
It looks like the root cause is the CI being very slow, so that:

<event starting the timeout, at time t=0>
<next event expected t=0, arriving at t=~tolerance && t< tolerance, ok>
<another event, expected t=tolerance (prev. event time), arriving at t=~2*tolerance && t< 2*tolerance, ok>
<add_add retransmission, expected at t=1s+2*tolerance (prev event time plus drill time) , correctly arriving in any time in the range [~1s, ~1s+tolerance], error>

No idea how to fix it...

**Comment by pabeni** [comment]
a possible fix would be replacing

```+1 <timeout pkt>```

with:

``` +0.9~+1.0 <timeout pkt> ```

and adjust the latter with the current tolerance with sed, before starting the script

(With the assumption that the timeout must be greater then the tolerance)

**Comment by matttbe** [comment]
This PR should help to reduce the false positives seen by the CI: https://github.com/multipath-tcp/packetdrill/pull/98
