### ISSUE TITLE
Add netlink events for listening socket create/close

### ISSUE THREAD

**Issue by mjmartineau** [multipath-tcp/mptcp_net-next#313]
MPTCP for Linux, when not using the in-kernel PM, depends on the userspace PM to create extra listening sockets before announcing addresses and ports. Let's call these "PM listeners".

With the existing MPTCP netlink events, a userspace PM can create PM listeners at startup time, or in response to an incoming connection. Creating sockets in response to connections is not optimal: ADD_ADDRs can't be sent until the sockets are created and `listen()`ed, and if all connections are closed then it may not be clear to the userspace PM daemon that PM listener sockets should be cleaned up.

Hence this feature request: to add MPTCP netlink events for listening socket close & create, so PM listening sockets can be managed based on application activity.

**Comment by geliangtang** [comment]
@mjmartineau Mat, if no one is looking at this yet, I'm willing to do it. Please assign this issue to me.

**Comment by mjmartineau** [comment]
Sure, thanks @geliangtang!

**Comment by matttbe** [comment]
The new feature has been added by Geliang:

New patches for t/upstream:
- a6871c7e014a: mptcp: add pm listener events
- 4aabc20960d4: selftests: mptcp: enhance userspace pm tests
- 83027c9e1d0c: selftests: mptcp: listener test for userspace PM
- e33052bbf56f: selftests: mptcp: listener test for in-kernel PM
- Results: 48478f54612d..077c54d47661 (export)

- e9fa9c5f6951: tg:msg: events are for any MPTCP listener socket
- Results: 077c54d47661..69720c6cd168 (export)

Tests are now in progress:

https://cirrus-ci.com/github/multipath-tcp/mptcp_net-next/export/20221118T102434
