### ISSUE TITLE
PM: userspace: update `MPTCP_INFO` fields

### ISSUE THREAD

**Issue by matttbe** [multipath-tcp/mptcp_net-next#329]
Somehow linked to #327, some fields from `MPTCP_INFO` are not updated by the userspace PM, e.g. `mptcpi_subflows` (after a quick look, it seems we only decrement it.)

Probably other fields linked to the PM are not updated:
- `add_addr_signaled`
- `add_addr_accepted`
- `local_addr_used`

**Comment by geliangtang** [comment]
Matt, is anyone looking at this? If not, I can do it.

**Comment by matttbe** [comment]
@geliangtang AFAIK, nobody is looking into it. Thanks!

Note that when I looked at #327, I only looked at `mptcpi_subflows` counter. Probably others are not updated.

Also this counter is not updated for the server side if I'm not mistaken. But there is another ticket for that: #330
