### ISSUE TITLE
netlink: switch to YAML Netlink specs

### ISSUE THREAD

**Issue by matttbe** [multipath-tcp/mptcp_net-next#340]
This is linked to [Jakub](https://lore.kernel.org/all/20230120175041.342573-1-kuba@kernel.org/) series and his [presentation at LPC2022](https://youtu.be/9QkXIQXkaQk?t=2562).

The specs are defined in YAML to help on different topics.

**Comment by dcaratti** [comment]
it seems that we are using "global" policy, but ops use (at least)  2 different  attribute-sets. In the RFC post [1] I was defaulting everything to "attr". In this way, the code generated from yaml spec is the same as what we have in the current "export" branch; however, it would be better to convert to `per-op` first, and then use a yaml spec that doesn't specify "global". In this way, we would have more accurate validation

[1] https://lore.kernel.org/mptcp/cb2ed01dd8797078c39c014e8c19eab5ddf1f0f2.1680801697.git.dcaratti@redhat.com/
