### ISSUE TITLE
scheduler: area in the socket structures reserved for schedulers

### ISSUE THREAD

**Issue by matttbe** [multipath-tcp/mptcp_net-next#342]
A packet scheduler needs to save some data at MPTCP **and** subflows levels, e.g. to "penalise" one subflow over another, to remember when an optimisation or check was done last not to do it too frequently, etc.

A refactoring is probably needed not to increase the sizes too much.

**Comment by geliangtang** [comment]
This issue can be closed now by "v11, BPF packet scheduler updates part 1" (https://patchwork.kernel.org/project/mptcp/cover/cover.1687827857.git.geliang.tang@suse.com/).

**Comment by matttbe** [comment]
@geliangtang thank you for your reply and patches!

Closing then.

- 8efabdbcaa2c: "squashed" patch 1/11 (with conflicts) in "mptcp: drop
last_snd and MPTCP_RESET_SCHEDULER"
- b0f6d5c5ae25: "squashed" patch 1/11 (with conflicts) in "mptcp: use
get_send wrapper"
- 9de04aa46c59: "squashed" patch 1/11 in "mptcp: use get_retrans wrapper"
- Results: e77e1cb5a372..3fcf166a9c7e (export)

- 6e930aa67c6e: "squashed" patch 2/11 in "mptcp: add struct mptcp_sched_ops"
- Results: 3fcf166a9c7e..437c8b684629 (export)

- f7e28c2443da: "squashed" patch 3/11 (with conflicts) in "mptcp: add
sched_data_set_contexts helper"
- 9dc7c0042a01: conflict in t/mptcp-add-scheduler-wrappers
- Results: 437c8b684629..504bc1f2d42d (export)

- Applied patch 4/11 with Paolo's ACK just before "bpf: Add
bpf_mptcp_sched_ops"
- 7f44744d88c6: mptcp: register default scheduler
- Results: 504bc1f2d42d..d45b69d4109b (export)

- 0c323c5cc341: "squashed" patch 5/11 in "bpf: Add bpf_mptcp_sched_ops"
- Results: d45b69d4109b..1b64ad359430 (export)

- 9ffacd26fad5: "squashed" patch 6/11 in "bpf: Add
bpf_mptcp_sched_kfunc_set"
- Results: 1b64ad359430..f95ddf57fd7e (export)

- 8f050b24bd4d: "squashed" patch 7/11 in "selftests/bpf: Add mptcp sched
structs"
- Results: f95ddf57fd7e..b1bfdcd53258 (export)

- a3eacd00bfb7: "squashed" patch 8/11 in "selftests/bpf: Add bpf_first
scheduler"
- Results: b1bfdcd53258..b80981f0543b (export)

- bc7512c33473: "squashed" patch 9/11 in "selftests/bpf: Add bpf_bkup
scheduler"
- Results: b80981f0543b..e1dbf174936b (export)

- 506feec3a419: "squashed" patch 10/11 in "selftests/bpf: Add bpf_rr
scheduler"
- Results: e1dbf174936b..c6edb7e5168c (export)

- 151a85fd02ab: "squashed" patch 11/11 in "selftests/bpf: Add bpf_red
scheduler"
- Results: c6edb7e5168c..679a4538b06c (export)

- 064c5746a0d9: "squashed" patch 12/11 (squash squash) in
"selftests/bpf: Add bpf_rr scheduler"
- Results: 679a4538b06c..255b06daaf0d (export)

- cebedb75ff65: "squashed" patch 6/7 from BPF 'force to MPTCP' v4 series
in "selftests/bpf: add two mptcp netns helpers"
- Results: 255b06daaf0d..cde4fa6a0a5e (export)
