### ISSUE TITLE
Userspace PM in 5.15 LTS

### ISSUE THREAD

**Issue by virus-atl** [multipath-tcp/mptcp_net-next#351]
Hello, i have question.  It's possible backport userspace PM from upstream kernel version to 5.15?
OS for embedded devices, use LTS kernels and mptcp in-kernel pm not suitable for long sessions because subflows is closed for network conditions and not reistablish.

**Comment by matttbe** [comment]
Hello,

Unfortunately, it is not possible to backport the userspace PM to earlier versions:
- only bug fixes can be backported
- we don't control the stable process: https://www.kernel.org/doc/html/latest/process/stable-kernel-rules.html

The best for you would be to switch to the next LTS (6.1).

> mptcp in-kernel pm not suitable for long sessions because subflows is closed for network conditions and not reistablish.

Is it something visible with the latest stable kernel?
Maybe that's a behaviour that can be changed. And if this is a fix, it could be backported.

(and maybe your issue could be prevented by using TCP KeepAlive?)

**Comment by virus-atl** [comment]
> The best for you would be to switch to the next LTS (6.1).

For various reasons, this is currently not possible.

> Is it something visible with the latest stable kernel?
Maybe that's a behaviour that can be changed. And if this is a fix, it could be backported.

Kernel version 5.15.92 situation.

We have 3 interfaces A & B & C. Mptcp connect M with 3 subflows from A & B & C.
After some time subflow from B is closed by network reason, now connection M have 2 subflows from A & C. Subflow from B never reistablish.

It's possible to reanimate subflow from B?

**Comment by matttbe** [comment]
> > Is it something visible with the latest stable kernel?
> > Maybe that's a behaviour that can be changed. And if this is a fix, it could be backported.
> 
> Kernel version 5.15.92 situation.

Do you mind trying to reproduce this issue on either by using (by preference order):
- the `export` branch (or `export-net`)
- the last RC from Linus (6.2-rc7)
- The last stable (6.1)

Previous versions are too old (dev from more than one year ago) and it is difficult for us to work with them.

This is not specific to MPTCP, see [docs.kernel.org](https://docs.kernel.org/admin-guide/reporting-issues.html?highlight=lts#reference-for-reporting-regressions-within-a-stable-and-longterm-kernel-line).

> We have 3 interfaces A & B & C. Mptcp connect M with 3 subflows from A & B & C. After some time subflow from B is closed by network reason, now connection M have 2 subflows from A & C. Subflow from B never reistablish.
> 
> It's possible to reanimate subflow from B?

Probably but it depends on the issue.

> subflow from B is closed by network reason

How is it closed exactly? Timeout? Reset?

**Comment by virus-atl** [comment]
> Do you mind trying to reproduce this issue on either by using (by preference order):
    the export branch (or export-net)
    the last RC from Linus (6.2-rc7)
    The last stable (6.1)

Test 6.1 on VM all ok. But unfortunately i can't use 6.1 on embedded device now.

Temporarily have to use Out-of-tree 0.96 version.

Thanks for answers.

**Comment by matttbe** [comment]
Thank you for having tested on v6.1.

You can always backport stuff on your side.
Maybe you need something like:

```
  mptcp: fix per socket endpoint accounting
  mptcp: clean-up MPJ option writing
  mptcp: keep track of local endpoint still available for each msk
  mptcp: do not block subflows creation on errors
  selftests: mptcp: add tests for subflow creation failure
  mptcp: fix local endpoint accounting
```
