### ISSUE TITLE
`getsockopt(SOL_MPTCP, ...)` on a MPTCP->TCP fallback connection returns `EOPNOTSUPP` in IPv4 and `ENOPROTOOPT` in IPv6

### ISSUE THREAD

**Issue by matttbe** [multipath-tcp/mptcp_net-next#358]
When doing a `getsockopt(SOL_MPTCP, MPTCP_INFO)` on a MPTCP connection that fell back to TCP, I noticed the returned error is different if the socket is in IPv4 or IPv6:
- `EOPNOTSUPP` is returned in IPv4
- `ENOPROTOOPT` is returned in IPv6

In fact, we have the same behaviour with "plain" TCP:

```python
>>> import socket
>>> s = socket.socket(socket.AF_INET, socket.SOCK_STREAM, socket.IPPROTO_TCP)
>>> s.getsockopt(284, 1)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
OSError: [Errno 95] Operation not supported
>>> s = socket.socket(socket.AF_INET6, socket.SOCK_STREAM, socket.IPPROTO_TCP)
>>> s.getsockopt(284, 1)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
OSError: [Errno 92] Protocol not available
```

That's because IPv4 returns explicitly `EOPNOTSUPP`:

https://github.com/multipath-tcp/mptcp_net-next/blob/e9ab2559e2c501593c58a02a956a6005a2a749fb/net/ipv4/ip_sockglue.c#L1551-L1552

While IPv6 returns `ENOPROTOOPT`:

https://github.com/multipath-tcp/mptcp_net-next/blob/e9ab2559e2c501593c58a02a956a6005a2a749fb/net/ipv6/ipv6_sockglue.c#L1486-L1487

FYI, on the `setsocktopt()` side, the error is `ENOPROTOOPT` in both v4 and v6:

https://github.com/multipath-tcp/mptcp_net-next/blob/e9ab2559e2c501593c58a02a956a6005a2a749fb/net/ipv4/ip_sockglue.c#L1445-L1446

https://github.com/multipath-tcp/mptcp_net-next/blob/e9ab2559e2c501593c58a02a956a6005a2a749fb/net/ipv6/ipv6_sockglue.c#L1008-L1009

Do we want to uniform this for MPTCP with something like:

```diff
diff --git a/net/mptcp/sockopt.c b/net/mptcp/sockopt.c
index f7842a0b6536..712ca3975c26 100644
--- a/net/mptcp/sockopt.c
+++ b/net/mptcp/sockopt.c
@@ -1239,8 +1239,13 @@ int mptcp_getsockopt(struct sock *sk, int level, int optname,
        lock_sock(sk);
        ssk = __mptcp_tcp_fallback(msk);
        release_sock(sk);
-       if (ssk)
+       if (ssk) {
+               /* Make sure the same errno is returned in v4 and v6 */
+               if (level == SOL_MPTCP)
+                       return -EOPNOTSUPP; // or ENOPROTOOPT
+
                return tcp_getsockopt(ssk, level, optname, optval, option);
+       }
 
        if (level == SOL_IP)
                return mptcp_getsockopt_v4(msk, optname, optval, option);
```

Mainly interesting for #294 (I just updated the example code in this ticket to support v6).

* On one hand, it would be good to have the same error in case of fallback 
* On the other hand, if we take the case of a server receiving a SYN was without MPTCP options, the accepted socket will be in plain TCP: a `getsockopt()` will talk to the TCP stack directly, no more to the MPTCP one
  * either we patch TCP when `SOL_MPTCP` level is received (doesn't sound good, no?)
  * or we keep the current behaviour with IP → but then it is not fully uniformed

**Comment by pabeni** [comment]
Note that changing the error code could break existing user-space (tests), see:

8ccc99362b60c6f27bb46f36fdaaccf4ef0303de

That is possibly less relevant for MPTCP, but likely much more for plain TCP.

**Comment by matttbe** [comment]
Indeed, probably too late then? It could be considered as a bug-fix but...

Also if we want to change it, we would probably need to adapt TCP code to return something if level is `SOL_MPTCP`, just two line in a non fast path but I don't know if it would be OK.

We can always say we have the same (weird) behaviour as on the IPv4/IPv6 stacks and that's OK?

**Comment by matttbe** [comment]
As discussed at the last meeting: we can close this and keep the current (weird) behaviour as on the IPv4/IPv6 stacks.
