### ISSUE TITLE
selftests: skip tests not being supported by older kernels

### ISSUE THREAD

**Issue by matttbe** [multipath-tcp/mptcp_net-next#368]
Linked to this [discussion](https://lore.kernel.org/stable/04fccfd8-62ea-cd68-6d49-04a910004901@w6rz.net/T/#maffa9cfa03ccb884c5576c6969f0b7e1a9c7fc94).

Selftests are supposed to run on any kernels, including the old ones not supporting MPTCP.

**Comment by AlejandraOliver** [comment]
Hi, I am trying to run the selftests (https://github.com/multipath-tcp/mptcp_net-next/wiki/Testing) to check if MPTCP is working correctly. All the tests seem to be correct (OK) but is there any tool I can use to see the traffic on the virtual interfaces that create the tests by running mptcp_connect.sh, mptcp_join.sh, etc.?

**Comment by matttbe** [comment]
@AlejandraOliver please open a new ticket, your questions are unrelated with the issue here and it will create confusions if we reply to these questions here.
