### ISSUE TITLE
MPTCPv1 not working: Configuration issue with ip mptcp on Ubuntu 20.04.5 LTS using Mininet 2.3.0.dev6"

### ISSUE THREAD

**Issue by mrconter1** [multipath-tcp/mptcp_net-next#380]
Hi!

When testing single path, I get around 90 Mbps, but when using MPTCP, I expect double the throughput but only get about 86.3 Mbps. I am unsure about the proper configuration for ip mptcp in my scenario. Right now I am using the following:

| Name      | Version |
| ----------- | ----------- |
| Ubuntu      | 20.04.5 LTS       |
| Mininet   | 2.3.0.dev6        |
| Python  | Python 3.8.10       |
| Kernel  | 5.15.0-67-generic  (I'm using the built in MPTCP)    |
| iproute2  | Latest src code (for `ip mptcp`)      |

I have created a test framework which sets up the following:

![image](https://user-images.githubusercontent.com/32551374/226994984-1085c498-eff3-4224-bed5-d73e7ac5c3b0.png)

The code for which can be found [here](https://github.com/mrconter1/simple_mptcp):

* main.py - Initializes the topology and starts the client and server code on the nodes
* server.py - Waits for an incoming connection and replies with data
* client.py - Connects and receives data

The output from _main.py_ is:

```bash
--- Testing single path ---
net.mptcp.enabled = 0
Creating socket...
Using tcp...
Connecting to server...
Receiving data...
Total time: 8.959124565124512 seconds
Amount bytes received: 100000000 bytes
Actual throughput: 89.29 Mbps

--- Testing multipath ---
net.mptcp.enabled = 1
Creating socket...
Using mptcp...
Connecting to server...
Receiving data...
Total time: 9.270249843597412 seconds
Amount bytes received: 100000000 bytes
Actual throughput: 86.3 Mbps
```

The single path should be around 100 Mbps which it currently is. But I would expect MPTCP to be about double the throughput. I think most things are set up correctly but I am a bit unsure about how I am supposed to configure with `ip mptcp` in this scenario. Currently I am doing this:

```python
# Run final commands for enabling mptcp
h1.cmd("ip mptcp limits set subflow 2 add_addr_accepted 2")
h2.cmd("ip mptcp limits set subflow 2 add_addr_accepted 2")
h2.cmd("ip mptcp endpoint add 10.0.2.2 dev h2-eth0 subflow")
```

I'm pretty sure that it's not correct but I am not familiar enough to fix it. The previous snippet and the other network configurations can be found in the [main.py](https://github.com/mrconter1/simple_mptcp/blob/main/main.py) file.

Any help in identifying the issue and suggestions for proper `ip mptcp` configuration would be greatly appreciated.

Regards, Rasmus

**Comment by matttbe** [comment]
Hello,

Thank you for this bug report.

Before continuing, it is important to note that the v5.15 kernel is too old for us, there might be some features, bug fixes and optimisations missing, see our [ChangeLog](https://github.com/multipath-tcp/mptcp_net-next/wiki#changelog) (not all fixes can be backported).
We recommend to use at least the last stable LTS (v6.1 for the moment), ideally the last stable version (v6.2 for the moment) or even build the development version (our `export` branch or `net-next`).

On Ubuntu, the easiest is to install the last `linux-oem` package from the repository and reboot, e.g. `linux-oem-22.04c`
Or download .deb packages from https://kernel.ubuntu.com/~kernel-ppa/mainline/
Or build the kernel following Ubuntu doc about that.

------

Now regarding your configuration, it looks like you only added one endpoint to create subflows on `h2`: is `h2` the client or the server? (maybe better to call it `client` or `server`, clearer than `h1` and `h2` :) )

Typically, we create:
- one `signal` endpoint on the server side to announce another address
- one `subflow` one on the client side to create new subflows

With such configuration, the client will create one subflow to the second address announced by the server.

Would this help?

Note that you can also use the `fullmesh` flag (or the userspace PM with mptcpd for more flexibility)

**Comment by mrconter1** [comment]
Thank you for the quick reply! I can (and likely will) definitely upgrade to v6.1. But the problem would likely still be there due to it being a config problem. From what I can tell from your response the `ip mptcp limits` is likely correct, right? Regarding the server and client, the assignment is as follows:

<html>
<body>


Node | Variable Name
-- | --
Client | h1
Server | h2


</body>
</html>

The _h2-eth1_ is not supposed to be used in this setup so that can be ignored. From what you are telling me I understand it as I am supposed to create a signal on the server:

```python
h2.cmd("ip mptcp endpoint add 10.0.2.2 dev h2-eth0 signal")
```

and **one** (?) subflow on the client side (which interface?):

```python
h1.cmd("ip mptcp endpoint add 10.0.0.2 dev h1-eth0 subflow")
```

But there are two interfaces at the client (h1-eth0 and h1-eth1). Aren't I supposed to add one subflow per interface?

The traffic is supposed to flow between 

```
h1-eth0 <=> h2-eth0
h1-eth1 <=> h2-eth0
```

If that is the case I will try that and reach back to you. But I don't really understand what I am doing here.

Regards, Rasmus

**Comment by matttbe** [comment]
> From what I can tell from your response the `ip mptcp limits` is likely correct, right?

Likely yes (but if you have issues, always best to start with higher limit and then decrease them)

> But there are two interfaces at the client (h1-eth0 and h1-eth1). Aren't I supposed to add one subflow per interface?

You need to add endpoints for *additional* addresses you want to use. If your default route is going through `eth0`, then add an endpoint for the address linked to `eth1`.

(The client might need to add the flag `fullmesh` when adding the new `subflow` endpoint, to be tested)

**Comment by mrconter1** [comment]
Hm... I've been trying some more but I am still not managing to get it working. My Mininet network topology is as follows:

![image](https://user-images.githubusercontent.com/32551374/227281275-02a1361b-78de-483a-8480-2b3cd77c310d.png)

And this is my MPTCP configuration I am running before starting the test:

```python
# Configure server for MPTCP
h2.cmd("sysctl -w net.mptcp.enabled=1")
h2.cmd("ip mptcp limits set subflows 4 add_addr_accepted 4")
h2.cmd("ip mptcp endpoint add 10.0.2.2 dev h2-eth0 signal")

# Configure client for MPTCP
h1.cmd("sysctl -w net.mptcp.enabled=1")
h1.cmd("ip mptcp limits set subflows 4 add_addr_accepted 4")
h1.cmd("ip mptcp endpoint add 10.0.0.2 dev h1-eth0 fullmesh")
h1.cmd("ip mptcp endpoint add 10.0.1.2 dev h1-eth1 fullmesh")
```

It feels like I am really close now but I still only get around 90 Mbps throughput when sending over a 100 Mb file from the server to the client. It feels like I should get about **180 Mbps** due to the fact that I am supposedly using two paths?

Any idea what I am doing wrong?

**Comment by matttbe** [comment]
Hello,

With which kernel version?

> ```
> h1.cmd("ip mptcp endpoint add 10.0.1.2 dev h1-eth1 fullmesh")
> ```

You need to set both the fullmesh flag and the subflow one, not just `fullmesh`.

Do you have anything send on the second interface? (`tcpdump` / `wireshark`)
Any interesting MIB counter? `nstat` from the netns before and after a test (+ eventually `ss`?)

**Comment by mrconter1** [comment]
Thank you so much! I've been attempting to get this working for several weeks, if not months now. I cannot even count the number of times I've re-installed Ubuntu and tried different variants of dependencies. Now, the result looks like this:

![image](https://user-images.githubusercontent.com/32551374/227295279-b9726c20-f017-46a3-b664-f0e6193a5d46.png)

In other words... It **works**! I will create a set-up script for other people (for the Ubuntu v6.1) now when I got this up and running.  I truly appreciate your help.

**Comment by matttbe** [comment]
You are welcome!

I guess I can close the issue now.
