### ISSUE TITLE
Question: Different path manager rules for different MPTCP connections

### ISSUE THREAD

**Issue by Monika-Research** [multipath-tcp/mptcp_net-next#382]
Hi Team,

I would like to know if it is feasible to assign diffferent path manager rules for different MPTCP connections.

For example, assume there are two applications sending data using MPTCP from a system where there are four network interfaces. Is it possible to  assign 2 networks (paths) for one application and the other 2 for another application.
Basically I would like to have an instance of path manager for each MPTCP connection. 

Please let me know if this is possible?

Also, I am trying to understand the difference between mptcpd and ip-mptcp. It would be great if you can point out some main differences.

Thanks,
Monika

**Comment by matttbe** [comment]
Hello,

> I would like to know if it is feasible to assign diffferent path manager rules for different MPTCP connections.

Yes it is.

There are currently two path-managers (PM): in-kernel (default) and userspace

For the in-kernel PM, you set some rules for all the connection of the net namespace. You can then set multiple netns (`ip netns`, `docker`, etc.) and have different rules. These global settings can be modified via `ip mptcp` and `mptcpd` (and it's config file: `man mptcpd`).

For the userspace PM, the rules are handled by a userspace daemon that can take different rules per connections. If the corresponding sysctl is set, all the new connections from the same netns will be handled by a userspace daemon like `mptcpd`.

`mptcpd` can then handle global settings and per connection control.

(feel free to close this ticket if it answers the questions)

**Comment by matttbe** [comment]
Hi @Monika-Research,

Does my previous reply answered your questions? Can I close this ticket?

**Comment by Monika-Research** [comment]
Hi @matttbe, Yes.. its clear.. thank you
