### ISSUE TITLE
TCP_KEEPIDLE, TCP_KEEPINTVL, TCP_KEEPCNT are not implemented in mptcp_setsockopt_sol_tcp

### ISSUE THREAD

**Issue by zonyitoo** [multipath-tcp/mptcp_net-next#383]
These options are claimed "supported" in `mptcp_supported_sockopt`:

Kernel:
https://github.com/torvalds/linux/blob/76f598ba7d8e2bfb4855b5298caedd5af0c374a8/net/mptcp/sockopt.c#L549-L551

Master branch:

https://github.com/multipath-tcp/mptcp_net-next/blob/579883a38a7cab29a555390b9bd251a0a005bbf0/net/mptcp/sockopt.c#L549-L551

But not implemented in `mptcp_setsockopt_sol_tcp`:

Kernel:

https://github.com/torvalds/linux/blob/76f598ba7d8e2bfb4855b5298caedd5af0c374a8/net/mptcp/sockopt.c#L780-L819

Master branch:

https://github.com/multipath-tcp/mptcp_net-next/blob/579883a38a7cab29a555390b9bd251a0a005bbf0/net/mptcp/sockopt.c#L782-L821

Which will eventually lead to `EOPNOTSUPP` when calling `setsockopt` on these options:

```
setsockopt(13, SOL_SOCKET, SO_KEEPALIVE, [1], 4) = 0
setsockopt(13, SOL_TCP, TCP_KEEPIDLE, [15], 4) = -1 EOPNOTSUPP
setsockopt(13, SOL_TCP, TCP_KEEPINTVL, [15], 4) = -1 EOPNOTSUPP
```

Forther more, there are 24 options claimed to be "supported" in `mptcp_supported_sockopt`, but only 10 are implemented in `mptcp_supported_sockopt`.

**Comment by matttbe** [comment]
Hi @zonyitoo 

Thank you for this bug report!

> TCP_KEEPIDLE, TCP_KEEPINTVL, TCP_KEEPCNT are not implemented

Indeed, it is not implemented.

(It might be easier to do that after #353)

> Forther more, there are 24 options claimed to be "supported" in `mptcp_supported_sockopt`, but only 10 are implemented in `mptcp_supported_sockopt`.

`mptcp_supported_sockopt` is indeed a bit confusing. I personally read it as "_what might be supported (at some points)_".

**Comment by matttbe** [comment]
We forgot a bit about this (maybe because of #353).

It looks like supporting these socket options is needed for Go as well, see https://github.com/golang/go/issues/56539 + https://go-review.googlesource.com/c/go/+/563575
As discussed at the last meeting, supporting them should be easy and the patches could be seen as a "bug fix" somehow.
