### ISSUE TITLE
sockopt: `MPTCP_TCPINFO` and `MPTCP_SUBFLOW_ADDRS`: add a unique ID

### ISSUE THREAD

**Issue by matttbe** [multipath-tcp/mptcp_net-next#388]
From @ggreenway:

A piece of information that may be useful on `MPTCP_TCPINFO` is a way to identify each entry in the array or `tcp_info`  so that for a subflow, I can periodically poll `MPTCP_TCPINFO` and compute deltas for some metrics. 

For instance, if I had two subflows, and then sometime during the MPTCP connection the 0'th subflow is closed and a new one is created (so the array of `tcp_info` has two elements in both cases) being able to tell that they are not referring to the same two subflows between two calls to `MPTCP_TCPINFO`.

_Originally posted by @ggreenway in https://github.com/multipath-tcp/mptcp_net-next/issues/385#issuecomment-1499352968_

Note: we might want to do the same for `MPTCP_SUBFLOW_ADDRS`

**Comment by matttbe** [comment]
I guess we will need to add a new field in `struct mptcp_subflow_data` to let the userspace setting a flag/bit. If set, the kernel will add such ID before each `struct tcp_info` (or `struct mptcp_subflow_addrs`).

Each subflow (`struct mptcp_subflow_context`?) would have a unique ID, the `msk` would have a counter that is incremented each time a new subflow is added (and never decremented)

**Comment by matttbe** [comment]
Notes from the last meeting:

- might be easier to add a new sockopt but we might not want to have plenty sockopt each time we need to change something
- maybe OK to have a new sockopt with both TCP_INFO and ADDR + ID? (ID is optional then)
- BPF maybe?
- getsockopt:
  - add two new fields in mptcp_subflow_data: size for the kernel and userspace to be able to add more stuff per subflow, e.g. ID, status from MPTCP point of view, even addresses, etc.
```
    +       __u32           size_2_kernel;
    +       __u32           size_2_user;
```

**Comment by matttbe** [comment]
Idea from @fw-strlen: we could re-use a deprecated field from TCP_INFO, e.g. `tcpi_fackets` which has been removed in v4.15: 737ff314563c ("tcp: use sequence distance to detect reordering"). Maybe there are others.

For `MPTCP_SUBFLOW_ADDRS` it is less of an issue: we can easily increase `struct mptcp_subflow_addrs` because we control it.

**Comment by pabeni** [comment]
side note: it could be useful including the whole subflow related infos, as exposed by subflow_get_info(). Currently we can't reuse the existing code for that, as subflow_get_info() dumps such info in NL attributes, while getsockopt/MPTCP_TCPINFO should expose them as a binary struct. Plain TCP achieve that kind of code reuse dumping the whole tcp_info struct as a single NL attribute in tcp_get_info()

**Comment by matttbe** [comment]
@pabeni: just to be sure, what you mean is that for the info per subflow, we currently expose them using the `tcp_ulp_ops->get_info` hook calling `subflow_get_info()`. But the issue is that we cannot re-use `subflow_get_info()` on the `getsockopt(SOL_MPTCP, ...)` side because the output is formatted using different NL attributes, just just a single binary structure.

But I guess it is too late to change `subflow_get_info()`: we will at least need to maintain the existing version, no?

**Comment by pabeni** [comment]
> @pabeni: just to be sure, what you mean is that for the info per subflow, we currently expose them using the `tcp_ulp_ops->get_info` hook calling `subflow_get_info()`. But the issue is that we cannot re-use `subflow_get_info()` on the `getsockopt(SOL_MPTCP, ...)` side because the output is formatted using different NL attributes, just just a single binary structure.

yes

> But I guess it is too late to change `subflow_get_info()`: we will at least need to maintain the existing version, no?

Indeed. As such the situation is a bit problematic/suboptimal.
