### ISSUE TITLE
MPTCP Enviroment Set Up

### ISSUE THREAD

**Issue by AlejandraOliver** [multipath-tcp/mptcp_net-next#390]
Hi, 
I have downloaded the kernel from the export branch and compiled and loaded the different eBPF packet scheduler in the kernel with `clang` and `bpftool` tools. I have checked that it works by running the kselftest according to https://github.com/multipath-tcp/mptcp_net-next/wiki/Testing and they are all OK. I would like to ask if there is any tool to see the traffic in the different virtual interfaces that create the .sh of these tests to see the behavior of MPTCP. I need to have the .sh archives loading while I try to see the traffic?
************************************************************************
Also, I would like to set up a MPTCP scenario with two Ubuntu 22.04 virtual machines that are connected by internal network being a client and a server. Do I need the mptcpd daemon from https://github.com/multipath-tcp/mptcpd or just with the kernel running and the routing and schedulers configured is enough?

Thanks in advance!

**Comment by matttbe** [comment]
Hi @AlejandraOliver,

> I would like to ask if there is any tool to see the traffic in the different virtual interfaces that create the .sh of these tests to see the behavior of MPTCP. I need to have the .sh archives loading while I try to see the traffic?

Are the `.sh` you are mentioning the scripts from our kselftests? (from MPTCP `tools/testing/selftests/net/mptcp/`, not from BPF)

If yes, these scripts typically create net namespaces (netns) and generate traffic between them.
Most of them accept the `-c` option to create packet captures with `tcpdump`.

You can always modify these scripts to run extra commands from the different netns.

Be careful that when a new netns is created, you start using the default settings, not the ones you set on the host, e.g. the packet scheduler you are using.

Not all the selftests from BPF side create a netns. The one linked to MPTCP only do it for the base test, not the scheduler ones where a dedicated netns is not used.

> Also, I would like to set up a MPTCP scenario with two Ubuntu 22.04 virtual machines that are connected by internal network being a client and a server. Do I need the mptcpd daemon from https://github.com/multipath-tcp/mptcpd or just with the kernel running and the routing and schedulers configured is enough?

You don't need `mptcpd`, you can do the configuration manually with `ip`, etc.

`mptcpd` is there to automate things and provide additional features, mainly for the path manager with a userspace path manager daemon.

**Comment by AlejandraOliver** [comment]
Hi @matttbe ,

> Are the `.sh` you are mentioning the scripts from our kselftests? (from MPTCP `tools/testing/selftests/net/mptcp/`, not from BPF)

Yes, I refer to the test in tools/testing/selftests/net/mptcp/ but I don't see in which part they use the default scheduler. If I want to see the traffic with tcpdump -c, I need to have al the .sh compiling while I capture?

>You don't need mptcpd, you can do the configuration manually with ip, etc.

 I just need to select the scheduler and configure the routing (interfaces, endpoints, etc) and mptcp will work, in theory?

**Comment by matttbe** [comment]
> Hi @matttbe ,
> 
> > Are the `.sh` you are mentioning the scripts from our kselftests? (from MPTCP `tools/testing/selftests/net/mptcp/`, not from BPF)
> 
> Yes, I refer to the test in tools/testing/selftests/net/mptcp/ but I don't see in which part they use the default scheduler.

By creating a new network namespace (`ip netns add (...)`), the default values are used: the scheduler is then reset to the default one even if you set one before on the host

> If I want to see the traffic with tcpdump -c, I need to have al the .sh compiling while I capture?

Simply launch the scripts supporting that with the `-c` option, e.g.

    ./mptcp_join.sh -c
    ./mptcp_connect.sh -c

> > You don't need mptcpd, you can do the configuration manually with ip, etc.
> 
> I just need to select the scheduler and configure the routing (interfaces, endpoints, etc) and mptcp will work, in theory?

yes it will if you do the configuration manually.

**Comment by AlejandraOliver** [comment]
Ok, thank you for all!!

**Comment by matttbe** [comment]
I hope you don't mind if I close this ticket.
