### ISSUE TITLE
Compile and run mptcp bpf selftests in CI

### ISSUE THREAD

**Issue by geliangtang** [multipath-tcp/mptcp_net-next#406]
We need to add mptcp bpf selftests in CI together with other selftests too.

Compile bpf selftests:
`
cd tools/testing/selftests/bpf && make
` 

Run mptcp bpf selftests:
` 
./test_progs -t mptcp
`

**Comment by matttbe** [comment]
remaining task: integrate that in GitHub Action → I'm working on that.

**Comment by matttbe** [comment]
> remaining task: integrate that in GitHub Action → I'm working on that.

Done: 71a9e1d223e484148778e2549adbf18a6abecf8a
