### ISSUE TITLE
Compiling this kernel for Raspberry pi OS latest version

### ISSUE THREAD

**Issue by echofriend** [multipath-tcp/mptcp_net-next#409]
Hello all,
Can you please guide me to compiling this for the latest Raspberry pi OS which uses Linux Kernel v 6.1?

I desperately need help. Would appreciate it.

Thank you so much in advance!!

**Comment by matttbe** [comment]
Hi,

Sorry but this repo is about MPTCP implementation for the upstream (generic) Linux kernel, not specific to one vendor (Raspberry Pi).
In other words, I don't know what you have to do to recompile the kernel on Raspberry Pi OS.

(It looks like the OS you mentions has a [repo on GitHub](https://github.com/raspberrypi/linux/) and there is even an [issue to enable MPTCP](https://github.com/raspberrypi/linux/issues/4254))

**Comment by echofriend** [comment]
okay, but how do I compile it with the generic Kinux Kernel 6.1? Forget raspberry pi, I just need help compiling it with Linux Kernel v6.1
