### ISSUE TITLE
Compiling MPTCP v1 with Linux Kernel v6.1

### ISSUE THREAD

**Issue by echofriend** [multipath-tcp/mptcp_net-next#410]
Hello,
How do I compile the MPTCP v1 for Linux Kernel v6.1?

Which version of MPTCP should I merge with it?
Any instructions on the process?

Thanks,

**Comment by matttbe** [comment]
Hello,

Please do not open multiple tickets on the same subject. We can still continue discussions on a close ticket and even re-open it if needed. (#409)

> How do I compile the MPTCP v1 for Linux Kernel v6.1?

There is nothing specific to MPTCP, you just need to make sure the MPTCP config is enabled (`make menuconfig` step or similar). Note that if you use a recent distribution (Ubuntu >= 22.04, Fedora, Debian, Arch, RHEL, etc.), MPTCP will likely be already there.

If you still want to compile a Linux kernel, it is better to look at one of the many tutorials about that subject. A quick search points me to:
- https://www.kernel.org/doc/html/latest/admin-guide/quickly-build-trimmed-linux.html
- https://www.linux.com/topic/desktop/how-compile-linux-kernel-0/
- https://help.ubuntu.com/community/Kernel/Compile
- https://www.raspberrypi.com/documentation/computers/linux_kernel.html

> Which version of MPTCP should I merge with it?

I'm not sure what you are talking about, maybe:
- https://github.com/multipath-tcp/mptcp_net-next/wiki#upstream-vs-out-of-tree-implementations
- https://github.com/multipath-tcp/mptcp_net-next/wiki#mptcpv0-vs-mptcpv1

**Comment by matttbe** [comment]
I guess I can close this ticket. If you still have questions about that, please re-open it.
