### ISSUE TITLE
Question: Transport Converters for non-MPTCP end devices

### ISSUE THREAD

**Issue by Monika-Research** [multipath-tcp/mptcp_net-next#413]
Hi Matt,

I am looking for a transport converter solution to convert MPTCP to TCP or vice versa whenever required. I did have a look at MPTCP Proxy https://www.tessares.net/mptcp-proxy-setup-at-home-easier-now/. However the use case I am focusing on is different from a home proxy setup. 

My test setup:
A group of nodes with multiple radios and MPTCP enabled. These nodes are in a mesh network over multiple radios.
Any non-MPTCP node can connect to a multi-homed mesh node via software AP. In order enable communication between two non-MPTCP end device over a MPTCP enabled mesh network, I need a mechanism to convert TCP to MPTCP and vice versa.

UE (TCP) ------------MPTCP mesh network of nodes ------------UE (TCP)

Is there any 0-RTT solution available? I read the theory and found it applicable. However I couldn't find a develop repo.

Kindly advise what could be the best solution here?

Thanks,
Monika

**Comment by matttbe** [comment]
Hi Monika,

(I'm not the only one here ;-) )

> A group of nodes with multiple radios and MPTCP enabled. These nodes are in a mesh network over multiple radios.
> Any non-MPTCP node can connect to a multi-homed mesh node via software AP. In order enable communication between two non-MPTCP end device over a MPTCP enabled mesh network, I need a mechanism to convert TCP to MPTCP and vice versa.

So it looks like you want the MPTCP nodes to proxy the data, right? A proxy can be explicit (the client explicitly establishes a connection to a proxy "client") or transparent (a proxy client is on the way between the client and the server and it intercepts connections).

In the blog post you mentioned, an explicit proxy is used: shadowsocks. Shadowsocks can be used with TFO and then be a "0-RTT solution". You can use mptcpize to force it to use MPTCP but for the rest, you set it up like you would do with TCP, following the generic documentation.

Note that to use TFO with MPTCP connections, you need at least Linux 6.1 for the client part and 6.2 for the server part.

There are other 0-RTT solutions like 0-RTT Converter protocol: https://www.rfc-editor.org/rfc/rfc8803.html
There is an Open-Source library for the client side: https://github.com/Tessares/libconvert/
but not for the proxy backend side.

**Comment by matttbe** [comment]
I suggest to close this old ticket. Feel free to re-open it if needed.

**Comment by Monika-Research** [comment]
I could get this to work. Thank you.
