### ISSUE TITLE
remove unneeded branches in critical path

### ISSUE THREAD

**Issue by pabeni** [multipath-tcp/mptcp_net-next#42]
mptcp_write_options() has a lot of unneeded branch instruction (e.g. no need to check for all MPJ or DSS options if we already included MPC).

The above is somewhat related to #15: transform mptcp_out_options into an union will make explicit that some options could not be added into the same packet.

Likely other core functions should be audited.

**Comment by matttbe** [comment]
> The above is somewhat related to #15: transform mptcp_out_options into an union will make explicit that some options could not be added into the same packet.

Indeed. What's left to be done is the receive path which is "less urgent" (the structure is not used in all TCP packets)

**Comment by matttbe** [comment]
"Sadly", this #42 ticket can be closed thanks to @pabeni 's patches:

- 43bb18ab33aa: mptcp: do not set unconditionally csum_reqd on incoming opt
- a232edf92729: mptcp: better binary layout for mptcp_options_received
- 8b88edd207eb: mptcp: consolidate in_opt sub-options fields in a bitmask
- 2cea5d97a2ff: mptcp: optimize the input options processing
- Results: 720da4811476..6d620b4d8c2b

Builds and tests are now in progress:                                                                                               
                                                                                                                                    
https://cirrus-ci.com/github/multipath-tcp/mptcp_net-next/export/20210820T080437  
https://github.com/multipath-tcp/mptcp_net-next/actions/workflows/build-validation.yml?query=branch:export/20210820T08043
