### ISSUE TITLE
syzkaller: validate all MPTCP Netlink API

### ISSUE THREAD

**Issue by matttbe** [multipath-tcp/mptcp_net-next#425]
At today's weekly meeting, we were wondering if syzkaller was covering all/most of the MPTCP Netlink API. (cc @cpaasch)

At some points, there was apparently an "out of tree" syzkaller, is it still the case?

It looks like the only the in-kernel PM is covered ([PR from 2020](https://github.com/google/syzkaller/pull/1815)) but not the userspace PM:
- [socket_netlink_generic_mptcp.txt](https://github.com/google/syzkaller/blob/master/sys/linux/socket_netlink_generic_mptcp.txt)
- [socket_netlink_generic_mptcp.txt.const](https://github.com/google/syzkaller/blob/master/sys/linux/socket_netlink_generic_mptcp.txt.const)

It would be good to increase the test coverage.

**Comment by cpaasch** [comment]
Yes, didn't follow up on aligning syzkaller... 

Will get that done...

**Comment by matttbe** [comment]
@cpaasch : do you think we could close this one now that your PR has been accepted on Syzkaller side: https://github.com/google/syzkaller/pull/4172

**Comment by cpaasch** [comment]
Sure!
