### ISSUE TITLE
`mptcp_info`: expose if the initial subflow has been removed / total number of subflows

### ISSUE THREAD

**Issue by matttbe** [multipath-tcp/mptcp_net-next#428]
`mptcp_info` (`getsocktopt(SOL_MPTCP, MPTCP_INFO, ...)` or `ss -Mi`) currently exposes the number of **additional** subflows via the confusing `mptcpi_subflows` counter.

But if the initial subflow has been removed, we cannot know without checking other counters, e.g. `ss -ti <filter> | grep -c tcp-ulp-mptcp` or `getsockopt(SOL_MPTCP, MPTCP_FULL_INFO, ...)` (or others except `MPTCP_INFO` of course) and then check `mptcp_subflow_data->num_subflows` to get the total amount of subflows.

It sounds interesting to add a new flag in `mptcpi_flags` to know if the initial subflow is still there. With that bit, we can then compute the total amount of subflows from `mptcp_info` by doing something like `mptcpi_subflows + mptcpi_flags & MPTCP_INFO_FLAG_HAS_INITIAL_SUBFLOW`.

EDIT: mmh, we also need a way to know if this flag is supported by the kernel or not otherwise we would compute the wrong amount of subflows on older kernels. So either we have two flags (`WITH` / `WITHOUT` initial subflow) or a new counters (`mptcpi_total_subflows`). Maybe if there is a new counter, it makes it a bit clearer that `mptcpi_subflows` is not necessary the total number of subflows)

**Comment by geliangtang** [comment]
Matt, I can take a look at this issue.
