### ISSUE TITLE
Missing close transition

### ISSUE THREAD

**Issue by matttbe** [multipath-tcp/mptcp_net-next#429]
When the remote (server) rsyncd process dies for some reason (likely a momentary storage issue):
```
2023/08/10 23:33:59 [3311591] [sender] io timeout after 901 seconds -- exiting
2023/08/10 23:33:59 [3311591] sent 7346976492 bytes  received 540439 bytes  total size 12574925000
2023/08/10 23:33:59 [3311591] rsync error: timeout in data send/receive (code 30) at io.c(197) [sender=3.2.3]
```
The corresponding client rsync does not seem to get the hint and hangs around indefinitely:
```
client # sudo ss -neimMtp | grep aeab9cf3 -B1
mptcp ESTAB 190592 0                 10.29.20.251:43430         10.25.20.251:873   users:(("rsync",pid=1750778,fd=4),("rsync",pid=1750753,fd=4)) ino:74059654 sk:7247 cgroup:unreachable:1 <->
	 skmem:(r190592,rb536870912,t0,tb14155776,f3464,w632,o0,bl0,d0) add_addr_signal:2 subflows_max:4 add_addr_signal_max:2 add_addr_accepted_max:4 remote_key token:aeab9cf3 write_seq:e9ac43dae6a3d01 snd_una:e9ac43dae6a3b09 rcv_nxt:5976acb55351092b 
```
So it looks like the two expected TCP connections have gone but the mptcp connection is still open? And this in turn is holding open the rsync process such that it never quits or times out.

_Originally posted by @daire-byrne in https://github.com/multipath-tcp/mptcp_net-next/issues/427#issuecomment-1674549001_

**Comment by matttbe** [comment]
Note that @pabeni already posted patches fixing this issue, see [patchwork](https://patchwork.kernel.org/project/mptcp/patch/fbfa573423eaf6692eaf4a14a840cc18722c7332.1692779220.git.pabeni@redhat.com/). Thank you for that!


@daire-byrne: if you are OK with that, do you mind replying to this patch on the [mailing list](https://lore.kernel.org/mptcp/fbfa573423eaf6692eaf4a14a840cc18722c7332.1692779220.git.pabeni@redhat.com/) with this in your message please? 

```
(...)

Reported-by: NAME <EMAIL>
Closes: https://github.com/multipath-tcp/mptcp_net-next/issues/429

(...)
```

And even `Tested-by: NAME <EMAIL>` if you want to.

(see the instructions at the bottom on [lore](https://lore.kernel.org/mptcp/fbfa573423eaf6692eaf4a14a840cc18722c7332.1692779220.git.pabeni@redhat.com/) to import the email if you are not already subscribed to the ML)

**Comment by matttbe** [comment]
(I just updated the links of my previous message to point to the v2 ; no behaviour changes between v1 and v2 so OK to test only the v1)

**Comment by daire-byrne** [comment]
So, I have not yet caught an instance of this happening under normal production operation yet (with patch), but we did see some hanging when somebody accidentally rebooted one of our transfer servers.

So a server running rsyncd processes was rebooted while multiple "client" hosts had active rsync processes to it. On nearly all those hosts, rsync was in the state described in this ticket - the tcp connections were gone but the mptcp connection was hanging around and holding the rsync command open.

I also had one client rsync from exactly the same time stuck in the initial connect and MPTCP-SYN was the only entry in the output of "ss".

I'm going to try run some more tests killing the server's rsyncd processes and/or rebooting servers to see if it is reproducible.

Again, this is not normal operation for us and may be a different issue to the one described here (but with the same result)?

**Comment by pabeni** [comment]
Thanks for the feedback!

> So a server running rsyncd processes was rebooted while multiple "client" hosts had active rsync processes to it. On nearly all those hosts, rsync was in the state described in this ticket - the tcp connections were gone but the mptcp connection was hanging around and holding the rsync command open.
> 
> I also had one client rsync from exactly the same time stuck in the initial connect and MPTCP-SYN was the only entry in the output of "ss".

Just to be sure I'm on the same page:
* the server [unexpectedly] rebooted.
* many mptcp connections were stuck, with no TCP socket paired
* one of such connection was in  [MP]TCP-SYN state

what about the state of the other stuck mptcp connections? unknown?

> Again, this is not normal operation for us and may be a different issue to the one described here (but with the same result)?

Yes, this *feels* like a different issue - even if more investigation is needed on my side.

**Comment by matttbe** [comment]
> So a server running rsyncd processes was rebooted while multiple "client" hosts had active rsync processes to it. On nearly all those hosts, rsync was in the state described in this ticket - the tcp connections were gone but the mptcp connection was hanging around and holding the rsync command open.

Thank you for reporting this!

I wonder how the different subflows got killed: timeout? Maybe helped by TCP KeepAlive feature? Maybe we don't correctly react when the last subflow is terminated by an error (timeout).

**Comment by matttbe** [comment]
@daire-byrne we discussed about this issue with @pabeni on IRC and Paolo confirmed it is a different issue: #430

**Comment by daire-byrne** [comment]
I still have not seen any instances of this in the wild with the v1 patch. I'll wait until next week and then will happily add my thumbs up to the mailing list patch post.
