### ISSUE TITLE
[syzkaller] Change syzkaller to exercise MPTCP inet_diag interface

### ISSUE THREAD

**Issue by cpaasch** [multipath-tcp/mptcp_net-next#43]
Need to make sure that syzkaller is able to generate netlink-calls that are exercising the new inet-diag interface.

**Comment by matttbe** [comment]
(unassigning Christoph as discussed last week)

**Comment by matttbe** [comment]
@cpaasch did you not modify syzkaller to support that? Or maybe it was only the Netlink interface for the PM? (just to know if we should close the ticket or not)

**Comment by cpaasch** [comment]
Can be closed.
