### ISSUE TITLE
`MPTcpExtMPCapableFallbackACK` - looks surprising

### ISSUE THREAD

**Issue by cpaasch** [multipath-tcp/mptcp_net-next#449]
It seems to me like `MPTcpExtMPCapableFallbackACK` is counted even for pure TCP-connections. I think that's confusing:

```
$ nstat MPTcp*
#kernel
MPTcpExtMPCapableSYNRX          4733564            0.0
MPTcpExtMPCapableSYNTX          2260               0.0
MPTcpExtMPCapableSYNACKRX       2260               0.0
MPTcpExtMPCapableACKRX          2437595            0.0
MPTcpExtMPCapableFallbackACK    463149275          0.0
```

Could we increment that counter only if we actually received a SYN with MP_CAPABLE ?

**Comment by matttbe** [comment]
Hi @cpaasch,

Thank you for the bug report!

We just discussed about that at our weekly meeting and it looks like a bug. Just to be sure, do you mean that this is the view of the "server" side: so we have an MPTCP socket and the counter is incremented for accepted SYN that didn't have any MPTCP options?

**Comment by cpaasch** [comment]
Yes, this is server-side. And it looks like the counter gets incremented for incoming "pure" SYN.
