### ISSUE TITLE
Sparse issues (`make C=1`)

### ISSUE THREAD

**Issue by matttbe** [multipath-tcp/mptcp_net-next#46]
Hello,

When I use `make C=1 net/mptcp/<file>.c`, I guess two errors:

* `net/mptcp/mptcp_diag.c`:
```
./include/net/sock.h:1612:31: warning: context imbalance in 'mptcp_diag_get_info' - unexpected unlock
```
* `net/mptcp/protocol.c`:
```
net/mptcp/protocol.c:1531:24: warning: context imbalance in 'mptcp_sk_clone' - unexpected unlock
```

Is it really an issue? If not, is there a way to add something to avoid them?

**Comment by pabeni** [comment]
both this warning are due to core TCP APIs.

unlock_sock_fast() conditionally releases the socket lock, fooling sparse

sk_clone_lock() conditionally acquires the socket lock, (if return value != 0), so we can't annotate the caller as 'release'. Again, sparse is fooled.
