### ISSUE TITLE
Add `MPTCP_MIB_CURRESTAB` similar to TCP

### ISSUE THREAD

**Issue by cpaasch** [multipath-tcp/mptcp_net-next#460]
For operations it is useful to have this information easily accessible.

**Comment by geliangtang** [comment]
@cpaasch @matttbe Hi, I can add this feature.

**Comment by matttbe** [comment]
@geliangtang thank you!

Please note that we quickly talked about that at the last meeting (I still need to send the minutes (and reviews many patches)... :'( ):

- In the fork, it was done by modifying TCP code:
https://github.com/multipath-tcp/mptcp/commit/b0b64e79bff79aaeefba51d90d6f24b90d458d65
- Likely not OK to do that in the upstream version, we should do that on MPTCP side
- Best here to create a new mptcp_set_state() and do this check there, then calling `inet_sk_state_store()`
- The rest would be the same: if we switch from/to ESTABLISH state, we increment/decrement a new counter.
