### ISSUE TITLE
CI: switch to virtme-ng

### ISSUE THREAD

**Issue by matttbe** [multipath-tcp/mptcp_net-next#472]
`virtme` is no longer maintained. `virtme-ng` bring many new features, fixes and is quicker (e.g. using virtiofs, init script, microvm, etc.) and it is also used by the new Netdev CI.

**Comment by geliangtang** [comment]
Matt, I can assist you in implementing this.

**Comment by matttbe** [comment]
@geliangtang thank you for this suggestion.

I started to look at it, I have some uncommited code. I will try to look at it this week and share code. Then we can see what can be done from there if that's OK.
