### ISSUE TITLE
A hypothesis

### ISSUE THREAD

**Issue by birdofprey** [multipath-tcp/mptcp_net-next#478]
> **一种假设**
>
> 能不能提供一种检测机制，当主机网络在多出口到达对端时自动切换到mptcp协议，当主机网络只有单个出口时退化到传统tcp,另外UDP能实现类似MPTCP的功能吗？

Edited by @matttbe:

Translation from Google:

Can you provide a detection mechanism that automatically switches to the mptcp protocol when the host network reaches the peer with multiple exits? It degrades to traditional tcp when the host network has only a single exit. In addition, can UDP realize functions similar to MPTCP?

**Comment by matttbe** [comment]
Hi,

Similar to the `multipath-tcp/mptcp` repo where you already opened [an issue](https://github.com/multipath-tcp/mptcp/issues/401), the content should be exclusively in English.

**Comment by geliangtang** [comment]
Please ask questions in English, this is a good opportunity for you to practice your English. Next time, I will simply ignore questions like this. Even if you ask it in Chinese, your description of the question is very inaccurate, giving me a feeling that you are very casual. We are all developers of MPTCP, and we expect to answer those accurate questions from serious questioners. We hope that the questioners have a basic understanding of MPTCP and have at least read the WIKI page. [1]

Now back to your question, "A hypothesis".

The first question is about switching between TCP and MPTCP. I don't understand your intention, but the general answer is:

Establishing an MPTCP connection requires three handshakes, just like TCP. If the handshake fails, it will fall back to a TCP connection. [2]

Legacy TCP applications can switch to MPTCP through the mptcpize tool or BPF. [3]

The second question is about so-called "multipath UDP", please refer to mp-dccp. We do not intend to discuss it here. [4]

[1] https://github.com/multipath-tcp/mptcp_net-next/wiki
[2] https://www.rfc-editor.org/rfc/rfc8684.html
[3] https://github.com/multipath-tcp/mptcp_net-next/issues/79
[4] https://multipath-dccp.org

**Comment by matttbe** [comment]
Hello

I guess it is fine to close this ticket, right? I think @geliangtang replied to all questions (thanks!).
If not, please re-open the issue.
