### ISSUE TITLE
ADD_ADDR: echo bit support

### ISSUE THREAD

**Issue by matttbe** [multipath-tcp/mptcp_net-next#49]
The current implementation supports the send and reception of `ADD_ADDR` (v1) but not in a reliable way: the receiver is supposed to send the same ADD_ADDR back with the `echo` bit set to 1. If it is not received after some time, the sender can send it again.

As specified in RFC8684: https://www.rfc-editor.org/rfc/rfc8684.html#sec_add_address

> The "E" flag exists to provide reliability for this option. Because this option will often be sent on pure ACKs, there is no guarantee of reliability. Therefore, a receiver receiving a fresh ADD_ADDR option (where E=0) will send the same option back to the sender, but not including the HMAC and with E=1, to indicate receipt. According to local policy, the lack of this type of "echo" can indicate to the initial ADD_ADDR sender that the ADD_ADDR needs to be retransmitted.

https://www.rfc-editor.org/rfc/rfc8684.html#section-3.4.1-9

For the moment, `ADD_ADDR` with the echo bit are ignored. Potentially, a host could retransmit the `ADD_ADDR` indefinitely because the current version don't send the ACK. It might be interesting to stop the retransmission once the address is used, after a number of retransmissions, etc.
→ To be validated with a version of the upstream kernel not sending the ACK (ADD_ADDR with the echo bit).

(Feature from the initial roadmap)

**Comment by mjmartineau** [comment]
@pkrystad Do you want to stay assigned on this one?

**Comment by matttbe** [comment]
@geliangtang just told me he is going to look at that.

**Comment by matttbe** [comment]
Implemented by @geliangtang and now on net-next, thx! → a1a35529bdf8f0d5da0f9ae10a670fb0ad7df2d3
This ticket can then be closed!
