### ISSUE TITLE
Test and Add MPTCP Schedulers

### ISSUE THREAD

**Issue by tiagojoseas** [multipath-tcp/mptcp_net-next#522]
Hello,
Not really a issue, but more of opinion question, I am currently doing my dissertation and i am trying to test the different schedulers and trying to implement my own. For what i saw, a lot of works use the old MPTCP, based on Kernel 5.4 to do that work, my question is: is that possible to do that on the new version already? Or that only will be possible on kernel 6.13/6.14 [#517](https://github.com/multipath-tcp/mptcp_net-next/issues/517)? Is there any way that can add my scheduler?

Thanks in advance!!

**Comment by matttbe** [comment]
Hello,

As mentioned on the ticket #517 you mentioned, referencing #75, this work is still in progress. There are different "toy" packet schedulers implemented in BPF in our development branch, but they need further development, as mentioned in the other tickets.

You can test them if you compile the `export` branch, but they are not ready yet, e.g.:

```
bpftool struct_ops register mptcp_bpf_rr.bpf.o
sysctl net.mptcp.scheduler=bpf_rr
```

I suggest closing the ticket, as it looks like a duplicated issue. If not, please tell us.

**Comment by tiagojoseas** [comment]
Thanks for your reply @matttbe!
