### ISSUE TITLE
MPTCP advanced options in Kernel configuration 

### ISSUE THREAD

**Issue by DanielP2D** [multipath-tcp/mptcp_net-next#527]
Hi All,
I am currently working on a project and the setup is as follows:

Linux_kernel_version:   6.6.57 (the latest LTS)
Ubuntu:                           Ubuntu 24.04 LTS

![flow](https://github.com/user-attachments/assets/c186a3f8-9ab6-4ea8-8af8-6423a161266d)

I have created dedicated network namespaces,
1) client_ns 
2) gateway_ns 
3) network_path_1_ns
4) network_path_2_ns
5) server_ns

I have a shell script ready, which will setup the network before I can bring up the Client and the server applications. 
For client and server scripting, I am using GO LANG

WORKING:
1) I want to implement MPTCP at the router_gateway as I want it to make the decision on whether to use the **network_path_1** or **network_path_2**, but I have an issue here with the configuration, 

oot@daniel-hp:/home/daniel/Downloads/linux-6.6.57# sudo sysctl -a | grep mptcp
net.mptcp.add_addr_timeout = 120
net.mptcp.allow_join_initial_addr_port = 1
net.mptcp.checksum_enabled = 0
net.mptcp.enabled = 1
net.mptcp.pm_type = 0
net.mptcp.scheduler = default
net.mptcp.stale_loss_cnt = 4

when i directly compiled the kernel 6.6.57, i did not get any MPTCP advanced options so i just copied the Kconfig file from the kernel 5.4.243 and pasted it in the Kernel 6.6.57. Now I at least see all the advanced options in the Kernel configuration (make xconfig or make menuconfig), but I am not sure if its a right approach and if it really works as it does not allow to use any other ADVANCED PATH_MANAGER CONTROL or ADVANCED SCHEDULER CONTROL
Can someone please clarify regarding this?
With many of the newer kernel version I used to just see two or three outcomes as shown below, is this normal? How can I play with advanced options if the Kernel does not provide me those options?
CONFIG_MPTCP=y
CONFIG_INET_MPTCP_DIAG=m
CONFIG_MPTCP_IPV6=y

                                     
Additionally, in the future I want to make use of ROUND ROBIN scheduler or play with the other config options and see how throughput varies but read that it will only be supported in the later kernel releases. If that is true then how can I transmit packets between the network_path_1 and network_path_2 alternatively at the moment?

(
v6.6: Forcing using MPTCP with BPF
Allow forcing using MPTCP with BPF ([example](https://git.kernel.org/bpf/bpf-next/c/ddba122428a7))
Refactoring to get rid of msk->subflow
**Preparation for future extension of the packet scheduler**
Some improvements in the selftests: TAP for subtests, uniformity, colours
)

Thank you!
![kernel_configuration](https://github.com/user-attachments/assets/2b16d7c5-6c16-4e9c-b5f3-ca75f0fe4462)

**Comment by matttbe** [comment]
Hi Daniel,

> when i directly compiled the kernel 6.6.57, i did not get any MPTCP advanced options

There are no such advanced options in the upstream Linux implementation. There were some in the old fork, but that's different here.

> so i just copied the Kconfig file from the kernel 5.4.243 and pasted it in the Kernel 6.6.57. Now I at least see all the advanced options in the Kernel configuration (make xconfig or make menuconfig), but I am not sure if its a right approach and if it really works as it does not allow to use any other ADVANCED PATH_MANAGER CONTROL or ADVANCED SCHEDULER CONTROL

That doesn't (**EDIT**) sound like a good idea if you took the config from a fork kernel and tried to apply it here.

> With many of the newer kernel version I used to just see two or three outcomes as shown below, is this normal?

Yes it is.

> How can I play with advanced options if the Kernel does not provide me those options?

What do you want to change? As mentioned on our website, there are for the moment 2 path-manager, and one packet scheduler. More might come later, please check the different tickets that have been created about that.

(Round Robin was developed as a "toy", just to check the modularity was working, but without real use-cases in mind as it is bad from a performance point of view)

>  Preparation for future extension of the packet scheduler

This is not ready yet, please check the different tickets that have been created about that.

**Comment by DanielP2D** [comment]
Thank you for the quick response and patience @matttbe!

> There are no such advanced options in the upstream Linux implementation. There were some in the old fork, but that's different here.

My major doubt is cleared that there are not advanced options in the newer(upstream) Kernel versions.

> That sounds like a good idea if you took the config from a fork kernel and tried to apply it here.

But I am still not convinced if it a right approach because this change is something which does not come with the default Kernel. Anyways, I decided to give it a try on a different machine by compiling Kernel 6.6.58

> What do you want to change? As mentioned on our website, there are for the moment 2 path-manager, and one packet scheduler. More might come later, please check the different tickets that have been created about that.

Two path managers, In-kernel Path-Manager (type 0) userspace Path-Manager (type 1)
One packet scheduler: Default scheduler (based on lowest RTT)

To understand the working of MPTCP, I will stick to In-Kernel path manager and when we say In-Kernel, there is no role of MPTCPD here right?

For example, In my case there are five network namespaces,
![Screenshot from 2024-10-30 21-33-12](https://github.com/user-attachments/assets/9ed3f024-214f-4f02-b14b-a64829613f17)
I want the MPTCP to kick in at the router_gateway(gateway_ns).
How I do this at the moment, I bring up all the network_ns, next, I start the **Server** application, I start the **router_gateway** lapplication located in the gateway_ns (because this behaves as server for the client)  and in the end I start the **client** application from client_ns and it immediately communicates with the **server** located in the server_ns but using TCP only. FROM CLIENT TO THE ROUTER_GATEWAY; I WANT IT TO USE TCP only, so that working as expected.
So my question is, should MPTCP automatically kick in at the router_gateway in the gateway_ns or should I add something in my GO application script for the router_gateway so that it makes use of MPTCP? 
Depending upon various factors, I want the gate_router to decide whether to take the path1 or path2 to reach the end server.

> (Round Robin was developed as a "toy", just to check the modularity was working, but without real use-cases in mind as it is bad from a performance point of view)

Thanks, I will try once I am successful in running the normal MPTCP configuration.

**Comment by matttbe** [comment]
> > That sounds like a good idea if you took the config from a fork kernel and tried to apply it here.
> 
> But I am still not convinced if it a right approach because this change is something which does not come with the default Kernel. Anyways, I decided to give it a try on a different machine by compiling Kernel 6.6.58

Sorry, I missed the "doesn't" word... That does **not** sound like a good idea to do that.
Best to start from a clean environment if you switch from a fork kernel.

> > What do you want to change? As mentioned on our website, there are for the moment 2 path-manager, and one packet scheduler. More might come later, please check the different tickets that have been created about that.
> 
> Two path managers, In-kernel Path-Manager (type 0) userspace Path-Manager (type 1) One packet scheduler: Default scheduler (based on lowest RTT)

Yes, all of that can be changed using `sysctl`.

> To understand the working of MPTCP, I will stick to In-Kernel path manager and when we say In-Kernel, there is no role of MPTCPD here right?

mptcpd can still help to create MPTCP endpoints (`ip mptcp endpoint`). That's what mptcpd does by default. This can also be done manually, or via other automated tools like Network-Manager.

But mptcpd is mainly useful to help to create custom userspace path-manager.

> For example, In my case there are five network namespaces, I want the MPTCP to kick in at the router_gateway(gateway_ns). How I do this at the moment, I bring up all the network_ns, next, I start the **Server** application, I start the **router_gateway** lapplication located in the gateway_ns (because this behaves as server for the client) and in the end I start the **client** application from client_ns and it immediately communicates with the **server** located in the server_ns but using TCP only. FROM CLIENT TO THE ROUTER_GATEWAY; I WANT IT TO USE TCP only, so that working as expected.

If I understood correctly, you want to have something like this:

```
Client --- TCP --- Router === MPTCP === Server
```

In this case, both the router and the server need to support MPTCP, and the router is running a TCP to MPTCP proxy (intercepting TCP connection from the client, and creating a new one to the server using MPTCP), right?

> So my question is, should MPTCP automatically kick in at the router_gateway in the gateway_ns or should I add something in my GO application script for the router_gateway so that it makes use of MPTCP?

Sorry, I'm not sure what you mean here: if you want MPTCP to be used, you need both a client and a server supporting it, and creating MPTCP network sockets. You cannot add "MPTCP" on an ongoing connection without the end hosts knowing about that. If the client cannot support MPTCP, you can add a proxy on a host supporting MPTCP: it will intercept plain TCP connections, and create MPTCP ones with another proxy server, or the end server.

> Depending upon various factors, I want the gate_router to decide whether to take the path1 or path2 to reach the end server.

If you only need to use one path per connection, maybe you don't need **Multipath** TCP? Your router can route some connections on one path, and some on the other one.

It is not clear to me what you want to achieve.

**Comment by DanielP2D** [comment]
Thank you for the quick response once again! I am new to MPTCP and hence finding some things confusing.

> Sorry, I missed the "doesn't" word... That does **not** sound like a good idea to do that. Best to start from a clean environment if you switch from a fork kernel.

Okay, I shall retry it today.

> mptcpd can still help to create MPTCP endpoints (`ip mptcp endpoint`). That's what mptcpd does by default. This can also be done manually, or via other automated tools like Network-Manager.

Got it, I will explore more about this from https://www.mptcp.dev/pm.html#userspace-path-manager

 
> If I understood correctly, you want to have something like this:
> Client --- TCP --- Router === MPTCP === Server
> In this case, both the router and the server need to support MPTCP, and the router is running a TCP to MPTCP proxy (intercepting TCP connection from the client, and creating a new one to the server using MPTCP), right?

Yes, thats absolutely correct. And i guess I did not configure the Server correctly, My understanding was that, a client will  initiate the MPTCP connection and I see this protocol in the Wireshark when the connection is being established. Later depending on whether the Server is capable of MPTCP, it replies using MPTCP , if not then TCP. 

> Sorry, I'm not sure what you mean here: if you want MPTCP to be used, you need both a client and a server supporting it, and creating MPTCP network sockets. You cannot add "MPTCP" on an ongoing connection without the end hosts knowing about that. If the client cannot support MPTCP, you can add a proxy on a host supporting MPTCP: it will intercept plain TCP connections, and create MPTCP ones with another proxy server, or the end server.

I think I get your point. So I will have to program the router, to take in the TCP packets and forward them to the Server as MPTCP. I should work on this TCP to MPTCP conversion and also modify the server code. 
SERVER:
	listenAddress := "10.0.3.1:8080" // Server's address in server_ns
	listener, err := net.Listen("tcp", listenAddress)                             

> > Depending upon various factors, I want the gate_router to decide whether to take the path1 or path2 to reach the end server.
> If you only need to use one path per connection, maybe you don't need **Multipath** TCP? Your router can route some connections on one path, and some on the other one.
> It is not clear to me what you want to achieve.

Sorry, let me try to explain and how I plan to simulate this.
For example, 
1) we have a UE connected to an Access Point(for example, an Access Point in Airport)
2) Access Point (Router in the above architecture) has got two options for connecting to the internet. 
3) Via Service provider 1(private N/W) OR/AND via service provider 2(Public N/W)
4) we would always want to make use of the connection from **service provider 1** path 1 due to some added benefits (better throughput, latency etc)
5) Depending upon the type of data being exchanged between the client and the server, we also want to make use of the connection path from **service provider 2** simultaneously or switch to it seamlessly when there is an outage on the path 1 from service provider 1(Private N/W) as a fallback.
6) I want to study the performance of MPTCP in such scenarios.

**Comment by matttbe** [comment]
> My understanding was that, a client will initiate the MPTCP connection and I see this protocol in the Wireshark when the connection is being established. Later depending on whether the Server is capable of MPTCP, it replies using MPTCP , if not then TCP.

I don't know if the example here is linked to the previous one, but if a random client sends a connection request with MPTCP to a server not supporting MPTCP, the server will reply in "plain" TCP, without MPTCP, and the connection will continue in "plain" TCP.

> So I will have to program the router, to take in the TCP packets and forward them to the Server as MPTCP. I should work on this TCP to MPTCP conversion and also modify the server code.

Sorry to be picky about the wording here, but here it is not a simple "packet forwarding" (or "routing"), but proxying data between a TCP connection (client -- router), and an MPTCP one (router -- server), right?

> also modify the server code.

Yes. If your server code is in Go, and you are using Go >= 1.21, you can either force to use MPTCP with [`GODEBUG=multipathtcp=1`](https://www.mptcp.dev/setup.html#force-applications-to-use-mptcp) or modify the code (see the [example in Go](https://www.mptcp.dev/implementation.html#examples-in-different-languages))

> Depending upon the type of data being exchanged between the client and the server, we also want to make use of the connection path from service provider 2 simultaneously or switch to it seamlessly when there is an outage on the path 1 from service provider 1(Private N/W) as a fallback.

If you have connections that either use only path 1, or both path 1 and 2, then I guess you can route the traffic through patch 1, a simple forwarding, except the ones that need to use both 1 and 2: for those, you intercept them with your proxy, and use MPTCP.

If you always want to use MPTCP, with some connections that use one path at a time, and other that use both, then either you need a custom path-manager, or you play with netns: one per type of traffic. But I guess that's something you can check after once you will want to handle the two cases at the same time.

**Comment by DanielP2D** [comment]
> I don't know if the example here is linked to the previous one, but if a random client sends a connection request with MPTCP to a server not supporting MPTCP, the server will reply in "plain" TCP, without MPTCP, and the connection will continue in "plain" TCP.
 > Sorry to be picky about the wording here, but here it is not a simple "packet forwarding" (or "routing"), but proxying data between a TCP connection (client -- router), and an MPTCP one (router -- server), right?

No problem, thanks for correcting!
"Proxying data: The router acts as a proxy, receiving data from the client over the TCP connection and forwarding it to the server over the MPTCP connection. Similarly, it receives data from the server over the MPTCP connection and forwards it back to the client over the TCP connection."

I will try to work on the changes which you have mentioned and get back to you if I have any doubts. Thanks for the support so far.

**Comment by matttbe** [comment]
Hello,

If I'm not mistaken, all questions asked here have been replied. If that's OK, I'm going to close this ticket. Feel free to re-open it or open a new one if needed.

**Comment by DanielP2D** [comment]
Yes sure, thanks @matttbe!
