### ISSUE TITLE
msk connection state set without msk lock

### ISSUE THREAD

**Issue by mjmartineau** [multipath-tcp/mptcp_net-next#56]
The subflow is setting msk->sk_state without holding the msk lock. Userspace could call shutdown/close concurrently
and get the msk lock, thinking it can change the state without it getting clobbered by the subflow

@pabeni notes that:
We currently use msk->sk_state == TCP_ESTABLISHED as an indication of msk being able to accept/create subflow,
so we can't set the state at accept() time, because due to OoO the the newly create msk could still lack the client key/the path could be not yet validated. A solution could be using a different, new, msk flag to track the 'fully established'/'path validated' status and let check_fully_established() set only the latter

**Comment by pabeni** [comment]
should be addressed in current export branch

**Comment by matttbe** [comment]
@mjmartineau : if we still need to fix some of them, please update the description or open a new one

**Comment by matttbe** [comment]
Last status: the race is still there for the client msk socket. But now much more difficult to raise: seems minor.
