### ISSUE TITLE
(MP)TFO support

### ISSUE THREAD

**Issue by matttbe** [multipath-tcp/mptcp_net-next#59]
There is a section about that in the RFC: https://www.rfc-editor.org/rfc/rfc8684.html#name-tcp-fast-open-and-mptcp

> TCP Fast Open (TFO) is an experimental TCP extension, described in [RFC7413], which has been introduced to allow the sending of data one RTT earlier than with regular TCP. This is considered a valuable gain, as very short connections are very common, especially for HTTP request/response schemes. It achieves this by sending the SYN segment together with the application's data and allowing the listener to reply immediately with data after the SYN/ACK. [RFC7413] secures this mechanism by using a new TCP option that includes a cookie that is negotiated in a preceding connection.
> When using TFO in conjunction with MPTCP, there are two key points to take into account, as detailed below (see RFC)

(Feature from the initial roadmap)

**Comment by matttbe** [comment]
Dmytro Shytyi is working on that.

**Comment by matttbe** [comment]
Note: @dmytroshytyi and @bhesmans are working on that.

**Comment by dmytroshytyi** [comment]
You could find some info on this subject here: [https://dmytro.shytyi.net/mptcp-fast-open-in-linux-kernel/](https://dmytro.shytyi.net/mptcp-fast-open-in-linux-kernel/)

Link to the patch v4.
Changelog
PDF presentation-report.
pcap file.

**Comment by dmytroshytyi** [comment]
Hello,

There is a new version (v15) uploaded to the mailing list:
https://patchew.org/MPTCP/20221106152411.655-1-dmytro@shytyi.net/
Build validation results:
https://github.com/multipath-tcp/mptcp_net-next/actions/runs/3404953313
There is a packetdrill test available:
https://github.com/multipath-tcp/packetdrill/pull/99

Todo:
tools/testing/selftests/net/mptcp/mptcp_connect.(c|sh) is failing. Needs to be improved.

**Comment by matttbe** [comment]
Last "TODO" as discussed at the last meeting:

- [x] Packetdrill for the client side (TODO Matth: check that → done)
- [x] Packetdrill for the server side (we don't have any)
- [x] Remaining socket option? (set key + packetdrill)

**Comment by matttbe** [comment]
Note: I'm looking at adding more packetdrill tests for the server side. I found a bug thanks to that, see #316

**Comment by matttbe** [comment]
2 remaining items before closing this issue:
- [x] review / merge the new packetdrill tests I suggested (task currently assigned to @dcaratti but we can change if needed): https://github.com/multipath-tcp/packetdrill/pulls/matttbe
- [ ] add a new test to validate the server can handle SYN + MPTCP + Cookie request without TS (currently assigned to @dmytroshytyi): https://github.com/multipath-tcp/packetdrill/pull/99

**Comment by matttbe** [comment]
We can close now:
- kernel patches are there:
  - but one "fix" still needed (false positive)
  - tracked in a dedicated issue: https://github.com/multipath-tcp/mptcp_net-next/issues/322
- most packetdrill tests are there:
  - some have been currently skipped due to https://github.com/multipath-tcp/mptcp_net-next/issues/322
  - But tracked: https://github.com/multipath-tcp/packetdrill/pull/112
  - Dmytro might add a new packetdrill test but tracked there: https://github.com/multipath-tcp/packetdrill/pull/99
