### ISSUE TITLE
PM: netlink: events per connection

### ISSUE THREAD

**Issue by matttbe** [multipath-tcp/mptcp_net-next#60]
To be able to have a fine control from userspace.

Idea is port the PM Netlink features from mptcp.org to the upstream kernel. And have it compatible with mptcpd.

(Feature from the initial roadmap)

**Comment by fw-strlen** [comment]
I"m working on this.

**Comment by matttbe** [comment]
Hi @fw-strlen

That's great, thank you!

I was thinking about looking at this one early next year but that's good if you do that before!

Feel free to discuss if you think we need to change the API defined in mptcp.org: https://github.com/multipath-tcp/mptcp/blob/mptcp_trunk/include/uapi/linux/mptcp.h

**Comment by matttbe** [comment]
Validated by @ossama-othman and these patches are now in net-next!
