### ISSUE TITLE
[syzkaller] WARNING in __mptcp_move_skbs_from_subflow

### ISSUE THREAD

**Issue by cpaasch** [multipath-tcp/mptcp_net-next#62]
Crash-trace:

```
------------[ cut here ]------------
WARNING: CPU: 0 PID: 9 at net/mptcp/protocol.c:223 __mptcp_move_skbs_from_subflow+0xb97/0x1440 net/mptcp/protocol.c:223
Kernel panic - not syncing: panic_on_warn set ...
CPU: 0 PID: 9 Comm: ksoftirqd/0 Not tainted 5.8.0-rc4 #14
Hardware name: QEMU Standard PC (i440FX + PIIX, 1996), BIOS rel-1.13.0-0-gf21b5a4aeb02-prebuilt.qemu.org 04/01/2014
Call Trace:
 __dump_stack lib/dump_stack.c:77 [inline]
 dump_stack+0xbe/0xfe lib/dump_stack.c:118
 panic+0x29e/0x6be kernel/panic.c:231
 __warn.cold+0x2f/0x36 kernel/panic.c:600
 report_bug+0x274/0x300 lib/bug.c:198
 handle_bug+0x3c/0x60 arch/x86/kernel/traps.c:235
 exc_invalid_op+0x13/0x40 arch/x86/kernel/traps.c:255
 asm_exc_invalid_op+0x12/0x20 arch/x86/include/asm/idtentry.h:542
RIP: 0010:__mptcp_move_skbs_from_subflow+0xb97/0x1440 net/mptcp/protocol.c:223
Code: fe 8b 5c 24 6c 44 8b 7c 24 34 01 5c 24 24 44 89 fe 89 df 01 5c 24 68 e8 f7 a3 90 fe 44 39 fb 0f 86 8b f9 ff ff e8 c9 a2 90 fe <0f> 0b e8 c2 a2 90 fe 48 8b 4c 24 40 48 b8 00 00 00 00 00 fc ff df
RSP: 0018:ffff88811a967490 EFLAGS: 00010246
RAX: ffff88811a907000 RBX: 0000000000007fe8 RCX: ffffffff82a49039
RDX: 0000000000000000 RSI: ffffffff82a49047 RDI: 0000000000000004
RBP: ffff8880677d2ed8 R08: ffff88811a907000 R09: ffffed100ce97c1e
R10: ffff8880674be0eb R11: ffffed100ce97c1d R12: ffff8880674be000
R13: dffffc0000000000 R14: ffff8880674be0e8 R15: 0000000000007f70
 move_skbs_to_msk+0x18b/0x1b0 net/mptcp/protocol.c:261
 mptcp_data_ready+0xc9/0x2b0 net/mptcp/protocol.c:275
 subflow_data_ready+0x1d2/0x260 net/mptcp/subflow.c:1026
 tcp_data_ready+0xee/0x230 net/ipv4/tcp_input.c:4816
 tcp_data_queue+0x150a/0x4650 net/ipv4/tcp_input.c:4881
 tcp_rcv_established+0x76b/0x1c40 net/ipv4/tcp_input.c:5774
 tcp_v4_do_rcv+0x602/0x8b0 net/ipv4/tcp_ipv4.c:1641
 tcp_v4_rcv+0x252d/0x2e60 net/ipv4/tcp_ipv4.c:2023
 ip_protocol_deliver_rcu+0x2b/0x200 net/ipv4/ip_input.c:204
 ip_local_deliver_finish net/ipv4/ip_input.c:231 [inline]
 NF_HOOK include/linux/netfilter.h:421 [inline]
 ip_local_deliver+0x2da/0x390 net/ipv4/ip_input.c:252
 dst_input include/net/dst.h:449 [inline]
 ip_rcv_finish net/ipv4/ip_input.c:428 [inline]
 ip_rcv_finish net/ipv4/ip_input.c:414 [inline]
 NF_HOOK include/linux/netfilter.h:421 [inline]
 ip_rcv+0xef/0x140 net/ipv4/ip_input.c:539
 __netif_receive_skb_one_core+0x197/0x1e0 net/core/dev.c:5287
 __netif_receive_skb+0x27/0x1c0 net/core/dev.c:5401
 process_backlog+0x1e5/0x6d0 net/core/dev.c:6245
 napi_poll net/core/dev.c:6690 [inline]
 net_rx_action+0x402/0xde0 net/core/dev.c:6760
 __do_softirq+0x18c/0x61a kernel/softirq.c:292
 run_ksoftirqd kernel/softirq.c:630 [inline]
 run_ksoftirqd+0x15/0x20 kernel/softirq.c:622
 smpboot_thread_fn+0x3a2/0x770 kernel/smpboot.c:165
 kthread+0x303/0x410 kernel/kthread.c:291
 ret_from_fork+0x22/0x30 arch/x86/entry/entry_64.S:293
Dumping ftrace buffer:
   (ftrace buffer empty)
Kernel Offset: disabled
Rebooting in 1 seconds..
```

HEAD is at:

382585d1f2ff ("DO-NOT-MERGE: mptcp: enabled by default")  (HEAD, tag: export/20200827T050630, mptcp_net-next/export) (2 days ago) <Matthieu Baerts>
0500323a3a98 ("DO-NOT-MERGE: mptcp: use kmalloc on kasan build")  (2 days ago) <Paolo Abeni>
290efe114633 ("mptcp: simult flow self-tests")  (2 days ago) <Paolo Abeni>
5e30f3b9f4b3 ("mptcp: allow picking different xmit subflows")  (2 days ago) <Paolo Abeni>
29e9676d61be ("mptcp: allow creating non-backup subflows")  (2 days ago) <Paolo Abeni>
1f31eb6c901b ("mptcp: move address attribute into mptcp_addr_info")  (2 days ago) <Paolo Abeni>
dd52e15c6b18 ("mptcp: add OoO related mibs")  (2 days ago) <Paolo Abeni>
f73d4e3e105c ("mptcp: cleanup mptcp_subflow_discard_data()")  (2 days ago) <Paolo Abeni>
8542953c08d3 ("mptcp: move ooo skbs into msk out of order queue.")  (2 days ago) <Paolo Abeni>
42c69d8107f1 ("mptcp: introduce and use mptcp_try_coalesce()")  (2 days ago) <Paolo Abeni>
db964ba8d5bf ("mptcp: basic sndbuf autotuning")  (2 days ago) <Paolo Abeni>
9a6240633587 ("mptcp: trigger msk processing even for OoO data")  (2 days ago) <Paolo Abeni>
af16eb97b98c ("mptcp: set data_ready status bit in subflow_check_data_avail()")  (2 days ago) <Paolo Abeni>
a0f3b1aba54d ("mptcp: rethink 'is writable' conditional")  (2 days ago) <Paolo Abeni>
c0781720b37b ("mptcp: add the incoming RM_ADDR support")  (2 days ago) <Geliang Tang>
1bb30d466a1a ("mptcp: add the outgoing RM_ADDR support")  (2 days ago) <Geliang Tang>
3a1e67afec6c ("mptcp: rename addr_signal and the related functions")  (2 days ago) <Geliang Tang>
e69205303979 ("selftests/mptcp: Better delay & reordering configuration")  (2 days ago) <Christoph Paasch>
cfd4f0531a24 ("bpf: add 'bpf_mptcp_sock' structure and helper")  (2 days ago) <Nicolas Rybowski>
c1514a500db4 ("mptcp: attach subflow socket to parent cgroup")  (2 days ago) <Nicolas Rybowski>
919d98cf04e9 ("bpf: expose is_mptcp flag to bpf_tcp_sock")  (2 days ago) <Nicolas Rybowski>

No reproducers :-/

[EDIT 8/28: Updated HEAD]

**Comment by matttbe** [comment]
@cpaasch do you still see the issue?

**Comment by cpaasch** [comment]
Let's give it another week.

**Comment by matttbe** [comment]
Not seen in one week, can be closed!
