### ISSUE TITLE
packetdrill/fixes: clearing properly the status in listen()/disconnect

### ISSUE THREAD

**Issue by matttbe** [multipath-tcp/mptcp_net-next#65]
Context: [patchwork](https://patchwork.ozlabs.org/project/mptcp/patch/539a0cd36a6ff12d3b8d702a2cb314925a32cd9f.1594996220.git.pabeni@redhat.com/#2485922)

It could be nice to add more coverage in packetdrill to check different scenarios with listen(), especially when getting disconnected. See @pabeni 's comment above

**Comment by pabeni** [comment]
this is addressed via:

commit e8a5f5decf1e844b99b15bc4c3d37e9359531451
Author: Paolo Abeni <pabeni@redhat.com>
Date:   Thu Dec 9 05:48:40 2021 +0000

    mptcp: full disconnect implementation
