### ISSUE TITLE
[interop] IPv4: Attempt to release TCP socket in state 1 00000000cbc88a4a

### ISSUE THREAD

**Issue by cpaasch** [multipath-tcp/mptcp_net-next#66]
I have a simple test, that does the following (netnext here is server, mptcp.org is client):

server-side:
```
fd = socket()
bind(...)
listen(fd, 5)
sleep(5)
close(fd)
```

client-side:
```
fd = socket()
connect()
write(fd, ..., 1)
sleep(10)
close(fd)
```

First I launch the server-program, wait 1 second and then the client.

This triggers a ```IPv4: Attempt to release TCP socket in state 1 00000000cbc88a4a```

**Comment by matttbe** [comment]
Hi Christoph,

Thank you for having opened the new issue.

Just to be sure, the server was using the net-next branch or additional commits on top, e.g. DATA-FIN support?

**Comment by cpaasch** [comment]
This was export-branch with Florian's syn-cookies on top.

**Comment by matttbe** [comment]
Paolo sent a patch upstream fixing this. Here is the version in our export branch: https://github.com/multipath-tcp/mptcp_net-next/commit/61dc31597d6fa996f6ea6a9442bbac8d58169983
