### ISSUE TITLE
selftests: diag: failing with new DATA_FIN patches

### ISSUE THREAD

**Issue by matttbe** [multipath-tcp/mptcp_net-next#68]
Without kernel debug:

```
# selftests: net/mptcp: diag.sh
# no msk on netns creation                          [  ok  ]
# after MPC handshake                               [  ok  ]
# ....chk remote_key                                [  ok  ]
# ....chk no fallback                               [  ok  ]
# check fallback                                    [  ok  ]
# many msk socket present                           [ fail ] expected 200 found 168
not ok 4 selftests: net/mptcp: diag.sh # exit=6
```

With kernel debug:

```
# selftests: net/mptcp: diag.sh
# no msk on netns creation                          [  ok  ]
# after MPC handshake                               [  ok  ]
# ....chk remote_key                                [  ok  ]
# ....chk no fallback                               [  ok  ]
# check fallback                                    [  ok  ]
# many msk socket present                           [ fail ] expected 200 found 194
not ok 4 selftests: net/mptcp: diag.sh # exit=6
```

**Comment by mjmartineau** [comment]
Looks like this is timing related but I'm not sure of the root cause. I see even more failures on a 4-core VM:

```
no msk on netns creation                          [  ok  ]
after MPC handshake                               [ fail ] expected 2 found 0
....chk remote_key                                [ fail ] expected 2 found 0
....chk no fallback                               [  ok  ]
check fallback                                    [ fail ] expected 1 found 0
many msk socket present                           [ fail ] expected 200 found 0
```

This is only a quick look at the problem, of course. I can take a closer look at it in a week or so.

**Comment by pabeni** [comment]
> after MPC handshake                               [ fail ] expected 2 found 0

look like the kernel has been build without 

CONFIG_INET_MPTCP_DIAG

likely because tools/testing/selftests/net/mptcp/config is outdated.

I'll send a patch. I think this is unrelated from the original issue reported by matttbe

**Comment by matttbe** [comment]
> I'll send a patch.

Thank you!

> I think this is unrelated from the original issue reported by matttbe

I guess so, I don't have this issue.
I enable INET_DIAG which turn CONFIG_INET_MPTCP_DIAG on.

**Comment by matttbe** [comment]
Paolo sent a patch upstream fixing this. Here is the version in our export branch: https://github.com/multipath-tcp/mptcp_net-next/commit/606f5a21cae949e582972e35173eb9d2724a2c42
