### ISSUE TITLE
cleanup sendmsg_frag allocation

### ISSUE THREAD

**Issue by pabeni** [multipath-tcp/mptcp_net-next#7]
Currently sendmsg_frag may block with msk socket lock held:

- directly, in the mptcp_page_frag_refill()/mptcp_ext_cache_refill() loop
- indirectly, via do_tcp_sendpages(), if sk_stream_memory_free() fails
- indirectly, via do_tcp_sendpages(), trying to allocate the new skb
- indirectly, via do_tcp_sendpages(), trying to forward allocate the memory account for skb

note mptcp currently pick a subflow only if sk_stream_memory_free() is true, but that condition may change with consecutive calls to sendmsg_frag() due to large user-space buffer.

Blocking with msk socket lock held is bad, we should avoid it. We could try to address with several changes:

- in the  mptcp_page_frag_refill()/mptcp_ext_cache_refill() loop:
     * call sk_stream_wait_memory() on msk, 
     * additionally releasing and acquiring the ssk socket lock around it.
     * loop on memory account conditions, too - that part is tricky, as we can do accurate memory accounting only with more information on pkt size available later 

- [ab-]use skb_tx_cache to pre-allocate the skb in mptcp_page_frag_refill() memory allocation loop

- picking a new subflow if the TCP window is closed/the sendbuf is full for the current one

**Comment by matttbe** [comment]
Note: Florian is looking at this.
