### ISSUE TITLE
[gs]etsockopt per subflow: BPF

### ISSUE THREAD

**Issue by matttbe** [multipath-tcp/mptcp_net-next#76]
@nrybowski is working on it

A short documentation (in the wiki) could be useful!

**Comment by matttbe** [comment]
Unassigning myself (in fact more Nicolas) just in case someone else wants to look at it. Nobody here is actively looking at that one for the moment.

**Comment by geliangtang** [comment]
@matttbe Matt, please give me more details about this issue. I'll try to implement it. Thanks.

**Comment by matttbe** [comment]
@geliangtang I think being able to set/get socket options per subflow from BPF is already possible. What is missing is the documentation and maybe a test.

Back then, Nicolas added a test that was adding a different mark (`SO_MARK`) on each subflow, and changing the TCP CC only on the first subflow: https://github.com/multipath-tcp/mptcp_net-next/blob/scripts/bpf/examples/mptcp_set_sf_sockopt_kern.c
I don't know if Nicolas' test is still OK, as his kernel code had to be adapted.

I think it would be good to have such test in the kernel, so it can be used as an example (and maybe linked to a doc), and be useful to track regressions.
