### ISSUE TITLE
improve packet scheduler for asymmetric links

### ISSUE THREAD

**Issue by pabeni** [multipath-tcp/mptcp_net-next#82]
the simult xmit self-tests fail [more badly] if the used links are asymmetric. 

It looks like the current heuristic (round robin on writable links) tends to  load more the slower links: much more pkts are present in the slower link write queue at shutdown(SHUT_WR) time.

Instead the packet scheduler should try load each subflow proportinally to the subflow sndbuf size

**Comment by matttbe** [comment]
- can be closed
      - similar (with the current infrastructure available)
      - time to stabilise this before extending it
