### ISSUE TITLE
Received DATA_FIN+FIN does not trigger wakeup

### ISSUE THREAD

**Issue by mjmartineau** [multipath-tcp/mptcp_net-next#84]
When receiving a "bare DATA_FIN" on a FIN packet (no data payload), the MPTCP worker thread does not get scheduled. If userspace is blocked on read, it will remain blocked.

Root cause is that the check for a DATA_FIN on an ack packet does not account for the sequence number of the FIN - it checks for seq == end_seq. Also need to look at possibly scheduling a wakeup in other places that the DATA_FIN information is stored for processing by the worker thread.

This affects v5.9-rc3 (current release candidate) and earlier in the 5.9 series, and will require a -net fix.

**Comment by mjmartineau** [comment]
Proposed fix:

http://patchwork.ozlabs.org/project/mptcp/patch/20200904003531.291283-1-mathew.j.martineau@linux.intel.com/

**Comment by matttbe** [comment]
@mjmartineau thx for the bug report!

I tried your patch you sent to the ML but it seems not fixing my issue with Packetdrill (cc @dcaratti ).
I need to investigate more but a `tcpdump -i any -n` didn't show any packet! It was working before. So maybe really something not linked to MPTCP. → so I just opened #85

**Comment by mjmartineau** [comment]
Thanks @matttbe, I wasn't sure the packetdrill issue would be fixed by this.

**Comment by mjmartineau** [comment]
Merged to -net: https://lore.kernel.org/netdev/20200923.173126.2037073365366368611.davem@davemloft.net/
