### ISSUE TITLE
mptcp_close() deletes MPTCP socket before disconnection completes

### ISSUE THREAD

**Issue by mjmartineau** [multipath-tcp/mptcp_net-next#92]
The DATA_FIN changes in v5.9 added code to mptcp_close() to send DATA_FIN, but when the function is called with timeout == 0 it does not wait for the peer to complete the disconnection handshake. The MPTCP socket is immediately deleted in a sequence like this:

1. Userspace calls close() on the MPTCP socket, leading to a call to mptcp_close() with timeout 0
1. DATA_FIN is sent
1. sk_stream_wait_close() does not wait because timeout is 0
1. The connection is immediately moved to the TCP_CLOSED state, the subflows are shut down, and the MPTCP socket is released
1. ACK packets are received from the peer with the DATA_ACK, and then DATA_FIN from the peer.

That final DATA_FIN from the peer is never acknowledged, so the peer keeps resending.

It looks like mptcp_close() needs to handle the non-closed states more like tcp_close() does, and let the protocol close handle final cleanup of the socket.

**Comment by pabeni** [comment]
should be addressed by the recent sendmsg refactor, right?

**Comment by mjmartineau** [comment]
@pabeni, it should be addressed by the sendmsg refactor. I just tested on the export branch and still see the resend behavior, but I think that's because the net-next tree doesn't have all the net fixes yet. I will confirm and close after net-next catches up.

**Comment by mjmartineau** [comment]
The DATA_FIN and DATA_ACKs are exchanged properly with mptcp_trunk v1 protocol - I tested with my own merge of net-next (before 16-Oct merge with Linus' tree) and -net.
