### ISSUE TITLE
simult_flows selftest is unstable: remaining sockets in TIME-WAIT state

### ISSUE THREAD

**Issue by matttbe** [multipath-tcp/mptcp_net-next#99]
When using a debug kernel, my CI reports issues with simult_flows selftest:

```
# selftests: net/mptcp: simult_flows.sh
# balanced bwidth                                     4864 max 5005 [ OK ]
# balanced bwidth - reverse direction                 4817 max 5005 [ OK ]
# balanced bwidth with unbalanced delay               5233 max 5005  [ fail ]
# client exit code 0, server 0
# \nnetns ns3-0-EwnkPH socket stat for 10003:
# State     Recv-Q Send-Q Local Address:Port  Peer Address:Port Process                    
# TIME-WAIT 0      0           10.0.3.3:10003     10.0.1.1:57818 timer:(timewait,59sec,0)
# 	
# TIME-WAIT 0      0           10.0.3.3:10003     10.0.2.1:38533 timer:(timewait,59sec,0)
# 	
# \nnetns ns1-0-EwnkPH socket stat for 10003:
# State Recv-Q Send-Q Local Address:Port Peer Address:PortProcess
# -rw------- 1 root root 8388608 Oct  6 14:08 /tmp/tmp.fA41dwZs3c
# -rw------- 1 root root 8388608 Oct  6 14:08 /tmp/tmp.uTbhkzqGAS
# -rw------- 1 root root 81920 Oct  6 14:08 /tmp/tmp.7v7dguEz4L
# -rw------- 1 root root 81920 Oct  6 14:08 /tmp/tmp.wAXbFuFGCZ
# balanced bwidth with unbalanced delay - reverse direction  4857 max 5005 [ OK ]
not ok 5 selftests: net/mptcp: simult_flows.sh # exit=1
```

According to @pabeni, this could be fixed by patches sent to fix #97: https://patchwork.ozlabs.org/project/mptcp/list/?series=206217

But better to track this in a dedicated issue.

**Comment by pabeni** [comment]
This is possibly/likely caused by oow events we observe on the relevant tree.

Anyway the issue is [almost] addressed by "mptcp: cope better with tcp_sendpage allocation".

(TCP) sockets in time_wait are the expected result at the end of the test.

**Comment by pabeni** [comment]
@matttbe: is this still reproducible on current export branch? I don't see this errors locally since some time

**Comment by matttbe** [comment]
@pabeni thx for the message!

I cannot reproduce the issue. My CI last saw it the 23rd of October which is still after having applied these two patches:

- 325abb8bd3d0: tcp: factor out tcp_build_frag()
- c573a4caa599: mptcp: use tcp_build_frag()

But nothing since then. I guess we can close this one.
